### ISSUE TITLE
Identify potential new developers through authorship analysis

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#10]
It should be possible to do a rough analysis of authorship information of PRs -- and the activity on those PRs -- to make it easier to figure out who to consider giving commit privileges to.

**Comment by srkunze** [comment]
Do you mean something like this? https://github.com/saltstack/salt/graphs/contributors

**Comment by brettcannon** [comment]
I haven't decided yet. 😄  While the graphs can be restricted by time length, it does include committers and in this instance I only care about authors. I also don't know if any analysis of the involved PRs would be desired, etc. But I do suspect that at least to start we will use the contributors graph GitHub provides on a restricted timeline to try and quickly spot potential candidates.

**Comment by brettcannon** [comment]
I'm closing this as once we have authorship information we should be able to look at a year-long timescale in the GitHub graph page and see which non-team members are there.
