### ISSUE TITLE
Automate backport PR creation

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#100]
Maybe we can use this to automate the PR creation in `cherry_picker.py`: 
https://github.com/jd/git-pull-request 

Blog post: 
https://julien.danjou.info/blog/2017/git-pull-request-command-line-tool 

Update:
Use gidgethub instead. For authentication, we'll use a personal access token, specified in the environment variable.

**Comment by Mariatta** [comment]
Hmm but this requires people to write their GitHub credentials to write your GitHub credentials to `~/.netrc` file, as mentioned in their readme:

```
machine github.com login jd password f00b4r
```


Not sure if users will be comfortable with this idea?

**Comment by matrixise** [comment]
Normally the .netrc file is readonly for the owner but maybe there is the capability to use a token, we can ask to Julien, it's a core dev of OpenStack at Redhat and I know him and also @haypo

**Comment by Mariatta** [comment]
Thanks @matrixise :)

I guess in the end it comes to the question of how we can store the password / token securely. 
We can also use Brett's gidgethub to create the PR, the question is still: how to we store the token/credential securely? 

@brettcannon how do you store the credentials when gidgethub is used for ni or bedevere?

**Comment by jd** [comment]
There are plenty of other options, such as using keyrings (OS X or GNOME have that as builtin), token etc.

I took the `.netrc` approach as it's easy and standard, but the code should make it pretty easy to add any new better/easier mechanism!
