### ISSUE TITLE
b.p.o. and the attached PRs

### ISSUE THREAD

**Issue by matrixise** [python/core-workflow#115]
@brettcannon in the interface of b.p.o, for an issue, if there is a PR, could we have the attached version of Python ?

for example, with this issue, there are 3 PR https://bugs.python.org/issue29870 but we don't know the affected version of Python.

Is it possible?

Thank you,

Stéphane

**Comment by brettcannon** [comment]
That's a feature request for bugs.python.org so that should be filed at http://psf.upfronthosting.co.za/roundup/meta/.
