### ISSUE TITLE
Check that generated files are up to date

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/core-workflow#118]
It is easy to forgot regenerating generated code after making changes (especially changes affecting Argument Clinic code). It would be nice if a bot checks this kind of errors. Just checkout the sources, run `make clinic`, `make regen-all`, and check that they are success and don't change any file.

**Comment by ncoghlan** [comment]
Thanks @serhiy-storchaka, I was just coming here to file the same issue.

The specific prompt for this suggestion: I'd missed that the patch for https://bugs.python.org/issue19180#msg295524 updated some Argument Clinic inputs, so neither the original submission nor the backport included the regenerated files.

**Comment by zware** [comment]
Fixed by python/cpython#2080, python/cpython#2092, python/cpython#2093, and python/cpython#2094.

**Comment by serhiy-storchaka** [comment]
Thank you @zware!
