### ISSUE TITLE
Move all of cherry_picker's code into its own directory

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#125]
Right now we have cherry_picker's `setup.py` file, etc. at the root of the repo. But once blurb is moved over here to centralize all workflow-related code, we will have conflicting `setup.py` files, etc. So we will end up needing make the top-level `cherry_picker` directory to hold **all** files for  the project so they aren't in the top-level directory.

**Comment by Mariatta** [comment]
I made a PR, where I moved MANIFEST.in, setup.cfg, and setup.py to cherry_picker directory.
But now I'm wondering whether it will be preferred to have another level of cherry_picker directory beneath that? 

eg
```
- core-workflow/
  - cherry_picker/
    MANIFEST.in
    setup.cfg
    setup.py
    - cherry_picker/
      __main__.py
      cherry_picker.py
      ...     
```

Currently in PR 127:

```
- core-workflow/
  - cherry_picker/
    MANIFEST.in
    setup.cfg
    setup.py
    __main__.py
    cherry_picker.py
    ...     
```

**Comment by brettcannon** [comment]
I was thinking option 1.

**Comment by Mariatta** [comment]
Thanks. I made the change.
