### ISSUE TITLE
Bot to check for issues in PR titles

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#13]
Can be a status check to make sure they are formatted correctly.

**Comment by brettcannon** [comment]
@warsaw has asked this be a status check instead of a bot with a comment to really put it in your face that you forgot an issue number (unless there's a "trivial" label on the PR). This could also be combined with a Misc/NEWS check for #6 since if something required an issue it probably requires a NEWS entry (unless, once again, it's "trivial").

**Comment by warsaw** [comment]
You'll have to modify some details, but [this script](https://github.com/CanonicalLtd/ubuntu-image/blob/master/debian/tests/haschangelog) might give you a head start.

**Comment by brettcannon** [comment]
Thanks. I also wrote my own async GitHub library (https://github.com/brettcannon/gidgethub), so I probably can't pull too much from there. 😉

**Comment by brettcannon** [comment]
I've created https://github.com/python/bedevere that does this check (and will do more things in the future). I will turn it on when I'm not sick and up for watching it for problems.

**Comment by brettcannon** [comment]
I just turned on Bedevere, so this is now done!
