### ISSUE TITLE
Make knight description explicit says when will retry the CLA signed

### ISSUE THREAD

**Issue by mlouielu** [python/core-workflow#131]
When the first-time contributor didn't sign CLA, or signed but not update correctly on b.p.o, it will pop-up a message to says how to sign and the detail for how-to-do. But most of the time contributor will then leave a message says 「they have been signed and when or how the label will be removed.」

Although the link in devguide says it will `you can either ask for the CLA check to be run again or wait for it to be run automatically the next time you push changes to your PR.`, I think Knight can add a new line at the end, says that 「label will be retry when Member removed `CLA not signed` or another push」. To eliminate contributor's question.

**Comment by brettcannon** [comment]
So issues  about the CLA bot should be reported at https://github.com/python/the-knights-who-say-ni. But specifically for this, it isn't a detail that a PR submitter needs to know about since they can't remove a label. It's purely just for a core dev to deal with.
