### ISSUE TITLE
Run blurb as part of Travis

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#147]
Maybe as part of the doc build we run `blurb merge` or `blurb release` to verify all news entries render appropriately?

@larryhastings

**Comment by nightlark** [comment]
Other than the bit about running on Travis likely being outdated, is this something that you would want have set up to run on GitHub Actions?

**Comment by hugovk** [comment]
The blurb tool has recently been added to the CI as part of https://github.com/python/cpython/pull/30009.

Please see PR https://github.com/python/cpython/pull/30419 which uploads the `NEWS` file as a build artifact, so it may be inspected after the build.
