### ISSUE TITLE
`pip install` does not work for cherry_picker

### ISSUE THREAD

**Issue by pitrou** [python/core-workflow#149]
The `readme.rst` seems outdated:
```
(cherry_picker) antoine@fsol:~/cpython/core-workflow/cherry_picker $ pip install .
Directory '.' is not installable. File 'setup.py' not found.
```

**Comment by Mariatta** [comment]
We use `flit` now, so the command will be `flit install .` 

`pip install cherry_picker` still works, it will install the released package in PyPI.
I can make a release today that'll include the latest change: #148.

**Comment by Mariatta** [comment]
Correction.. the command is "flit install" (without the dot)

**Comment by brettcannon** [comment]
It should be mentioned that once PEP 517 is done and pip supports it then `pip install .` will work again, so it's coming. 😉

**Comment by Mariatta** [comment]
v.0.1.0 is in PyPI now, so you can do `pip install -U cherry_picker`
