### ISSUE TITLE
blurb refuse to work without setting EDITOR env

### ISSUE THREAD

**Issue by nirs** [python/core-workflow#154]
blurb is too picky:
```
$ python3 /home/nsoffer/src/core-workflow/blurb/blurb.py 
Error: Could not find an editor! Set the EDITOR environment variable.
```

Git is happy on this system using vim, why blurb has to be so picky?

**Comment by Mariatta** [comment]
Perhaps this is something that needs to be mentioned in the readme, that an EDITOR environment variable should exists.  
On Macbook somehow I did not have to set the EDITOR env variable.

**Comment by nirs** [comment]
Same here on Fedora 25, EDITOR does not exists unless you add it. Using EDITOR is a good idea, but if it is not set, blurb can use a default.

**Comment by nirs** [comment]
I think both #156 and #155 can be useful to fix this issue.

**Comment by larryhastings** [comment]
"vim" isn't an acceptable default value; it's difficult to use, and a user who is so inexperienced at UNIX that they don't have EDITOR set will likely not be familiar with how to use it.

On platforms where acceptable defaults exist, blurb will use them:

- On Windows, blurb will default to notepad.
- On POSIX platforms, it will default to /etc/alternatives/editor if it exists.  (/etc/alternatives is a Debian thing.)
- On OS X, Ned Deily assured me that no default needed to be set.

I considered adding "nano" to the list of default editors for POSIX platforms but I figured /etc/alternatives basically covered it.  The Linux newbies would likely be on a Debian-based distro, where /etc/alternatives would exist.

Also, if you run

    % EDITOR=vim blurb

that will tell blurb to use vim.

**Comment by larryhastings** [comment]
Wait, it *does* have "nano" in the defaults.  You don't have "nano" installed?!

**Comment by nirs** [comment]
Checking new Fedora 25 install, nano is installed by default. Turns out that I removed this package about a year ago for some reason. So nano seems a good fallback.

**Comment by brettcannon** [comment]
Closing this since the current defaults are acceptable.
