### ISSUE TITLE
Start using CODEOWNERS

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#160]
https://github.com/blog/2392-introducing-code-owners

Since mention-bot seems to be perpetually down, we might as well drop it and switch over to the [CODEOWNER file](https://github.com/blog/2392-introducing-code-owners) instead. Not sure how we want this to interact with https://devguide.python.org/experts/, though (e.g. script to generate CODEOWNERS from the experts file, link to CODEOWNERS from the experts file?).

**Comment by brettcannon** [comment]
FYI the free mention-bot instance we were using is down which used to do something similar for us: https://github.com/facebook/mention-bot/issues/230. So it might be time to drop mention-bot and just switch to this opt-in solution.

**Comment by Mariatta** [comment]
I started the CODEOWNERS file https://github.com/python/cpython/pull/2924

Haven't really thought how to add in the experts list from the devguide to CODEOWNERS file 😛 

Should we first verify if the list of experts is accurate?

**Comment by Mariatta** [comment]
Also, the experts list contains b.p.o usernames. We need GitHub userid for CODEOWNERS.

**Comment by brettcannon** [comment]
Yep, which is why I haven't just added `CODEOWNERS` since there's no good solution. 😉  I would say we should drop `experts.rst` and just use `CODEOWNERS`, but that won't work since we need that for the nosy list on bugs.python.org. We could query b.p.o for people's GitHub usernames, but that doesn't translate to file globs that `CODEOWNERS` needs.

I think we're stuck with comments in both files saying "make sure to update the other one as appropriate" and cross-linking so people know about both files. 😞

**Comment by brettcannon** [comment]
And we should just tell people to add themselves to `CODEOWNERS` once the file is in instead of making bad assumptions about which files they care about.

**Comment by Mariatta** [comment]
We now have `CODEOWNERS` file (https://github.com/python/cpython/pull/2924), and `.mention-bot` has been removed from all branches (https://github.com/python/cpython/pull/2923)! :taco:

**Comment by brettcannon** [comment]
Thanks for the PRs, @Mariatta !
