### ISSUE TITLE
Create a list of tools we use with the new workflow

### ISSUE THREAD

**Issue by berkerpeksag** [python/core-workflow#164]
It would be nice to gather all the tools we use in a list so we can easily report bugs or feature requests without having to search on Google or list archives. Plus, future contributors can easily find them if they are looking for an alternative area to work on.

Suggested tools:

* https://github.com/python/bedevere
* https://github.com/python/the-knights-who-say-ni
* https://github.com/berkerpeksag/cpython-emailer-webhook
* https://github.com/berkerpeksag/cpython-bpo-linkify

Suggested format:

Name | Description | Issue tracker | Owner/Maintainer
---- | ----------- | ------------- | ----------------
[python/bedevere](https://github.com/python/bedevere) | A bot to help identify missing information for CPython pull requests | [GitHub](https://github.com/python/bedevere/issues) | [Brett Cannon](https://github.com/brettcannon)

**Comment by Mariatta** [comment]
Do you think the above list can be added here in the readme of core-workflow, or in the dev guide?

**Comment by brettcannon** [comment]
I think the README works; don't see why someone wanting to contribute to CPython is explicitly going to care about where the tools come from, just how to use them.

**Comment by berkerpeksag** [comment]
Yes I agree, `core-workflow/README.rst` would be a better place to put the list.

**Comment by pablogsal** [comment]
I am so sorry for the spam. Clearly, GitHub doesn't like `git --amend' of commits that refer to issues.
