### ISSUE TITLE
Allow release managers to build releases-in-progress on Travis CI

### ISSUE THREAD

**Issue by larryhastings** [python/core-workflow#165]
The current `.travis.yaml` file restricts builds on Travis CI to `master` and `\d.\d`.  I'm not going to second-guess the thought process behind preventing other people from using Travis CI on their PRs etc.  But: release managers do vital work with CPython, and it'd be nice if they could confirm that the release they're working on built correctly on Travis CI.

Right now the release process is a little in flux, given the move to GitHub etc.  But the current thinking is that we create a branch with the release name (e.g. "3.7.0a1", "3.4.7rc1", "3.5.4") on our personal GitHub fork of CPython.

I think all that's necessary is to change the second regex under `branches` to something like `/^\d\.\d(\.\d+((a|b|rc)\d+)?)?$/` (did I do that right?).

**Comment by brettcannon** [comment]
So the reason for the restriction is to not waste time building as a branch stuff like `fix-spelling-mistake` branches someone might make through the web UI. But updating the regex to support in-dev branches is totally fine in my opinion.

And yes, your regex looks right. 😄

**Comment by webknjaz** [comment]
It looks like this issue is not relevant anymore.
