### ISSUE TITLE
blurb and `garglemox` ?

### ISSUE THREAD

**Issue by matrixise** [python/core-workflow#166]
@larryhastings why ``path = os.path.abspath("garglemox")`` at https://github.com/python/core-workflow/blob/master/blurb/blurb.py#L659 ?

**Comment by berkerpeksag** [comment]
Larry already explained it in the following comment:

```py
# we intentionally start in a (probably nonexistant) subtree
# the first thing the while loop does is .., basically
```

Copied from https://github.com/python/core-workflow/blob/2b04c97818c4ae303f833d0c5be7d6d7a5e38fb7/blurb/blurb.py#L657-L658

**Comment by matrixise** [comment]
thanks @berkerpeksag  I close this issue
