### ISSUE TITLE
blurb not compatible with Python 3.4 used on docs.iad1.psf.io

### ISSUE THREAD

**Issue by JulienPalard** [python/core-workflow#169]
In order to run blurb while building documentations (https://github.com/python/docsbuild-scripts/issues/14) we upgraded the documentation build venv from Python 2 to Python 3 (https://github.com/python/psf-salt/issues/109).

The distro we're using provides Python 3.4 (https://github.com/python/psf-salt/issues/109#issuecomment-320144061), but blurb is not Python 3.4 compatible:

```
  File "blurb/blurb.py", line 1049
    subprocess.run(["git", "add", *git_add_files], stdout=subprocess.PIPE, stderr=subprocess.PIPE).check_returncode()
                                         ^
SyntaxError: can use starred expression only as assignment target
```

**Comment by Mariatta** [comment]
`blurb`'s readme says: "blurb's only dependency is Python 3.5+."
So I'd say, please use Python 3.5+?

**Comment by JulienPalard** [comment]
@Mariatta Yes but blurb needs to run on `docs.iad1.psf.io` (server behind `docs.python.org`) which does not have Python 3.5 (https://github.com/python/psf-salt/issues/109#issuecomment-320144061).

As making blurb 3.4 compatible looked easy, I tried it, it may (or may not, I probably didn't test everything) solve the problem with less pain than a full server upgrade, fixing one thing at a time.

**Comment by JulienPalard** [comment]
docs.iad1.psf.io now have Python 3.6.

Due to a bug in 3.4 (see https://github.com/python/core-workflow/issues/171 and https://github.com/python/core-workflow/pull/170) blurb will not be compatible with 3.4, let's keep the 3.5+ requirement.
