### ISSUE TITLE
Unexpected space with `blurb merge` and python 3.4

### ISSUE THREAD

**Issue by JulienPalard** [python/core-workflow#171]
For the following lines in the cpython 3.4 branch (commit 362e9fb):

```
$ git grep -C1 'Pythons use gcc-4.0 and the 10.4u' Misc/NEWS.d/
Misc/NEWS.d/3.3.0a1.rst-Distutils LDSHARED configuration variable for OS X. (Note, the python.org
Misc/NEWS.d/3.3.0a1.rst:32-bit-only Pythons use gcc-4.0 and the 10.4u SDK, neither of which are
Misc/NEWS.d/3.3.0a1.rst-available in Xcode 4.  This change does not attempt to override settings to
```

using Python 3.5 to execute `blurb merge` correctly gives:

    OS X. (Note, the python.org 32-bit-only Pythons use gcc-4.0 and the 10.4u

But running `blurb merge` with Python 3.4.3 gives a space between `32` and `-bit`:

    OS X. (Note, the python.org 32 -bit-only Pythons use gcc-4.0 and the 10.4u

It's expected (https://github.com/python/core-workflow/pull/170#issuecomment-320206299) that this is simply an issue from textwrap.wrap that has been fixed between 3.4 and 3.5.

**Comment by larryhastings** [comment]
I traced it down.  Here's a minimal test case:

```
text = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n32-bit-only'

import textwrap
x = textwrap.wrap(text, width=76)
print(x)
```
Without the bugfix, the line is split between "32" and "-".  With the bugfix applied "32-bit-only" remains one word.

The behavior was changed in git revision 72bd327db0b, checked in 2015-03-24 by Serhiy Storchaka, in regards to issue bpo-22687 ("horrible performance of textwrap.wrap() with a long word").  This made it into 3.5.0a3, but has never been backported to 3.4, and at this point it shouldn't be as 3.4 is in security-fixes-only mode.

So, uh, maybe blurb can't support 3.4?  Unless we wanna do something crazy like monkeypatch textwrap or something.

**Comment by JulienPalard** [comment]
We'll have to hear from the infra team about the possibility of upgrading Python. I went on the path of backporting blurb to 3.4 because it seemed easier and faster (and was not excluding a future upgrade). If it's hard, it's the wrong way.

The compromise may be: If the software upgrade take a long time, we'll still be able to merge this so blurb work (with a single strange space) in the meantime. I don't know what it take, I'll ask.

**Comment by JulienPalard** [comment]
I'm closing this. Won't fix as this is a bug in textwrap, and blurb won't support Python 3.4.
