### ISSUE TITLE
Do post-merge checks on PRs to remind committers what to do when they forget something

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#172]
E.g. rewrite the commit message, change `#12345` to `GH-12345`, etc. The idea is that if after a merge it's discovered a core dev forgot to do something then a comment on the PR can be left reminding them what to try and remember what to do next time.

https://mail.python.org/pipermail/python-committers/2017-July/004678.html
https://mail.python.org/pipermail/python-committers/2017-August/004788.html

**Comment by Mariatta** [comment]
This is tracked in https://github.com/python/bedevere/issues/14, so I'm closing this.
The only thing left is about reminding people to cleanup the asterisks in the commit message. (Number 3 in the issue).
