### ISSUE TITLE
blurb should error out if run with a Python interpreter which is too old

### ISSUE THREAD

**Issue by rodrigc** [python/core-workflow#173]
The blurb command relies on Python 3.5+ in order to run.
If run with an older Python interpreter, weird errors happen such as:

```
   File "/usr/bin/blurb", line 123
     def textwrap_body(body, *, subsequent_indent=''):
                              ^
SyntaxError: invalid syntax
```

For newcomers to Python, this is hard to figure out.

blurb should error out if the Python version is too old.
I recommend that the code check the value of `sys.version_info` and
error out with a message indicating that the Python version is too old.

**Comment by rodrigc** [comment]
@caavery ran into this issue

**Comment by zware** [comment]
The problem is that the SyntaxError is thrown before we have a chance to check sys.version_info.  There are any number of more or less horrible hacks that can be added to make this check, but I'm not sure whether any of them are worth it.

/cc: @larryhastings

**Comment by larryhastings** [comment]
They're not.  blurb should be installed using "pip", and that will fail if you use python < 3.5.  This is a rare circumstance, and as Zachary points out, painful to fix.

**Comment by CuriousLearner** [comment]
I think this needs to be handled. I faced the same issue and the blurb gets successfully installed with Python < 3.5.

**Comment by haypo** [comment]
We can add a simple test on sys.version to prevent any attempt to install blurb on Python older than 3.5.

**Comment by rodrigc** [comment]
@haypo @CuriousLearner See: https://github.com/python/core-workflow/issues/174

pip falls back to installing a version of blurb which does not fail if installed on Python 2.7.
