### ISSUE TITLE
blurb: get rid of spaces in paths

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/core-workflow#186]
I suggest to rename the "`Core and Builtins`" directory to "`Core_and_Builtins`" and make `blurb` automatically converting underscores to spaces and back. This would help to select paths in terminal with mouse.

**Comment by encukou** [comment]
`C API/` is similarly unpleasant to work with.

**Comment by merwok** [comment]
The PR is ready for review.

If Serhiy and Petr both approve, do we need a discussion on Discuss? Just a notice?

**Comment by encukou** [comment]
A notice would be appropriate. And it'll turn into a discussion :)

**Comment by hugovk** [comment]
This is now released in blurb 1.2.0 and blurb-it has also been updated.

Please upgrade!

https://discuss.python.org/t/new-blurb-1-2-please-upgrade/59159
