### ISSUE TITLE
Don't wait for allowed_failures on travis builds?

### ISSUE THREAD

**Issue by dstufft** [python/core-workflow#19]
Currently we have a matrix item in Travis for ``allowed_failure``. This is fine to do, but travis won't mark the build successful or failed until that job has finished even though it won't ultimately effect the outcome. One option we can do is to set:

```yaml
matrix:
  fast_finish: true
```

Which will tell travis to report the status of the job as soon as all of the non allowed failure builds are done, while still running the allowed failure build.

**Comment by brettcannon** [comment]
Fine by me, although knowing the coverage can be useful (but I suspect people will wait to see that report anyway). So I say submit a PR! 😄

**Comment by brettcannon** [comment]
Documentation of the configuration value: https://docs.travis-ci.com/user/customizing-the-build#Fast-Finishing

**Comment by brettcannon** [comment]
Thanks for merging and closing, @dstufft !
