### ISSUE TITLE
The PR is blocked by the issue-number check

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/core-workflow#199]
The bedevere bot hanged on the issue-number check and blocks merging https://github.com/python/cpython/pull/142.

**Comment by brettcannon** [comment]
Just closed and re-opened the PR and it seems fine now.

**Comment by serhiy-storchaka** [comment]
Thanks. I did the same 3 days ago, but this didn't help.

**Comment by brettcannon** [comment]
Yeah, I noticed you tried and it didn't work for some reason. I assume it was a hiccup either between GitHub, Heroku, or the code for Bedevere that worked itself out.

**Comment by ioanatia** [comment]
What seemed to fix the issue was not the reopening of the PR, but the fact that I rebased the branch.
It is an old PR that was opened before the issue number check was introduced.
