### ISSUE TITLE
Hook up Codecov for coverage reporting on C code

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#2]
See https://github.com/brettcannon/cpython-ci-test/blob/master/codecov.yml for an initial configuration (only differs from the default thanks to the `new` config for comments).

**Comment by tiran** [comment]
I have been running lcov regularly. gcov / lcov coverage of C code is a bit tricky for some modules. Some tests require a real terminal (ncurses), X server (tkinter, idle), root privileges (spwd) or special system configuration (yp for nis). The ```make coverage-lcov``` target ignores coverage of 3rd party code, too.

```
        @ # remove 3rd party modules, system headers and internal files with
        @ # debug, test or dummy functions.
        @lcov --remove $(COVERAGE_INFO) \
            '*/Modules/_blake2/impl/*' \
            '*/Modules/_ctypes/libffi*/*' \
            '*/Modules/_decimal/libmpdec/*' \
            '*/Modules/_sha3/kcp/*' \
            '*/Modules/expat/*' \
            '*/Modules/zlib/*' \
            '*/Include/*' \
            '*/Modules/xx*.c' \
            '*/Parser/listnode.c' \
            '*/Python/pyfpe.c' \
            '*/Python/pystrcmp.c' \
            '/usr/include/*' \
            '/usr/local/include/*' \
            '/usr/lib/gcc/*' \
            --output-file $(COVERAGE_INFO)
```

**Comment by brettcannon** [comment]
Would we run lcov as a separate coverage step from coverage.py? Or somehow run them simultaneously? I don't know what kind of slowdown we're looking at here if we had both on and if we might run afoul of Travis' free tier limitations.

**Comment by tiran** [comment]
On my machine it takes almost 10 minutes to run Python's test suite with a gcov instrumented build of Python. My laptop is pretty fast (8 cores ```i7-4900MQ CPU @ 2.80GHz```, 16 GB RAM). I'm able to utilze all cores with 10 parallel test process. It's going to be hard enough to get lcov finish on Travis without coverage.py.

```
$ make coverage
$ time make test
...
real    9m40.226s
user    56m49.298s
sys     1m17.350s
```

**Comment by brettcannon** [comment]
OK, then we can look at running it as a separate test. If you want to try and get this working now then send a PR at https://github.com/brettcannon/cpython-ci-test as that's where I plan to pull the initial config files for Travis and Codecov.

**Comment by tiran** [comment]
I have to look into it. I'd like to use a service that can use lcov database so we can re-use out-of-tree build and lcov excludes from ```make coverage-lcov```.

**Comment by brettcannon** [comment]
It looks like lcov is supported by Codecov: https://github.com/codecov/codecov-bash/blob/master/codecov#L822

**Comment by brettcannon** [comment]
Did you want me to leave this open for you, @tiran to look into lcov?

**Comment by abalkin** [comment]
Please take a look at  <https://github.com/abalkin/cpython/tree/ci> or specifically at <https://codecov.io/gh/abalkin/cpython/branch/ci>.  @brettcannon is that the "appropriate merging" that you are looking for?

**Comment by brettcannon** [comment]
@abalkin unfortunately no as there's no coverage for the Lib/ directory. If you include coverage runs for both lcov and coverage.py do the results show up in Codecov as if they were run together?

**Comment by abalkin** [comment]
Right.  I thought I've seen both, but clearly my focus was on C coverage.

We are evaluating codecov's commercial offering in my firm at the moment, so I should have a working setup "soon".

**Comment by brettcannon** [comment]
Tweaked the title in hopes that someone is able to look into getting C code coverage working.

**Comment by ammaraskar** [comment]
and here it is as part of the pull request: https://codecov.io/gh/python/cpython/tree/f2148586600ea3a2c4a04550105f32d561f100aa

**Comment by brettcannon** [comment]
Great work! Hopefully one of us will be able to review python/cpython#7773 shortly.

**Comment by brettcannon** [comment]
This is now merged!
