### ISSUE TITLE
Support for NEWS entries that relate to more than one bpo issue

### ISSUE THREAD

**Issue by bitdancer** [python/core-workflow#202]
I have a PR that closes more than one bpo issue (and no, the issues are not duplicates).  Apparently the blurb file format does not support this.  In the old days we'd just list the numbers separated by commas, and I think the rst translator was smart enough to linkify them all (but I'm not sure).  So, I don't know if this is a doc issue or a feature request.

**Comment by terryjreedy** [comment]
I think you should submit two blurb files, with different bodies for the different issues.   The bot should not prevent this, and it does not matter to the changelog if two files were added in the same PR.  This is so rare that I don't think we need to do anything special except mention this solution in the devguide.

**Comment by larryhastings** [comment]
You can just mention the other issues in the text.

**Comment by larryhastings** [comment]
We discussed this, and IIRC I was instructed to just support a single issue.  Multiple issues is rare enough that it wasn't worth bothering with, or something.  Anyway, the bpo you give to blurb should be the "primary" issue (assuming you have one), and then you should add "(See also: bpo-XXXX)" to the end of your text body.  That's the same thing blurb did when translating old entries from Misc/NEWS.
