### ISSUE TITLE
Tweak the "A Python core developer has requested some changes" workflow

### ISSUE THREAD

**Issue by 1st1** [python/core-workflow#204]
"A Python core developer has requested some changes " message prompting the user to post a comment "I have made the requested changes; please review again" is a bit too involved.  Some issues contain a few of these comments (and corresponding messages from bedevere-bot).

How about instead of requiring a user to post that comment, we simply ask them to remove the "awaiting changes" label?  The bot can detect that, and add the "awaiting review", and notify the reviewers.

**Comment by Mariatta** [comment]
Only those with write access can remove labels: core devs and bedevere-bot.
