### ISSUE TITLE
blurb: inconsistent spacing in changelog.html

### ISSUE THREAD

**Issue by ned-deily** [python/core-workflow#209]
The rendered ``changelog.html`` files produced with ``blurb`` and ``make html`` have inconsistent spacing between items.  Usually, the first changelog topic section (e.g. Security) starts with no blank lines between items but occasionally some subsequent sections will render with a blank link between items; this seems to be often true for the Library section, but not always.  This is visible across the blurbified 3.x branches; here's an example with the stable 3.5 docs:

Library section has blank line separator:
https://docs.python.org/3.5/whatsnew/changelog.html#id5

Library section has no blank separators:
https://docs.python.org/3.5/whatsnew/changelog.html#id11

**Comment by larryhastings** [comment]
blurb generates identical formatting in the RST file.  It looks to me like the RST to HTML converter is the one that's being inconsistent, and I have no idea why.  But this isn't blurb's doing.

**Comment by ned-deily** [comment]
But it's easier to blame blurb! (Thanks for investigating.)

**Comment by larryhastings** [comment]
Note also that the changelog displayed this behavior long before blurb was created.  For example, here's the changelog from 3.4.4, released in 2015.

With blank line separator:

https://docs.python.org/release/3.4.4/whatsnew/changelog.html#id152

Without blank line separator:

https://docs.python.org/release/3.4.4/whatsnew/changelog.html#id2

**Comment by ned-deily** [comment]
I've opened a doc bug: https://bugs.python.org/issue32523
