### ISSUE TITLE
Adjust coverage failure threshold

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#21]
Codecov lets us specify [how much of a coverage drop is acceptable](https://docs.codecov.io/docs/commit-status#section-threshold). Since we are seeing some [PRs fail by just adding an extra comment line](https://github.com/python/cpython/pull/20), we should probably set a threshold of some sort to say a slight drop is acceptable. I'm thinking maybe 0.01% is okay?

And the [configuration can be validated](https://docs.codecov.io/docs/codecov-yaml#section-validate-your-repository-yaml).

**Comment by zware** [comment]
There is also some [random noise](https://codecov.io/gh/python/cpython/pulls/16/changes) in the coverage results that we might need to track down and mitigate.
