### ISSUE TITLE
Travis has an issue with the C build?

### ISSUE THREAD

**Issue by matrixise** [python/core-workflow#218]
Hi all, 

Today I have worked on this issue https://bugs.python.org/issue1100942 and I was waiting for the build of my PR (https://github.com/python/cpython/pull/5578) and I was really surprised to see 57sec for a test.

```
Files changed: 
Doc/library/datetime.rst Lib/_strptime.py Lib/datetime.py Lib/test/datetimetester.py Misc/NEWS.d/next/Core and Builtins/2018-02-07-10-55-58.bpo-1100942.md4agI.rst Modules/_datetimemodule.c
Only docs were updated, stopping build process.
```

I have modified one .c file, three .py files and it has only detected the change in the documentation. 

Here is the job on Travis, I am really surprised. 
https://travis-ci.org/python/cpython/jobs/338426030

Is there an explanation?

@brettcannon ?

**Comment by matrixise** [comment]
Here is my test:

```bash
#!/usr/bin/env bash

files_changed=$(git diff --name-only bpo-1100942) 

echo $(git diff --name-only bpo-1100942 | grep -vE '(\.rst$)|(^Doc)|(^Misc)')
has_code=$(git diff --name-only bpo-1100942 | grep -qvE '(\.rst$)|(^Doc)|(^Misc)')

if ! $has_code
then
    echo "HasCode: Only docs updated"
else
    echo "HasCode: We can update"
fi

if ! echo $files_changed | grep -qvE '(\.rst$)|(^Doc)|(^Misc)'
then
    echo "FilesChanged: Only docs updated"
else
    echo "FilesChanged: We can update"                                                        
fi
```

and the output:
```
Lib/_strptime.py Lib/datetime.py Lib/test/datetimetester.py Modules/_datetimemodule.c
HasCode: We can update
FilesChanged: Only docs updated
```

When I execute the code of Travis, I have the result, `Only docs updated` but when I execute the `git diff` with the `grep` command, I have the right result.

**Comment by matrixise** [comment]
@brettcannon I have changed the condition with a flat condition, without any variable and the worker of Travis runs the tests

Here is my PR for review https://github.com/python/cpython/pull/5580/files 

my 2cents...

**Comment by berkerpeksag** [comment]
https://github.com/python/cpython/commit/b2ec3615c81ca4f3c938245842a45956da8d5acb (see https://github.com/python/core-workflow/issues/14#issuecomment-323270286 for details) might be the culprit. @ammaraskar do you have some time to investigate this?

**Comment by ammaraskar** [comment]
Oh this is most likely just a quoting issue around the variable, trying changing the line to:

`if ! echo "$files_changed" | grep -qvE '(\.rst$)|(^Doc)|(^Misc)'`

instead of

`if ! echo $files_changed | grep -qvE '(\.rst$)|(^Doc)|(^Misc)'`

**Comment by matrixise** [comment]
I have created this issue https://bugs.python.org/issue32802 and the associated PR https://github.com/python/cpython/pull/5589 . This PR can be back ported to 3.6 & 3.7

**Comment by Mariatta** [comment]
Thanks @matrixise! Good catch and thanks for fixing.
I've merged that PR and now waiting for the backports to be finished.

I wonder if other open PRs should be rebased to include the change in https://github.com/python/cpython/pull/5589?

**Comment by ammaraskar** [comment]
>I wonder if other open PRs should be rebased to include the change in python/cpython#5589?

A rebase won't be required, travis pulls in latest changes and applies the changes to the latest codebase (which should include the new travis.yml). A rebuild should do.

Someone who has administrator access over the python travis should be [able to trigger a rebuild](http://dearkumar.com/trigger-a-travis-ci-rebuild/). From a quick look it would be every RP after this one: https://github.com/python/cpython/pull/5449. Another view on travis that should help is this: https://travis-ci.org/python/cpython/pull_requests

Of course PRs that change only documentation don't need a rebuild, it should also be able to see if the full build went through by the time taken.

**Comment by berkerpeksag** [comment]
I think we close this now. Thank you everyone!
