### ISSUE TITLE
GH-5550 was linked to bpo-12345

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/core-workflow#223]
The bot added links to https://github.com/python/cpython/pull/5550 and its backports in unrelated [bpo-12345](https://bugs.python.org/issue12345). But I haven't found references to bpo-12345 neither in the PR comments, no in corresponding commit (5bb9692575f10f4a7c7f1c2c0c70956baf6d5c23).

**Comment by Mariatta** [comment]
Sorry, I've caused this issue.
In https://github.com/python/cpython/pull/5841/files I modified the PR template, and referencing bpo-12345 as a comment inside the pull request. If the comment is not deleted, the bpo webhook picks that up and the links the PR to bpo-12345.
I'll work on modifying the PR template.

**Comment by Mariatta** [comment]
I changed the PR template to reference bpo-123 (doesn't exist). Does that sound ok?

**Comment by brettcannon** [comment]
I say just have the comment reference `bpo-NNNN` and completely avoid the potential issue.

**Comment by Mariatta** [comment]
Thanks, I've removed the sentence that says bpo-123.
