### ISSUE TITLE
Double link to the same PR

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/core-workflow#224]
In [bpo-32856](https://bugs.python.org/issue32856) you can see that the bot created two links to the same PR https://github.com/python/cpython/pull/5695. I suppose this happened because I fixed a typo in the title just after creating the PR. But I wondering if there is a race condition which can cause more several errors.

**Comment by terryjreedy** [comment]
This also happened, within the last month I believe, with one of Cheryl Sabella's PRs for IDLE.  I unlinked one of the two and do not remember the issue.

**Comment by Mariatta** [comment]
The links inside bugs.python.org are not handled by bedevere, I think they're handled by bugs.python.org/pull_request webhook.
I don't know who maintains that.

**Comment by brettcannon** [comment]
http://psf.upfronthosting.co.za/roundup/meta/ would be the best place to report any issues with the linking on the bugs.python.org side. @ezio-melotti and @soltysh are probably the best people to look into it.

**Comment by Mariatta** [comment]
Since this issue is for bugs.python.org, I've opened https://github.com/python/bugs.python.org/issues/12.
