### ISSUE TITLE
Bot for Github labels

### ISSUE THREAD

**Issue by csabella** [python/core-workflow#239]
Currently, triagers aren't able to add labels to Github issues.  Zulip has a bot that allows for others to add labels, self-assign, etc.  I think this would be helpful to the CPython workflow, with the proper guidance and documentation.

'''
zulipbot's purpose is to work around various limitations in GitHub’s binary permissions and notifications systems to create a better workflow for our contributors. It allows anyone to perform issue triage (self-assigning and labeling issues), not just the core contributors trusted with full write access to the repository (which is the only model GitHub supports). Additionally, zulipbot monitors the activity of issues and pull requests, notifying contributors about new merge conflicts, continuous integration build results, inactivity, and more.
'''

**Comment by webknjaz** [comment]
Here's some ideas on bot commands https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md

**Comment by hugovk** [comment]
> Currently, triagers aren't able to add labels to Github issues.

I guess something changed in the past four years, I'm a triager and am able to add and remove labels here:

![image](https://user-images.githubusercontent.com/1324225/148687686-f8f7914b-996e-438c-bd25-19bd2a79529a.png)

Shall we close this?

**Comment by Mariatta** [comment]
This was raised before GitHub has the triaging feature, and we only have triagers on bpo. So yes this is not relevant anymore.
