### ISSUE TITLE
[cherry-picker] Document config options

### ISSUE THREAD

**Issue by webknjaz** [python/core-workflow#249]
Now that this tool supports working with other repos I wanted to check how can I use it in other project.

It took me a while to realize that `check_sha` should contain very fist commit in a repo's main branch. So I suggest documenting the config usage somewhere in README.

**Comment by Mariatta** [comment]
It is documented under "Available config options [here](https://github.com/python/core-workflow/tree/master/cherry_picker#options)?

**Comment by webknjaz** [comment]
Oh, I think I missed that, thanks. But still I'm not sure what is the purpose of it.

**Comment by Mariatta** [comment]
Just a way to ensure that we are operating on the right repo, before even starting to do `git fetch`, `checkout`, etc.
It can be any commit hash in your repo. We picked the first ever commit to CPython, we know it won't be amended or dropped ever.

**Comment by Mariatta** [comment]
I'm closing your issue since it's been documented.
