### ISSUE TITLE
Feedback on trying to adopt cherry-picker within @ansible/ansible

### ISSUE THREAD

**Issue by webknjaz** [python/core-workflow#263]
Hi @Mariatta,

So as other people started trying out `cherry_picker`-based flow, some failures to use it happened:
* It seems like there's not enough terminal output to completely understand when something goes wrong
* Failed branches disappear without explanation
* It looks like it pushes into wrong branch, but there's not enough verbosity to verify this.

Ref: ansible/ansible#41403
cc: @abadger

**Comment by Mariatta** [comment]
I think all of these have been resolved in the 1.2.1 release, right?

**Comment by webknjaz** [comment]
Yes, #277 will be addressed separately.
