### ISSUE TITLE
Merge commit messages

### ISSUE THREAD

**Issue by zware** [python/core-workflow#27]
Should we have some guidance on what the commit message should be for our squash merges?  The default is something like:

```
bpo-12345: PR Title (#PRNumber)

* bpo-12345: Commit message from first commit on the PR

* Commit message from second commit

* Commit message from a cleanup commit
```

Should we explicitly clean up the message, specifically by removing unnecessary cleanup commit messages and manually merging relevant parts of remaining commit messages?

**Comment by methane** [comment]
>
>
> Should we explicitly clean up the message, specifically by removing
> unnecessary cleanup commit messages and manually merging relevant parts of
> remaining commit messages?
>
>
​+1 for clean commit message.​

**Comment by berkerpeksag** [comment]
I always cleanup the message so +1 from me.

**Comment by brettcannon** [comment]
Always clean up.

There's also the question of whether the PR # should be left on as a suffix or not.

**Comment by zware** [comment]
> There's also the question of whether the PR # should be left on as a suffix or not.

I think it's somewhat nice to have an easy link to the PR, but perhaps we should change it from "#27" to "GH-27".  I have implemented a linkifier in our buildbot config that handles linkifying 'bpo-12345' to bpo and '#27' to GitHub (though it needs some enhancement).

**Comment by brettcannon** [comment]
I think keeping the suffix but asking people to rewrite it to e.g. GH-27 makes sense.

**Comment by Mariatta** [comment]
There's already some write up about commit message here:
https://docs.python.org/devguide/gitbootcamp.html#accepting-and-merging-a-pull-request

So I'm closing this :)
