### ISSUE TITLE
Teach cherry_picker to forwardport to master

### ISSUE THREAD

**Issue by andresdelfino** [python/core-workflow#270]
In #7765 ,  I opened a PR for 3.6 that was intended for master. After it was committed, I had to forwardport it to master.

When trying to do that, cherry_picker throw an error because it doesn't expect branch names without the X.Y format.

I ended up editing the script for this particular PR.

I know this isn't usual, but if deemed useful, I can take the task and make a PR.

**Comment by Mariatta** [comment]
Thanks, but I'm -1 on this idea. It is not an official CPython's workflow.

cherry_picker is convenience tool, and I don't think we should make forward porting too convenient.
(core devs going to need to be more careful next time 🙂).

I think we will focus on preventative measures, as discussed in https://github.com/python/core-workflow/issues/211 and https://github.com/python/bedevere/issues/111.

It could also be ported manually the old fashioned way, using `git cherry-pick`

```
git fetch upstream
git checkout -b port-pr-x-to-master upstream/x.y
git cherry-pick -x commithash
git push origin port-pr-x-to-master
...
```
