### ISSUE TITLE
[cherry-picker][blurb] License metadata broken

### ISSUE THREAD

**Issue by webknjaz** [python/core-workflow#273]
It looks like flit doesn't add sufficient metadata to dists, causing badges in README show empty string:
https://img.shields.io/pypi/l/cherry-picker.svg and https://img.shields.io/pypi/l/blurb.svg (non-working)
vs https://img.shields.io/pypi/l/cherrypy.svg (working).
I didn't check why this is happening though.

**Comment by Mariatta** [comment]
I noticed it's been broken for a while. I couldn't figure out the problem.
So is this a bug with flit or with shields.io?
The license info showing up properly in pypi.org.
We could also remove the badge...

**Comment by Mariatta** [comment]
License badge seems working now. 
![screenshot_20180911-070516 2](https://user-images.githubusercontent.com/5844587/45365337-262a6c80-b591-11e8-94a3-13fa6f9ed4f4.png)
