### ISSUE TITLE
Add 'skip backport' label to skip the backport source check.

### ISSUE THREAD

**Issue by terryjreedy** [python/core-workflow#278]
For #211, we added another ignorable check to Bedevere - for the master GH-NNNN number for non-master PRs.  Following the precedent of 'skip issue' and 'skip news' for other ignorable checks, add 'skip backport' (or 'skip GH-NNNN'?), with the same black blob, to skip the backport source # check.

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/core-workflow/issues/72 (Add a status check for reverted commits), https://github.com/python/core-workflow/issues/268 ([cherry-picker] [idea 💡] Extend backport sources), https://github.com/python/core-workflow/issues/267 (Automatically apply "needs backport to " labels.), https://github.com/python/devguide/issues/126 (Document backport and cherry-pick labels), and https://github.com/python/core-workflow/issues/211 (Bot to check if PR is not against the master branch, and it is not a backport PR).

**Comment by brettcannon** [comment]
@terryjreedy that's not true anymore as of [this commit](https://github.com/python/bedevere/pull/125). Now it only checks that you specified the branch name.
