### ISSUE TITLE
Add links back to bugs.python.org

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#28]
When the `bpo-\d+` pattern is picked up in a comment we should rewrite it to be linked to bugs.python.org appropriately. And if the link is detected in the title then a link should be added as a comment on the PR.

**Comment by soltysh** [comment]
Sign me up for this :)

**Comment by brettcannon** [comment]
And FYI we have a PSF account on Heroku so I would just write any bot to be hosted there to make writing this easier. (I also wonder if there isn't a bot somewhere that does this already? Quite possibly not but a quick Google search wouldn't hurt.)

**Comment by soltysh** [comment]
Roger that.

**Comment by jaraco** [comment]
Is there currently any art on which this effort could be based or does it need to be engineered from scratch?

**Comment by jaraco** [comment]
Until we have a service that can re-write the source, I've developed this [greasemonkey](http://www.greasespot.net/) script that will inject links:

```
// ==UserScript==
// @name Link bugs.python.org
// @include https://github.com/python/*
// @require https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js
// @grant none
// ==/UserScript==

$(".comment-body").html(
    function () {
       return $(this).html().replace(/(bpo-(\d+))/, '<a href="https://bugs.python.org/issue$2">$1</a>');
    }
);
```

**Comment by brettcannon** [comment]
@jaraco it doesn't need to be from scratch, it just needs to be easily deployed and maintained.

I should also mention that there's a possibility of making this a status check where the "Details" link would point to the issue itself (it's an idea I have in the back of my head that I'm still thinking through).

**Comment by ezio-melotti** [comment]
FTR @berkerpeksag wrote https://github.com/berkerpeksag/cpython-bpo-linkify

**Comment by brettcannon** [comment]
Bedevere is now doing this indirectly through a status check for issue numbers.
