### ISSUE TITLE
cherry_picker doesn't support forward-porting to master

### ISSUE THREAD

**Issue by larryhastings** [python/core-workflow#289]
` % cherry_picker <hash> master` caused cascading exceptions:

> Traceback (most recent call last):
>   File "/home/larry/lib/python3.7/site-packages/cherry_picker/cherry_picker.py", line 463, in version_from_branch
>     return tuple(map(int, re.match(r'^.*(?P<version>\d+(\.\d+)+).*$', branch).groupdict()['version'].split('.')))
> AttributeError: 'NoneType' object has no attribute 'groupdict'
>
> The above exception was the direct cause of the following exception:
>
> Traceback (most recent call last):
>   File "/home/larry/bin/cherry_picker", line 11, in <module>
>     sys.exit(cherry_pick_cli())
>   File "/home/larry/lib/python3.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/larry/lib/python3.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/larry/lib/python3.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/larry/lib/python3.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/larry/lib/python3.7/site-packages/cherry_picker/cherry_picker.py", line 412, in cherry_pick_cli
>     cherry_picker.backport()
>   File "/home/larry/lib/python3.7/site-packages/cherry_picker/cherry_picker.py", line 269, in backport
>     for maint_branch in self.sorted_branches:
>   File "/home/larry/lib/python3.7/site-packages/cherry_picker/cherry_picker.py", line 81, in sorted_branches
>     key=version_from_branch)
>   File "/home/larry/lib/python3.7/site-packages/cherry_picker/cherry_picker.py", line 465, in version_from_branch
>     raise ValueError(f'Branch {branch} seems to not have a version in its name.') from attr_err
> ValueError: Branch master seems to not have a version in its name.

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/core-workflow/issues/149 (`pip install` does not work for cherry_picker), https://github.com/python/core-workflow/issues/270 (Teach cherry_picker to forwardport to master), https://github.com/python/core-workflow/issues/140 (Move cherry_picker over to flit), https://github.com/python/core-workflow/issues/162 (blurb does not support command line options in EDITOR/GIT_EDITOR), and https://github.com/python/devguide/issues/3 (Add Travis support).

**Comment by larryhastings** [comment]
GitMate.io is right, this is a duplicate of #270.
