### ISSUE TITLE
Links to www.bugs.python.org

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/core-workflow#292]
Links created automatically for mentions of `bpo-XXXX` refer to [www.bugs.python.org](https://www.bugs.python.org/) instead of [bugs.python.org](https://bugs.python.org/).

See for example https://github.com/python/cpython/pull/9721.

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/core-workflow/issues/28 (Add links back to bugs.python.org), https://github.com/python/devguide/issues/4 (Migrate over issues from bugs.python.org), https://github.com/python/devguide/issues/16 (Remove mentions of hg.python.org), https://github.com/python/devguide/issues/231 (Update links to point to https://devguide.python.org/), and https://github.com/python/core-workflow/issues/15 (Shut down Rietveld instance on bugs.python.org).
