### ISSUE TITLE
Add Windows CI for cherry-picker

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#296]
I think it will be good idea to add CI and test cherry-picker in windows environment.

But I don't know how to do that myself.

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/core-workflow/issues/113 (Questions about cherry-picker from Windows never-venv user), https://github.com/python/core-workflow/issues/88 (Make `-h` work for cherry-picker), https://github.com/python/core-workflow/issues/44 (Add the branch number to cherry pick commits?), https://github.com/python/core-workflow/issues/286 (Further automation for releasing cherry-picker.py), and https://github.com/python/devguide/issues/292 (Add linkcheck to CI).

**Comment by webknjaz** [comment]
AppVeyor is a classical solution to this.
And now Travis CI has beta support of Windows jobs but I believe it's not that straightforward in usage.

**Comment by encukou** [comment]
See https://github.com/python/core-workflow/pull/311 for a Travis CI setup.

**Comment by Mariatta** [comment]
Closed in #311
