### ISSUE TITLE
[blurb] f-string simulation does not work with closures.

### ISSUE THREAD

**Issue by JulienPalard** [python/core-workflow#299]
In the `throw` function, the `raise BlurbError(f("Error in {filename}:{line_number}:\n{s}"))` can't find the filename variable leading to:

```
Traceback (most recent call last):
  File "/home/mdk/clones/core-workflow/blurb/blurb.py", line 1691, in <module>
    main()
  File "/home/mdk/clones/core-workflow/blurb/blurb.py", line 1651, in main
    sys.exit(fn(*filtered_args, **kwargs))
  File "/home/mdk/clones/core-workflow/blurb/blurb.py", line 954, in add
    blurb.load(tmp_path)
  File "/home/mdk/clones/core-workflow/blurb/blurb.py", line 553, in load
    self.parse(text, metadata=metadata, filename=filename)
  File "/home/mdk/clones/core-workflow/blurb/blurb.py", line 543, in parse
    finish_entry()
  File "/home/mdk/clones/core-workflow/blurb/blurb.py", line 495, in finish_entry
    throw("Blurb 'body' text must not be empty!")
  File "/home/mdk/clones/core-workflow/blurb/blurb.py", line 486, in throw
    raise BlurbError(f("Error in {filename}:{line_number}:\n{s}"))
  File "/home/mdk/clones/core-workflow/blurb/blurb.py", line 138, in f
    return s.format_map(d)
KeyError: 'filename'
```

To reproduce it: invoke blurb, empty the buffer, and close the editor.

I don't think we should try to fix `def f`, maybe simple add `nonlocal filename` and `nonlocal file_number` so they become visible in the function locals.

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/core-workflow/issues/154 (blurb refuse to work without setting EDITOR env), https://github.com/python/core-workflow/issues/149 (`pip install` does not work for cherry_picker), https://github.com/python/devguide/issues/324 (Building docs without make doesn't seem to work), https://github.com/python/core-workflow/issues/162 (blurb does not support command line options in EDITOR/GIT_EDITOR), and https://github.com/python/core-workflow/issues/159 (Make blurb working in Python 3.5.).

**Comment by jaraco** [comment]
I ran into this issue also when implementing a similar function and I ended up creating [namespace_format](https://github.com/jaraco/jaraco.text/blob/258e3af8c62d24bf7637c334f47a673370bae975/jaraco/text.py#L159-L173) to format a string from the locals and globals. But maybe blurb should just use [future-fstrings](https://pypi.org/project/future-fstrings) or just drop support for Python 3.5 (which is EOL anyway).

**Comment by JulienPalard** [comment]
Dropping Python 3.5 support looks the right way to me too.

**Comment by Mariatta** [comment]
I'm in favor of dropping 3.5 support. (https://github.com/python/core-workflow/issues/283)
