### ISSUE TITLE
Link to developer guide in CPython repo description

### ISSUE THREAD

**Issue by ncoghlan** [python/core-workflow#30]
https://github.com/python/cpython/pull/118 adds a link to the Developer Guide to the top of the README.

It would be useful if the repo description linked to the developer guide in addition to linking to the main python.org website.

**Comment by brettcannon** [comment]
There's no good way to provide two links in the repo title as that link is a specific, separate field from the description.

**Comment by ncoghlan** [comment]
In that case, I'll rephrase the proposal to suggest linking to the developer guide *instead* of linking to python.org :)

**Comment by brettcannon** [comment]
The question becomes what do people use that link for? I personally use it to validate that I'm looking at the project that's behind a certain website or to get to the homepage quickly, not to get to developer documentation. I always assume the README and/or CONTRIBUTING files will have the dev doc links.

**Comment by Mariatta** [comment]
:thinking:  Maybe instead of www.python.org, it should be pointing to docs.python.org?
It is part of cpython repo

**Comment by brettcannon** [comment]
I think we are all way over-thinking a single link 😉 . Maybe it would be better to just have 3 quick links listed at the top of the README: www.python.org, docs.python.org, and the devguide.

**Comment by Mariatta** [comment]
Sounds good to me :) 
Please see my proposed PR at https://github.com/python/cpython/pull/283

**Comment by ncoghlan** [comment]
@Mariatta's addition looks good to me, and should be useful to folks looking at the README offline as well.

As far as the project level link goes, I think the reason it bugs me is just because our top level directory and file listing is long enough to push the start of the README off the bottom of the page. And yes, I'm almost certainly overthinking it :)

**Comment by brettcannon** [comment]
Since Mariatta's proposed PR was merged I'm closing this.
