### ISSUE TITLE
The cpython github merge webhook to bugs.python.org is broken

### ISSUE THREAD

**Issue by ned-deily** [python/core-workflow#301]
The github webhook that sends cpython merge updates to individual issues on bpo is failing (https://bugs.python.org/pull_request).  I'm guessing it may have something to do with the recent upgrade and move of bpo to a different system.  I don't have time to track it down myself at the moment but this is a pretty critical item as we are losing documentation in bpo of pushed merges.

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/devguide/issues/4 (Migrate over issues from bugs.python.org), https://github.com/python/core-workflow/issues/28 (Add links back to bugs.python.org), https://github.com/python/core-workflow/issues/15 (Shut down Rietveld instance on bugs.python.org), https://github.com/python/core-workflow/issues/292 (Links to www.bugs.python.org), and https://github.com/python/devguide/issues/79 (https://docs.python.org/devguide/ is broken?).

**Comment by Mariatta** [comment]
Webhook are returning 400 error from bpo.
![screenshot_20181223-143837](https://user-images.githubusercontent.com/5844587/50388069-a5672a80-06c0-11e9-88f3-30f3bfd802b2.png)

**Comment by Mariatta** [comment]
I don't have access to bpo server log. I don't know who would be able to look into this.

**Comment by ewdurbin** [comment]
Fairly clear error message:

```ERROR:root:Missing SECRET_KEY environment variable set!```

Appears configuration is the only non ini file based config in the roundup instance, and was missed.

I'm working to resolve it now and will replay all backlogged web hooks after its restored.

**Comment by ewdurbin** [comment]
https://bitbucket.org/python/roundup/commits/59d6d4284aea7df30344758fe391478a47609c2e resolves, it's deployed and hooks are flowing. I'm trying to determine how to mass replay the hooks now.

**Comment by ewdurbin** [comment]
I've submitted a support request to GitHub... it appears our only option for redelivery of the failed hooks is to click the buttons in the GitHub UI (or script something to do so)... but not too fast! if you click them too fast you'll get rate limited :)

**Comment by ned-deily** [comment]
Thanks for getting it working again, @ewdurbin!  But, yikes, I hope you don't have to push every button!

**Comment by ewdurbin** [comment]
Welp, clicked and tapped and it’s done. 😅

Gonna leave this issue open until we confirm things are flowing/behaving as expected.

**Comment by ewdurbin** [comment]
Got confirmation from GitHub that there is no automated way to mass redeliver failed hooks.

**Comment by ewdurbin** [comment]
Okay, looks like we had some kerfuffle in delivery over the past few days.

To address this I've refactored each roundup instance on the new host to run its own gunicorn stack and gracefully reload to maintain availability: https://github.com/python/psf-salt/commit/ebacc0aea3e1b1adbc8ddb800920ebb8b27cf74f

Will continue to watch for a few days :)

**Comment by ned-deily** [comment]
Thanks, @ewdurbin!  I think the merge messages are now showing up as expected.  But there is still at least one remaining transition issue: the multiple identical PR links showing up in b.p.o issues as referenced [above](https://github.com/python/bugs.python.org/issues/12).
