### ISSUE TITLE
Setup cronjobs on Travis CI to run tests

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#306]
I think it would be great to run our test suites regularly instead of only when there's a PR.
For CPython we receive PRs daily, so perhaps there's no issue there. But our bots aren't as high traffic, and depend on various libraries.

Recently in bedevere we discovered issues with uritemplate, aiohttp (and probably asyncio) in Python 3.8. I also realized we haven't been running the tests against the latest Python versions.

- [x] daily cron jobs for miss-islington
- [x] daily cron jobs for bedevere
- [x] daily cron jobs for the-knights-who-say-ni
- [x] daily cron jobs for blurb_it
- [x] daily cron jobs for core-workflow (cherry_picker + blurb)

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/core-workflow/issues/1 (Hook up Travis for PR/CI testing), https://github.com/python/core-workflow/issues/61 (Set up Travis CI), https://github.com/python/core-workflow/issues/54 (Travis tests are broken), https://github.com/python/core-workflow/issues/91 (Require macOS testing for Travis), and https://github.com/python/core-workflow/issues/147 (Run blurb as part of Travis).

**Comment by Mariatta** [comment]
Added "help wanted" label as I'm not sure if I'll have the ability to configure the cron jobs in travis CI :)
Maybe I do? I haven't tried.

**Comment by encukou** [comment]
> For CPython we receive PRs daily, so perhaps there's no issue there. But our bots aren't as high traffic, and depend on various libraries.

Travic CI has a "Do not run if there has been a build in the last 24h" setting for exactly this case.

> Added "help wanted" label as I'm not sure if I'll have the ability to configure the cron jobs in travis CI :)
Maybe I do? I haven't tried.

I have that ability, and I'm just a random core dev, so you should have it as well :)
It's at the bottom of settings page, e.g. [here for blurb_it](https://travis-ci.org/python/blurb_it/settings).
I saw the label, so I went ahead and configured the ones that didn't have a cron job yet with the above setting.

**Comment by Mariatta** [comment]
😃 Great! Thanks for handling this quickly, @encukou !
