### ISSUE TITLE
The PR is blocked by the issue-number check

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/core-workflow#321]
The bedevere bot hanged on the issue-number check and blocks merging https://github.com/python/cpython/pull/12712.

**Comment by tirkarthi** [comment]
There are some errors logged at https://github.com/python/core-workflow/issues/258#issuecomment-480599752 for bedevere . Almost all PRs to master and backport PRs to maintenance branches today have this check having no return response.

miss-islington issue also has a recent error : https://github.com/python/core-workflow/issues/257#issuecomment-480584122

**Comment by serhiy-storchaka** [comment]
Thanks @Mariatta!
