### ISSUE TITLE
Potential security issue with ":robot: automerge"

### ISSUE THREAD

**Issue by Carreau** [python/core-workflow#325]
Opening following private back and forth with @Mariatta 

Imagine the following sequence of event: 
- Evil User: Send Typo Pull-request. 
- CI Starts
- Core-dev: approve and set ":robot: automerge" label
- Evil user push new commits with backdoor. 
- CI Re-Starts
- CI Pass
- Miss-islington merges with backdoor.

One of the solution is to look at the push event; and remove the label; 
You can also activate the "dismiss review on commits push" and have Miss islington merge only if there are positive reviews.

**Comment by Mariatta** [comment]
Thanks for the report, @Carreau. I think we need to fix this.

When a PR has been approved, it would have an `awaiting merge` label. So one way to deal with this  is to remove the `awaiting merge` label and move it back to `awaiting core review` state. But I think it will make sense to also dismiss review, and request a re-review.

**Comment by lysnikolaou** [comment]
I think it makes sense to dismiss the review altogether and apply the `awaiting review` label again.

**Comment by Carreau** [comment]
Or "awaiting changes review"; in the other hand, the push can just cleanup/rebase, so their might not be much to re-review.

Could you push a label "automerged-cancel"; it's really easy to spot and should be pretty rare.

**Comment by Mariatta** [comment]
`awaiting change review` sounds good too. I kinda don't want to create yet another label just for this situation.
I'm thinking perhaps the `awaiting change review` should be done anyway when there is a new push after last review, (even for the ones without ":robot: automerge" label).

**Comment by lysnikolaou** [comment]
@Mariatta I could work on updating `bedevere` to apply the `awaiting change review` label, as soon as a new commit is pushed, if nobody else already works on this. Would that be okay in your opinion?

**Comment by Mariatta** [comment]
I've created PR to address this.
If there is new commit pushed to already approved PR, it will be moved back to `awaiting core review` stage. https://github.com/python/bedevere/pull/220

**Comment by Mariatta** [comment]
I've deployed the change where approved PRs will be moved back to the `awaiting core review` stage if it has a new commit pushed. If there is any issues with it please open a ticket in bedevere repo.

Thanks.
