### ISSUE TITLE
BPO notifications should ignore PR branches

### ISSUE THREAD

**Issue by ncoghlan** [python/core-workflow#33]
If you use the online merge conflict resolution on a PR branch that was created directly in the online editor, GitHub will merge the target branch into the PR branch.

This currrently retriggers BPO notifications for all the commits merged into the PR branch.

Limiting notifications to master and X.Y branches should avoid the problem.

**Comment by ezio-melotti** [comment]
I created http://psf.upfronthosting.co.za/roundup/meta/issue614 in case we have to fix this on the Roundup side, but if it can be fixed on the GitHub side even better.

**Comment by ncoghlan** [comment]
Looking at the webhook settings on another repo, I don't see any way to set up per-branch filtering for events, so closing this in favour of the tracker issue @ezio-melotti created.

**Comment by ezio-melotti** [comment]
Thanks to Anish and @soltysh this should now be fixed.  Let me know if there are any issues.
