### ISSUE TITLE
We need a "Needs backport to 3.8" label

### ISSUE THREAD

**Issue by ambv** [python/core-workflow#331]
Hello Core Workflow,
as the title implies, we need the label + the automation it provides. The "3.8" branch is already there and "master" is already marked as "3.9a0".

**Comment by Mariatta** [comment]
I've created the `needs backport to 3.8` label.

Perhaps next time we can have a bot that automatically create the label when we have the 3.9 branch.

**Comment by vstinner** [comment]
> I've created the needs backport to 3.8 label.

Thanks.
