### ISSUE TITLE
CLA signed just became CLA not signed for GitHub user dcarlier-afilias

### ISSUE THREAD

**Issue by vstinner** [python/core-workflow#333]
Copy of my https://github.com/python/cpython/pull/13835#issuecomment-499044674 comments.

> @the-knights-who-say-ni the-knights-who-say-ni added the CLA not signed label just now

I don't get it. I found https://bugs.python.org/user27678 user in the bugs.python.org database which has the CLA signed and the GitHub username "dcarlier-afilias".

Note: There is also https://bugs.python.org/user27725 user which has no GitHub nickname filled but the CLA signed.

@Mariatta @csabella: Any idea what is happening with the CLA?

> @the-knights-who-say-ni the-knights-who-say-ni added CLA not signed and removed CLA signed CLA not signed labels an hour ago

That's even more weird. The CLA **was** signed. The same author also wrote PR #13654 and I'm quite sure that the CLA was signed when I merged the PR. But then the bot removed the "CLA signed" label to add "CLA not signed"!?

**Comment by Mariatta** [comment]
If you look not the commits, one of the commit was made by devnexen, who has not signed cla
