### ISSUE TITLE
Add people into the "Python Triagers" team

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#335]
Let's start with a small group of active and experienced triagers.
We'll update devguide as we go along and resolve any issues before we add even more people.

**Comment by Mariatta** [comment]
Related discussion thread: https://discuss.python.org/t/proposal-create-bug-triage-team-on-github/992

Current list of triagers in bpo: https://bugs.python.org/user?username=&realname=&roles=Developer&%40action=search&iscommitter=0

My proposal is to start with the following:

maxking
ammaraskar
CuriousLearner
mariocj89
tirkarthi
nanjekyejoannah

Other triagers are welcome to request themselves be added to the triagers team on GitHub.

**Comment by nanjekyejoannah** [comment]
@Mariatta, Since am mentioned here, I decided to give consent by saying am happy to help in these triage procedures on Github.

**Comment by hugovk** [comment]
This issue has been moved to "Done" on its project board so closing to match.
