### ISSUE TITLE
automatic add user to nosy list if not exist in bpo after PR submitted

### ISSUE THREAD

**Issue by aldwinaldwin** [python/core-workflow#341]
User is not in nosy list on bugs.python.org after submitting a PR. User has to add himself to nosy list manually. This for small documentation fixes, a PR is made very quickly and user forgets to added self to the nosy list.

**Comment by Mariatta** [comment]
Thank you, I agree it is a great idea. This needs to be done in bpo.

Duplicate of https://github.com/python/bedevere/issues/98
Duplicate of https://github.com/python/bugs.python.org/issues/8

**Comment by Mariatta** [comment]
Duplicate of python/bedevere#98

**Comment by Mariatta** [comment]
Duplicate of python/bugs.python.org#8

**Comment by aldwinaldwin** [comment]
Thank you. I checked the bedevere issues but not the Closed ones. :)
