### ISSUE TITLE
Use GitHub Actions for CI

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#347]
GitHub Actions now has built-in CI/CD https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

Would be good to look into using that for Python. We have access to the beta GitHub Actions.

**Comment by epicfaace** [comment]
Why would it be better to move to Github Actions from the existing process in Azure Pipelines?

**Comment by terryjreedy** [comment]
We *might* have better control of the test environment.  For instance, Azure Mac runs our test suite with the ancient decade-old Apple system tcl/tk 8.5.9, while we release with 8.6.9, which has fewer and perhaps different bugs.  Somewhat separate, it skips tkinter and IDLE tests that require the GUI resource.  (This latter is true for nearly all *nix-based test machines.  New Deily knows the most about this for Mac.)

Perhaps Github Actions CI make it possible/easier to rerun particular test runs, like Travis does.

We cannot know if Actions is 'better' until someone 'looks into' Actions, which is what Marietta suggested.  Anyway, the above are 3 things that I would like such an investigation to consider.

**Comment by ammaraskar** [comment]
So here's a cool usage of Github Actions that could be useful for the CPython worflow: https://github.com/ammaraskar/cpython/pull/14/files#diff-9af756ebedaea31ef549c4e24f2d9162R3

I whipped up a quick action to perform a Sphinx build, this lets us put warnings from the build straight into the diff. Really useful for if you're trying to make a quick change using the Github web editor and don't want to pour through all the Travis logs to figure out why it failed.

**Comment by zware** [comment]
@ammaraskar That looks *really* nice.

**Comment by hugovk** [comment]
Shall we close this now?

Travis CI has been replaced with GitHub Actions in https://github.com/python/cpython and most if not all the other https://github.com/python repos.

**Comment by brettcannon** [comment]
Yep, this is stale.
