### ISSUE TITLE
Question: Why is there no 'Backport to 3.5' label in CPython repo?

### ISSUE THREAD

**Issue by maxking** [python/core-workflow#352]
It looks like we don't have a label to automatically create backport PRs to 3.5 branch, even though it is still in security maintenance mode.

Not sure if this is the right place for the question, but since I didn't see anything in the devguide about this, I thought it is more of a workflow question.

**Comment by Mariatta** [comment]
This is appropriate place for question about the label. 

We used to have it, but deleted when the branch became security only, after this thread
https://mail.python.org/archives/list/python-committers@python.org/thread/BIKX3VZ4VDX2BXMGZ4AL447JKQ7BS45Y/
and no-one seems to complain afterwards.

There was similar discussion raised to remove the `needs backport to 3.6`. But this time, the release manager allows the label to remain, so it is still around.
https://discuss.python.org/t/remove-needs-backport-to-3-6-label/563/7

**Comment by aeros167** [comment]
That's a good question, I've been curious myself as to the reasoning behind it. Thanks for the links Mariatta. 

As a related question regarding the security branch backports, do they specifically require approval from the release managers or org admins in order to be merged?

If so, I personally don't think it's an issue to leave the labels around if we are still delivering security updates to that version. Either way though, I think we should aim to be consistent with regards to either removing all of the security-only branch labels or retaining them in the future if possible.

**Comment by terryjreedy** [comment]
"do [security branch backports] specifically require approval from the release managers?"
Generally yes, but the rule is sociological, not technical, and probably not absolute.  So I think it better that the label not be present.  But if Ned wants them for 3.6, and later 3.7, that is okay with me.  Maybe enough auto backports to 3.6 work that he finds the label useful, while that is less common for 3.5, or maybe Larry prefers to just do a manual backport in the first place.  There are time costs and mental energy costs either way and people differ in their tradeoffs.  People are not 'consistent'.

**Comment by maxking** [comment]
> specifically require approval from the release managers?
So, the security branches are also restricted and only RMs can merge PRs into those branches.

@terryjreedy what I am actually trying to understand is what is the workflow for 3.5 branch. Does Larry picks issues and backports them manually or do I just need to ping him on BPO or on the PR which needs to be backported? I am totally okay with doing either of those, just trying to figure out the best way. Maybe I should send him an email instead. 

Thanks @Mariatta for the links.

**Comment by terryjreedy** [comment]
The bpo should be marked as security -- but only if it really is such -- and Ned and Larry added as nosy.  Usually this would be done by a core developer (possibly you now) who is a least somewhat familiar with what qualifies.  (I somewhat lack that knowledge.)  And add a comment and request a review for possible backport on a specific PR.  Remember that core devs too can ask questions on core-mentorship.
