### ISSUE TITLE
Python Triage Team Application: Kyle Stanley

### ISSUE THREAD

**Issue by aeros167** [python/core-workflow#353]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @aeros167 |
| bpo username   | aeros167     |
| Additional info   | So far, I have reviewed 57 PRs and have 10 merged PRs for both cpython and devguide. Multiple of those have involved the creation of the guidelines for the Python Triage team. I am highly motivated in joining the team because I've not only enjoyed the process of reviewing PRs, I've also seen the need for reviewers. There are far more PRs submitted each day than there are core developers to adequately handle them and I would very much like to help with that issue. It is my goal to become an effective triager, for both improving the workflow and bettering the experience of PR authors.| |

**Comment by aeros167** [comment]
A few core developers that I've interacted with several times (who might have feedback on this):

/cc @willingc, @terryjreedy, @taleinat, @Mariatta, @brettcannon, @pitrou

**Comment by pitrou** [comment]
Sounds fine to me.

**Comment by Mariatta** [comment]
+1 @dstufft or @benjaminp will one of you be able to invite @aeros167 to @python/python-triage team?
I've already made @aeros167 a Developer in b.p.o

**Comment by taleinat** [comment]
+1

**Comment by benjaminp** [comment]
invited

**Comment by aeros167** [comment]
Thanks for the feedback everyone and for the invite. (:

**Comment by jdemeyer** [comment]
Congrats @aeros167

**Comment by aeros167** [comment]
Congrats to you as well @jdemeyer
