### ISSUE TITLE
Python Triage Team Application: Jeroen Demeyer

### ISSUE THREAD

**Issue by jdemeyer** [python/core-workflow#354]
# Request for Python Triage membership

- GitHub username: @jdemeyer
- bpo username: jdemeyer

## Additional info

- Authored 60 commits in cpython master.
- Oldest accepted cpython patch written in 2015.
- Reviewed 53 PRs on the cpython repo that I did not author.
- Opened 65 bpo issues.
- Commented on 64 bpo issues that I did not create.
- Co-author of accepted PEP 590.
- Well-known developer of SageMath and Cython.

## Core dev contacts

@encukou @methane @vstinner @scoder

**Comment by methane** [comment]
+1

**Comment by scoder** [comment]
+1

**Comment by Mariatta** [comment]
+1 @dstufft or @benjaminp will one of you be able to invite @aeros167 to @python/python-triage team?
I've already made @jdemeyer a Developer in b.p.o

**Comment by encukou** [comment]
+1, from me as well!

**Comment by brettcannon** [comment]
@Mariatta did you mean aeros167 or jdemeyer?

**Comment by Mariatta** [comment]
Well both. @aeros167's request is handled separately in #352 .

Edited my comment.

Thanks!

**Comment by benjaminp** [comment]
I invited jdemeyer.

**Comment by jdemeyer** [comment]
Thanks!

**Comment by vstinner** [comment]
> Request for Python Triage membership

What is the Python Triage group/team? Is it related to bugs.python.org or only GitHub?

**Comment by jdemeyer** [comment]
> Is it related to bugs.python.org or only GitHub?

Both. On GitHub, it is this team: https://github.com/orgs/python/teams/python-triage

**Comment by vstinner** [comment]
How are both lists synchronized? Manually?

**Comment by Mariatta** [comment]
The two lists are not synchronized. Read devguide for details and difference of Python triage team and Developer in bpo. https://devguide.python.org/triaging/#becoming-a-member-of-the-python-triage-team

**Comment by vstinner** [comment]
> Do note that the responsibilities of a Python triager is more elevated than a developer on bpo. For example, the Python triager has access to more repositories than just CPython. Triagers will be responsible to handle not just issues, but also pull requests, and even managing backports.

What does "handling pull requests" mean? Does it mean being allowed to merge a pull request? To add labels? To close a PR?

**Comment by Mariatta** [comment]
Responsibilities are described in previous section. https://devguide.python.org/triaging/#python-triage-team

**Comment by aeros167** [comment]
@vstinner 

> What does "handling pull requests" mean? Does it mean being allowed to merge a pull request? To add labels? To close a PR?

It means adding labels, helping with the initial review, and closing PRs. Python triagers can't merge PRs though. The primary purpose of the team is to help the core devs with the preliminary steps to help improve the workflow efficiency. In theory, this will allow the core devs to spend more time on the merging/final review step while the triage team handles the categorization and initial intake process.

**Comment by aeros167** [comment]
@Mariatta 
> Responsibilities are described in previous section. https://devguide.python.org/triaging/#python-triage-team

Not to go too off-topic from the initial questions, but it looks like a few of the permission for the role might be off (at least from what I could tell last night). Most notably, it looks like we might be able to add labels that we shouldn't (``auto-merge``, ``awaiting ...``) and are unable to edit PR titles. I'll create a new topic in Discuss to go over it in more detail, but I just wanted to bring it to your attention first.

**Comment by Mariatta** [comment]
> it looks like we might be able to add labels that we shouldn't (auto-merge, awaiting ...) 

`awaiting ...` labels are meant to be applied by bots. Core devs are able to add these labels too, but they should not.

`🤖automerge` can be added by triagers but miss-islington will automatically remove it.
