### ISSUE TITLE
Python Triage Team Application: Ammar Askar

### ISSUE THREAD

**Issue by ammaraskar** [python/core-workflow#355]
|     | Description |
| --- | -------------------------- |
| GitHub username   | @ammaraskar |
| bpo username   | ammar2     |
| Additional info   | Triager on bpo <br/> ~50 bugs triaged on bpo <br/> ~30 [merged prs](https://github.com/python/cpython/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3Aammaraskar)| 

core devs who can likely give feedback: @berkerpeksag @giampaolo @zware and @Mariatta

**Comment by giampaolo** [comment]
Ammar contributed getloadavg() emulation on Windows for psutil:
https://github.com/giampaolo/psutil/issues/1484
The task was not straightforward as outlined here:
https://github.com/giampaolo/psutil/pull/1485#issuecomment-482521924
This is the only interaction I had with him so far but AFAICT he was very good in terms of communication and dealing with the code review. I personally see no issues in having him on board as a bug trigger.

**Comment by Mariatta** [comment]
Sounds good to me. I've seen reviews from @ammaraskar across various areas of CPython.

@dstufft or @benjaminp will one of you be able to invite @ammaraskar to @python/python-triage team?
Thanks.

**Comment by aeros167** [comment]
Congrats @ammaraskar!

**Comment by benjaminp** [comment]
invited

**Comment by berkerpeksag** [comment]
+1 from me. I've been working with Ammar on different projects in the Python organization and I think he is going to be a great addition to the triage team.

**Comment by Mariatta** [comment]
Thanks!

**Comment by ammaraskar** [comment]
Thanks everyone :)
