### ISSUE TITLE
Python Triage Team Application: Dong-hee Na

### ISSUE THREAD

**Issue by corona10** [python/core-workflow#357]
# Request for Python Triage membership

## GitHub username
@corona10

## bpo username 
corona10

## Additional info
- Authored [21 commits](https://github.com/python/cpython/commits?author=corona10) in cpython master.
- [36 PRs](https://github.com/python/cpython/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Acorona10+is%3Amerged+) were merged including backport patch.
- I have a strong passion for the Python runtime and the standard library. 
This can be demonstrated by the enthusiastic activities of the project. (e.g Google grumpy,  gpython, RustPython, pyston)
- I would like to join the Python Triage Team to resolve minor issues and to help new contributors to land well with activities including code reviews.
- I want to help Python interpreter projects based on other languages ​​through the Python Triage membership team. (Reflects the latest implementation)

**Comment by corona10** [comment]
@Mariatta 
Please be generously understanding what I've done with the new formatting because the existing templates are difficult to fill in additional information for me.

**Comment by nanjekyejoannah** [comment]
@corona10 , do you want to @ any relevant core devs for approval also?

**Comment by corona10** [comment]
@nanjekyejoannah Might be.. @vstinner can help me?
I have not discussed this matter directly with him.
So I think he might be embarrassed about being suddenly mentioned.

**Comment by nanjekyejoannah** [comment]
You can @ some other core devs also that have reviewed your PRs before may be ?

**Comment by corona10** [comment]
@nanjekyejoannah 
Core developers who work with more than 1 bpo work with : @vstinner @serhiy-storchaka @1st1 
Core developers who work at least 1 bpo work with: @vsajip  @methane  @rhettinger 

---------
Dear core developers,
Thank you for your patience with my sudden mention.
Over the last two years, I have contributed to CPython and other Python interpreters. I have not yet contributed to the core features of CPython, but I would like to contribute more through the Triage membership program. I also think this opportunity will help you understand CPython's decisions.

What I want to do with this program is:
-Find a good first bug for new contributors
- Well-landing help of new contributors through code review
- Improve my ability to become core developer
-  Helping runtime implementations of many recent alternative interpreters (by checking the latest implementation of CPython)


I would appreciate it if you give me feedback
I will accept any decision positively.

Thanks for reading. and I am looking forward to your positive review.

**Comment by aeros167** [comment]
> I would like to contribute more through the Triage membership program

> Well-landing help of new contributors through code review

I would highly recommend getting more involved with PR review in the Python repositories in the meantime. That's the primary task at the moment for the Python triage team. The additional permissions allow us to apply labels, but anyone can help with the review process. There's currently far more incoming PRs than there are people to review them, which is one of the main issues the triage team was created to help with solving.

**Comment by corona10** [comment]
@aeros167 

Thank you for the comment. I will leave code reviews as much as I can from today.
Thanks!

**Comment by vstinner** [comment]
@corona10 @Mariatta: I'm not comfortable to vote to give triagger permission if the candidate has no mentor to help him to handle these new responsibilities. Who would like to mentor @corona10 for 1 month? I will not be available for that in September.

**Comment by corona10** [comment]
@corona10 @Mariatta:
If any core developers can help me, it will be helpful for me.
For me, there was no chance to meet or get mentoring for core developers.
I will do my best

**Comment by vstinner** [comment]
+1 for me. Is it enough to add him to the bug triage team? Who can actually add him, @ewdurbin maybe?

> Who would like to mentor @corona10 for 1 month? I will not be available for that in September.

Ok, I'm now filling ridiculous of blocking this promotion. So I changed my mind and I would like to mentor @corona10 for his new responsibilities.

**Comment by aeros167** [comment]
> So I changed my mind and I would like to mentor @corona10 for his new responsibilities.

@vstinner I'm not a core developer, so I can't "officially" mentor, but I have built up some amount of experience with PR review. Feel to either msg me on discuss.python.org (preferred) or send me an email for any questions, and I'll do my best to help @corona10. This also applies to any other new triagers, I would be happy to assist in any way I can.

**Comment by aeros167** [comment]
> +1 for me. Is it enough to add him to the bug triage team? Who can actually add him, @ewdurbin maybe?

According to the guidelines we laid out, one core developer approval is enough to add them to the team. I believe any admin of the Python organization can send the invite, last time @benjaminp handled it though. I'm not sure if there's someone specific that usually handles organization team invites though.

**Comment by ewdurbin** [comment]
If everything is lined up and this is confirmed, I can send an invite. Is that what's desired?

**Comment by corona10** [comment]
@vstinner @aeros167 I will do my best to meet expectations Thank you

**Comment by vstinner** [comment]
@ewdurbin:
> If everything is lined up and this is confirmed, I can send an invite. Is that what's desired?

Yes, please. Do you want me to add the Developer role to his bugs.python.org account, or do you want to do it?

**Comment by ewdurbin** [comment]
Invite sent for GitHub team, Developer role on bpo applied.

**Comment by vstinner** [comment]
Congrats @corona10! I will be your mentor for one month ;-)

**Comment by corona10** [comment]
@vstinner 
Thank you. This is a great honor to me.
I will do my best to meet your expectations.
I 've now received the mail from you, I will follow your guide!

Thank you again!

**Comment by nanjekyejoannah** [comment]
congrats @corona10

**Comment by aeros167** [comment]
Congrats @corona10!

**Comment by corona10** [comment]
@aeros167 @nanjekyejoannah Thank you!
