### ISSUE TITLE
Making news entries optional for documentation-only changes

### ISSUE THREAD

**Issue by isidentical** [python/core-workflow#363]
# The short story

It would be nice if news entries can be optional by default in documentation-only changes. 

# Long version
Most of the documentation change cases, news entries aren't important. It would be nice to automatically skip news entry check on `[type-documentation]` labeled PRs.

**Comment by brettcannon** [comment]
"Most of the documentation change cases, news entries aren't important", but as you admit that isn't always the case. The point of having a label to opt out is to make sure it is an explicit opt-out of a news entry so people don't forget. If we made this change there would be  an increase in instances where people forgot the news entry when it was appropriate.

**Comment by isidentical** [comment]
Thanks for your response. That is a valid point. I have another idea but i don't think that is suitable for this workflow (you can close the issue if you agree with me): using a bot command to label our own PRs without triage permission. Like `'@botsname label skip-news`, `@botsname skip-issue`

**Comment by terryjreedy** [comment]
I agree with Brett.  Our general rule is that if something is important enough to merit an issue, it should get a news entry.  There are a few exceptions, mostly for doc issues.  But these are fewer since we moved to github.  Trivial  doc changes are often reported with a no-issue PR instead of a bpo issue.

**Comment by brettcannon** [comment]
@isidentical giving PR authors abilities to specify labels on their own is a separate issue (there may already be one open?). There's also the question as to whether people will use the labels appropriately (e.g. saying to skip news when in fact it shouldn't). But anyway, separate discussion.
