### ISSUE TITLE
Add type-behavior label for CPython PRs

### ISSUE THREAD

**Issue by aeros** [python/core-workflow#364]
With the existing labels for CPython PRs, I think a `type-behavior` label could be quite useful for describing PRs that involve changes in functionality and don't add new features (which would be covered by `type-enhancement`). This label already exists on BPO, and frequently feels missing on GitHub. It may not seem incredibly important at the moment, but I think it will be more noticeable as we transition to GitHub issues.

As a concrete example of a PR that it would be well suited towards, I recently opened a [PR](https://github.com/python/cpython/pull/19149) that makes an internal change in `concurrent.futures` to not use daemon threads for compatibility with subinterpreters. A `type-behavior` label would definitely be appropriate, while none of the others would quite fit.

I can also think of quite a few other types of PRs that it could be well suited towards, such as new warnings (including deprecation, resource, etc), removals, and any other code changes in the internals that wouldn't qualify as a bug fix, performance optimization, or enhancement.

The addition of the label should be rather straightforward, as it would not include any new functionality or act as a trigger for a bot action.

**Comment by brettcannon** [comment]
So it depends on your view of the separation of "bug" and "enhancement" as to whether this sort of label would be necessary. Any semantic change in behaviour -- and that's how it should be spelled 😉 -- is either a bugfix or an enhancement since we don't make changes just for fun. 😉 For instance, I don't think of enhancements as only covering additive changes, but any change which wasn't done to fix a bug and thus isn't going to get backported.

**Comment by aeros** [comment]
> For instance, I don't think of enhancements as only covering additive changes, but any change which wasn't done to fix a bug and thus isn't going to get backported.

Ah, I see. I suppose that I've mostly thought of "enhancements" as being primarily additive changes. But, I don't have a substantial issue with using the enhancement label to describe other semantic changes, as long as it's clear. I think the main point of confusion was that BPO has a clear "behavior" category that didn't obviously fit under "enhancement" (at least to me).

Thanks for clarifying. :-)
