### ISSUE TITLE
Make Travis CI (and Windows x64 ?) mandatory

### ISSUE THREAD

**Issue by vstinner** [python/core-workflow#365]
Azure Pipelines CI was made optional by @brettcannon: https://bugs.python.org/issue39837

Problem: now, there is no more mandatory CI on Python pull requests. It became possible to merge a PR even if all CIs fail.

I would prefer to also have the Windows 64-bit CI (GitHub Action) mandatory, but I'm not sure if it's possible to only make a single GitHub Action mandatory?

**Comment by Mariatta** [comment]
I can make the change. Which CI should be required, and is this the same for all branches? 3.5, 3.6, 3.7, 3.8?

**Comment by Mariatta** [comment]
These are the availble CIs which I can make as "Required". Just let me know which ones we need, then i'll activate them:

Azure Pipelines CI
 Azure Pipelines PR
 Docs
 Ubuntu
 Ubuntu (C Coverage)
 Ubuntu (Coverage)
 Windows (x64)
 Windows (x86)
 bedevere/issue-numberRequired
 bedevere/maintenance-branch-pr
 bedevere/newsRequired
 buildbot/AMD64 Arch Linux TraceRefs 3.7
 buildbot/AMD64 Arch Linux TraceRefs 3.8
 buildbot/AMD64 Arch Linux TraceRefs 3.x
 buildbot/AMD64 Arch Linux TraceRefs PR
 buildbot/AMD64 Debian PGO 3.7
 buildbot/AMD64 Debian PGO 3.8
 buildbot/AMD64 Debian PGO 3.x
 buildbot/AMD64 Debian PGO PR
 buildbot/AMD64 Debian root 3.7
 buildbot/AMD64 Debian root 3.8
 buildbot/AMD64 Debian root 3.x
 buildbot/AMD64 Debian root PR
 buildbot/AMD64 Fedora Stable 3.7
 buildbot/AMD64 Fedora Stable 3.8
 buildbot/AMD64 Fedora Stable 3.x
 buildbot/AMD64 Fedora Stable Clang 3.7
 buildbot/AMD64 Fedora Stable Clang 3.8
 buildbot/AMD64 Fedora Stable Clang 3.x
 buildbot/AMD64 Fedora Stable Clang Installed 3.7
 buildbot/AMD64 Fedora Stable Clang Installed 3.8
 buildbot/AMD64 Fedora Stable Clang Installed 3.x
 buildbot/AMD64 Fedora Stable Clang Installed PR
 buildbot/AMD64 Fedora Stable Clang PR
 buildbot/AMD64 Fedora Stable LTO + PGO 3.7
 buildbot/AMD64 Fedora Stable LTO + PGO 3.8
 buildbot/AMD64 Fedora Stable LTO + PGO 3.x
 buildbot/AMD64 Fedora Stable LTO + PGO PR
 buildbot/AMD64 Fedora Stable LTO 3.7
 buildbot/AMD64 Fedora Stable LTO 3.8
 buildbot/AMD64 Fedora Stable LTO 3.x
 buildbot/AMD64 Fedora Stable LTO PR
 buildbot/AMD64 Fedora Stable PR
 buildbot/AMD64 Fedora Stable Refleaks PR
 buildbot/AMD64 FreeBSD Non-Debug 3.7
 buildbot/AMD64 FreeBSD Non-Debug 3.8
 buildbot/AMD64 FreeBSD Non-Debug 3.x
 buildbot/AMD64 FreeBSD Non-Debug PR
 buildbot/AMD64 FreeBSD Shared 3.7
 buildbot/AMD64 FreeBSD Shared 3.8
 buildbot/AMD64 FreeBSD Shared 3.x
 buildbot/AMD64 FreeBSD Shared PR
 buildbot/AMD64 RHEL7 3.7
 buildbot/AMD64 RHEL7 3.8
 buildbot/AMD64 RHEL7 3.x
 buildbot/AMD64 RHEL7 LTO + PGO 3.7
 buildbot/AMD64 RHEL7 LTO + PGO 3.8
 buildbot/AMD64 RHEL7 LTO + PGO 3.x
 buildbot/AMD64 RHEL7 LTO + PGO PR
 buildbot/AMD64 RHEL7 LTO 3.7
 buildbot/AMD64 RHEL7 LTO 3.8
 buildbot/AMD64 RHEL7 LTO 3.x
 buildbot/AMD64 RHEL7 LTO PR
 buildbot/AMD64 RHEL7 PR
 buildbot/AMD64 RHEL7 Refleaks PR
 buildbot/AMD64 RHEL8 3.7
 buildbot/AMD64 RHEL8 3.8
 buildbot/AMD64 RHEL8 3.x
 buildbot/AMD64 RHEL8 LTO + PGO 3.7
 buildbot/AMD64 RHEL8 LTO + PGO 3.8
 buildbot/AMD64 RHEL8 LTO + PGO 3.x
 buildbot/AMD64 RHEL8 LTO + PGO PR
 buildbot/AMD64 RHEL8 LTO 3.7
 buildbot/AMD64 RHEL8 LTO 3.8
 buildbot/AMD64 RHEL8 LTO 3.x
 buildbot/AMD64 RHEL8 LTO PR
 buildbot/AMD64 RHEL8 PR
 buildbot/AMD64 RHEL8 Refleaks PR
 buildbot/AMD64 Ubuntu Shared 3.7
 buildbot/AMD64 Ubuntu Shared 3.8
 buildbot/AMD64 Ubuntu Shared 3.x
 buildbot/AMD64 Ubuntu Shared PR
 buildbot/AMD64 Windows10 3.7
 buildbot/AMD64 Windows10 3.8
 buildbot/AMD64 Windows10 3.x
 buildbot/AMD64 Windows10 PR
 buildbot/AMD64 Windows7 SP1 3.7
 buildbot/AMD64 Windows7 SP1 3.8
 buildbot/AMD64 Windows8.1 Non-Debug 3.7
 buildbot/AMD64 Windows8.1 Non-Debug 3.8
 buildbot/AMD64 Windows8.1 Non-Debug 3.x
 buildbot/AMD64 Windows8.1 Non-Debug PR
 buildbot/AMD64 Windows8.1 Refleaks PR
 buildbot/PPC64 Fedora 3.7
 buildbot/PPC64 Fedora 3.8
 buildbot/PPC64 Fedora 3.x
 buildbot/PPC64 Fedora PR
 buildbot/PPC64LE Fedora Stable 3.7
 buildbot/PPC64LE Fedora Stable 3.8
 buildbot/PPC64LE Fedora Stable 3.x
 buildbot/PPC64LE Fedora Stable Clang 3.7
 buildbot/PPC64LE Fedora Stable Clang 3.8
 buildbot/PPC64LE Fedora Stable Clang 3.x
 buildbot/PPC64LE Fedora Stable Clang Installed 3.7
 buildbot/PPC64LE Fedora Stable Clang Installed 3.8
 buildbot/PPC64LE Fedora Stable Clang Installed 3.x
 buildbot/PPC64LE Fedora Stable Clang Installed PR
 buildbot/PPC64LE Fedora Stable Clang PR
 buildbot/PPC64LE Fedora Stable LTO + PGO 3.7
 buildbot/PPC64LE Fedora Stable LTO + PGO 3.8
 buildbot/PPC64LE Fedora Stable LTO + PGO 3.x
 buildbot/PPC64LE Fedora Stable LTO + PGO PR
 buildbot/PPC64LE Fedora Stable LTO 3.7
 buildbot/PPC64LE Fedora Stable LTO 3.8
 buildbot/PPC64LE Fedora Stable LTO 3.x
 buildbot/PPC64LE Fedora Stable LTO PR
 buildbot/PPC64LE Fedora Stable PR
 buildbot/PPC64LE Fedora Stable Refleaks PR
 buildbot/PPC64LE RHEL7 3.7
 buildbot/PPC64LE RHEL7 3.8
 buildbot/PPC64LE RHEL7 3.x
 buildbot/PPC64LE RHEL7 LTO + PGO 3.7
 buildbot/PPC64LE RHEL7 LTO + PGO 3.8
 buildbot/PPC64LE RHEL7 LTO + PGO 3.x
 buildbot/PPC64LE RHEL7 LTO + PGO PR
 buildbot/PPC64LE RHEL7 LTO 3.7
 buildbot/PPC64LE RHEL7 LTO 3.8
 buildbot/PPC64LE RHEL7 LTO 3.x
 buildbot/PPC64LE RHEL7 LTO PR
 buildbot/PPC64LE RHEL7 PR
 buildbot/PPC64LE RHEL7 Refleaks PR
 buildbot/PPC64LE RHEL8 3.7
 buildbot/PPC64LE RHEL8 3.8
 buildbot/PPC64LE RHEL8 3.x
 buildbot/PPC64LE RHEL8 LTO + PGO 3.7
 buildbot/PPC64LE RHEL8 LTO + PGO 3.8
 buildbot/PPC64LE RHEL8 LTO + PGO 3.x
 buildbot/PPC64LE RHEL8 LTO + PGO PR
 buildbot/PPC64LE RHEL8 LTO 3.7
 buildbot/PPC64LE RHEL8 LTO 3.8
 buildbot/PPC64LE RHEL8 LTO 3.x
 buildbot/PPC64LE RHEL8 LTO PR
 buildbot/PPC64LE RHEL8 PR
 buildbot/PPC64LE RHEL8 Refleaks PR
 buildbot/aarch64 Fedora Stable 3.7
 buildbot/aarch64 Fedora Stable 3.8
 buildbot/aarch64 Fedora Stable 3.x
 buildbot/aarch64 Fedora Stable PR
 buildbot/aarch64 RHEL7 3.7
 buildbot/aarch64 RHEL7 3.8
 buildbot/aarch64 RHEL7 3.x
 buildbot/aarch64 RHEL7 PR
 buildbot/aarch64 RHEL8 3.7
 buildbot/aarch64 RHEL8 3.8
 buildbot/aarch64 RHEL8 3.x
 buildbot/aarch64 RHEL8 PR
 buildbot/s390x Debian 3.7
 buildbot/s390x Debian 3.8
 buildbot/s390x Debian 3.x
 buildbot/s390x Debian PR
 buildbot/s390x Fedora 3.7
 buildbot/s390x Fedora 3.8
 buildbot/s390x Fedora 3.x
 buildbot/s390x Fedora Clang 3.7
 buildbot/s390x Fedora Clang 3.8
 buildbot/s390x Fedora Clang 3.x
 buildbot/s390x Fedora Clang Installed 3.7
 buildbot/s390x Fedora Clang Installed 3.8
 buildbot/s390x Fedora Clang Installed 3.x
 buildbot/s390x Fedora Clang Installed PR
 buildbot/s390x Fedora Clang PR
 buildbot/s390x Fedora LTO + PGO 3.7
 buildbot/s390x Fedora LTO + PGO 3.8
 buildbot/s390x Fedora LTO + PGO 3.x
 buildbot/s390x Fedora LTO + PGO PR
 buildbot/s390x Fedora LTO 3.7
 buildbot/s390x Fedora LTO 3.8
 buildbot/s390x Fedora LTO 3.x
 buildbot/s390x Fedora LTO PR
 buildbot/s390x Fedora PR
 buildbot/s390x Fedora Refleaks PR
 buildbot/s390x RHEL7 3.7
 buildbot/s390x RHEL7 3.8
 buildbot/s390x RHEL7 3.x
 buildbot/s390x RHEL7 LTO + PGO 3.7
 buildbot/s390x RHEL7 LTO + PGO 3.8
 buildbot/s390x RHEL7 LTO + PGO 3.x
 buildbot/s390x RHEL7 LTO + PGO PR
 buildbot/s390x RHEL7 LTO 3.7
 buildbot/s390x RHEL7 LTO 3.8
 buildbot/s390x RHEL7 LTO 3.x
 buildbot/s390x RHEL7 LTO PR
 buildbot/s390x RHEL7 PR
 buildbot/s390x RHEL7 Refleaks PR
 buildbot/s390x RHEL8 3.7
 buildbot/s390x RHEL8 3.8
 buildbot/s390x RHEL8 3.x
 buildbot/s390x RHEL8 LTO + PGO 3.7
 buildbot/s390x RHEL8 LTO + PGO 3.8
 buildbot/s390x RHEL8 LTO + PGO 3.x
 buildbot/s390x RHEL8 LTO + PGO PR
 buildbot/s390x RHEL8 LTO 3.7
 buildbot/s390x RHEL8 LTO 3.8
 buildbot/s390x RHEL8 LTO 3.x
 buildbot/s390x RHEL8 LTO PR
 buildbot/s390x RHEL8 PR
 buildbot/s390x RHEL8 Refleaks PR
 buildbot/s390x SLES 3.7
 buildbot/s390x SLES 3.8
 buildbot/s390x SLES 3.x
 buildbot/s390x SLES PR
 buildbot/x86 Gentoo Installed with X 3.7
 buildbot/x86 Gentoo Installed with X 3.8
 buildbot/x86 Gentoo Installed with X 3.x
 buildbot/x86 Gentoo Installed with X PR
 buildbot/x86 Gentoo Non-Debug with X 3.7
 buildbot/x86 Gentoo Non-Debug with X 3.8
 buildbot/x86 Gentoo Non-Debug with X 3.x
 buildbot/x86 Gentoo Non-Debug with X PR
 buildbot/x86 Gentoo Refleaks PR
 buildbot/x86 Windows7 3.7
 buildbot/x86 Windows7 3.8
 buildbot/x86-64 macOS 3.7
 buildbot/x86-64 macOS 3.8
 buildbot/x86-64 macOS 3.x
 buildbot/x86-64 macOS PR
 continuous-integration/travis-ci
 macOS

**Comment by vstinner** [comment]
It would be nice to have a least one Linux mandatory CI and one Windows mandatory CI:

* Travis CI
* Windows 64-bit (GH action)

It can be the same on 3.7, 3.8 and master branches.

--

For 3.5 and 3.6, only Travis CI should be mandatory.

I don't think that we have GH actions on the 3.5 branch. Example on my 3.5 PR: https://github.com/python/cpython/pull/19305 there is only Travis CI there.

Same for 3.6: I only see Travis CI on this 3.6 PR: https://github.com/python/cpython/pull/19224

**Comment by vstinner** [comment]
In your list, I'm talking about:

* Windows (x64)
* continuous-integration/travis-ci

**Comment by Mariatta** [comment]
It's done. 
`continuous-integration/travis-ci` and `Windows (x64)` are now required in `master`, `3.8`, `3.7`.
`continuous-integration/travis-ci` is required in `3.5` and `3.6`.

**Comment by vstinner** [comment]
Great, thank you!

**Comment by zooba** [comment]
Unfortunately, you can't make the GitHub Actions checks required, because GitHub can't tell the difference between when they are excluded by path filters (see https://github.com/python/cpython/pull/19806)

I'm pinging my contacts there again, but we're going to have to only require Linux tests for now.

**Comment by zooba** [comment]
(FWIW, @Mariatta, since you weren't involved in the other discussions, there isn't anyone else supportive of this change that I'm aware of - it's only Victor. But since he's not going to stop his campaign against network flakiness, I'll concede - but NOT in a way that prevents people from merging doc-only changes!)

**Comment by vstinner** [comment]
Me:
> I would prefer to also have the Windows 64-bit CI (GitHub Action) mandatory, but I'm not sure if it's possible to only make a single GitHub Action mandatory?

@zooba:
> Unfortunately, you can't make the GitHub Actions checks required, because GitHub can't tell the difference between when they are excluded by path filters (see python/cpython#19806)

Oh right, now I recall the issue :-/ https://bugs.python.org/issue39837#msg363405

**Comment by vstinner** [comment]
> Oh right, now I recall the issue :-/ https://bugs.python.org/issue39837#msg363405

I moved the discussion to the Core Workflow category of Discourse:
https://discuss.python.org/t/make-one-windows-ci-job-mandatory/4047

--

@Mariatta: Sorry, would you mind to make the Windows (64 bit) job non-voting again, until https://discuss.python.org/t/make-one-windows-ci-job-mandatory/4047 issue is resolved?

**Comment by Mariatta** [comment]
Windows(64) has been made not required.

**Comment by vstinner** [comment]
> Windows(64) has been made not required.

Thanks again.

**Comment by vstinner** [comment]
I fixed the Windows job of GitHub Action and proposed https://github.com/python/core-workflow/issues/368 to make it mandatory.

**Comment by cjerdonek** [comment]
FYI, I created PR #20105 that updates only the ACKS file, and the required Travis CI never starts. It just stays on, "Expected — Waiting for status to be reported." Does someone know why that is happening or what I can do to skip it or get it to run?

**Comment by Mariatta** [comment]
> the required Travis CI never starts

Happens sometimes. It could be something wrong on either GitHub or Travis CI's side. Usually I just close and re-open the PR to retrigger the check.

**Comment by cjerdonek** [comment]
I did try it twice, but I can keep trying.

**Comment by vstinner** [comment]
> I did try it twice, but I can keep trying.

I see that https://github.com/python/cpython/pull/20105 is merged so it seems like the problem is gone :-)

I hope that the issue is now resolved.

**Comment by vstinner** [comment]
If someone wants to investigate, https://travis-ci.org/python/cpython/builds gives the list of all Travis CI jobs of the CPython project.

**Comment by cjerdonek** [comment]
> I hope that the issue is now resolved.

Yes, I tried once more and it worked. Thanks for your help, @Mariatta  and @vstinner.

**Comment by brettcannon** [comment]
Both WIndows x64 and Travis are currently required, so closing.
