### ISSUE TITLE
Is the bot adding "CLA signed" or "CLA not signed" sick?

### ISSUE THREAD

**Issue by vstinner** [python/core-workflow#366]
Hi, on https://github.com/python/cpython/pull/19832 I cannot see any "CLA signed" or "CLA not signed" label. Did the bot disappear or is it broken? I don't know which bot is responsible of this label.

@Mariatta: any idea?

**Comment by vstinner** [comment]
Hum, it looks specific to https://github.com/python/cpython/pull/19832

The PRs https://github.com/python/cpython/pull/19833 and https://github.com/python/cpython/pull/19834 got the label.

**Comment by vstinner** [comment]
> Hum, it looks specific to python/cpython#19832

GitHub action jobs didn't start neither on this PR, but they started when I closed/reopened the issue: https://github.com/python/core-workflow/issues/367

It looks like a workflow hiccup. Maybe we can safely ignore it.

---

I added the "CLA not signed" label, then I removed it. It worked around the issue:

> @vstinner vstinner added the CLA not signed label 1 minute ago
> @vstinner vstinner removed the CLA not signed label now
> @the-knights-who-say-ni the-knights-who-say-ni added the CLA signed label now 

The bot added "CLA signed" label. Good!

I close the issue, it doesn't seem to be blocker.

**Comment by terryjreedy** [comment]
Same for https://github.com/python/cpython/pull/19816

**Comment by Mariatta** [comment]
There were failed webhook deliveries for https://github.com/python/cpython/pull/19832 and https://github.com/python/cpython/pull/19816.

I just redelivered the webhook and it seemed to work now.

**Comment by brettcannon** [comment]
The rule of thumb is if any of the bots don't work it's because there was a networking hiccup between GitHub and the bots. Give it a little time and try closing and re-opening the issues or flipping a label on/off and that usually re-runs things.
