### ISSUE TITLE
Make Windows (x64) GitHub action mandatory on master branch

### ISSUE THREAD

**Issue by vstinner** [python/core-workflow#368]
Hi,

Last week, I asked to make Travis CI and Windows (x64) CI mandatory on Python PRs: https://github.com/python/core-workflow/issues/365

Problem: on documentation-only PRs, GitHub Action jobs were not run but GitHub still required Windows (x64) job to pass even if it never run.

I worked around the issue in the master branch, by always running GitHub action jobs, even for documentation-only PRs:
* https://github.com/python/cpython/commit/4e363761fc02a89d53aba4382dc451293bd6f0ba
* https://bugs.python.org/issue40548

**Would it be possible to make Windows (x64) mandatory in the master branch?**

If it goes well, I will backport the change to 3.7 and 3.8 and then request to also make it mandatory there.

Another PR was also proposed to skip GH Actions jobs for documentation-only changes. Basically, re-do what was done previously, but in a different ways (without "paths-ignored") to workaround a GitHub limitation.

@Mariatta @zooba @brettcannon: Is it ok for you?

Example of recent PR: https://github.com/python/cpython/pull/19982 all jobs are green, great :-) (Windows (x64) helped me to find a real bug in the first version of my PR, thanks!)

**Comment by vstinner** [comment]
@Mariatta @zooba @brettcannon: Friendly ping. Are you ok to make the Windows (x64) CI mandatory on Python PRs?

**Comment by Mariatta** [comment]
In general, if the CI is reliable and trustworthy then I think it's good to make it mandatory. But I don't have much context on why it was disabled in the first place (that thread and bpo ticket are a bit long for me to keep up, sorry). I'll defer to the Windows experts for final decision.

**Comment by vstinner** [comment]
> In general, if the CI is reliable and trustworthy then I think it's good to make it mandatory. But I don't have much context on why it was disabled in the first place (that thread and bpo ticket are a bit long for me to keep up, sorry). I'll defer to the Windows experts for final decision.

Previously, it wasn't possible to make a GitHub Action job mandatory because of the issue with documentation only PRs: https://bugs.python.org/issue40548

These jobs were never mandatory. I propose to start to make one mandatory on the master branch.

**Comment by vstinner** [comment]
Update: GitHub Action Tests jobs are now skipped for documentation-only changes... as it was done before :-) But it's implemented differently, which again, allows to make a job (like Windows x64) mandatory: it should not hold a PR anymore if the job is skipped.
https://github.com/python/cpython/commit/75d7257b201a56f950c20cd9f5753a83fff4742b

**Comment by vstinner** [comment]
So far, GitHub configuration changes were only pushed into master. I prefer to ensure that it works as expected before backporting changes. But the Windows job cannot be made mandatory in branches other than master until the GitHub configuration changes are backported to these branches.

**Comment by Mariatta** [comment]
Perhaps we can first apply and backport the GitHub Actions changes first and see how it works for the next 2 weeks. If it works great, we can then make it a required CI.

Thanks.

**Comment by vstinner** [comment]
> Perhaps we can first apply and backport the GitHub Actions changes first and see how it works for the next 2 weeks. If it works great, we can then make it a required CI.

Sure. I'm fine with this plan.

**Comment by vstinner** [comment]
@brettcannon @Mariatta: So far, Windows x64 look reliable. I only saw one or two download errors while getting dependencies. Is it now ok to make this CI mandatory?

**Comment by vstinner** [comment]
Any update on this issue?

**Comment by brettcannon** [comment]
Looking at https://github.com/python/cpython/pull/20694 suggests that Windows x64 is not being run on documentation changes and is still being explicitly skipped instead of being flagged as successful while not running actual tests. I thought the issue we had was GitHub didn't consider skipped tests as passing from a required test perspective. Do we know if that's still the case?

**Comment by vstinner** [comment]
Previously, "paths-ignored" was used in the configuration. This caused the troubles.

The workflow was designed to use `if: needs.check_source.outputs.run_tests == 'true'` which should not have the issue.

See https://bugs.python.org/issue40548 for changes and discussion.

**Comment by brettcannon** [comment]
I just flipped on the `Windows (x64)` status check as mandatory on master.

**Comment by FFY00** [comment]
If you go to #20740 you should now see a shiny green button.

I think this can be closed now.

**Comment by vstinner** [comment]
> If you go to python/cpython#20740 you should now see a shiny green button.

I confirm: the Windows x64 job is skipped but I can still merge the PR :-)
