### ISSUE TITLE
Add more pre-commit CIs to Python 3.9 PRs

### ISSUE THREAD

**Issue by vstinner** [python/core-workflow#369]
Currently, PRs on the 3.9 branch of Python only gets 1 CI (Travis CI) + 3 bots. Example:
https://github.com/python/cpython/pull/20228

Whereas PRs on 3.8 branch of Python get 8 CIs + 3 bots. Example:
https://github.com/python/cpython/pull/20191

Would it be possible to enable GitHub Action jobs on the 3.9 branch? cc @Mariatta @ambv @pablogsal 

Also: How can we enable Azure Pipelines on 3.9? cc @brettcannon @zooba

**Comment by hugovk** [comment]
Please see PR https://github.com/python/cpython/pull/20231 to enable GHA for the 3.9 branch.

**Comment by vstinner** [comment]
> Would it be possible to enable GitHub Action jobs on the 3.9 branch? cc @Mariatta @ambv @pablogsal

Ok, this part should be fixed by https://github.com/python/cpython/commit/c105f7d8955ef9bf51125f6e44e8543e5f0618df

**Comment by brettcannon** [comment]
FYI I don't know anything about Azure Pipelines. I know way more about GitHub Actions.

**Comment by vstinner** [comment]
> Please see PR python/cpython#20231 to enable GHA for the 3.9 branch.

Changing the config in master wasn't enough. Backporting to 3.9 fixed it. Example: https://github.com/python/cpython/pull/20228

**Comment by zooba** [comment]
Sorry, just saw this. I'm switching the Pipelines trigger configuration back to the YAML files, so it'll be enabled soon.

**Comment by CAM-Gerlach** [comment]
Just checking in since this was referenced in python/peps#1405 — is this fixed now?

**Comment by hugovk** [comment]
No comments one year on, I think we're good here so let's close this issue, and can re-open, or open a new issue if there's something still needed.
