### ISSUE TITLE
Use "stale" GitHub actions to mark PRs as stale

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#372]
It would be great if we can set up the `stale` GitHub Actions to the CPython repo to automatically mark PRs as stale:

https://github.com/actions/stale

**Comment by Mariatta** [comment]
Created the PR for this functionality, and I'm using bedevere-bot's GitHub token. https://github.com/python/cpython/pull/21247

Let me know if we want to use other bot's GitHub token.

**Comment by brettcannon** [comment]
We shouldn't use any bot token as it's not necessary. GitHub Actions comes with its own write token for a repo.

I also left a comment about the setting to close PRs after 5 days from being marked stale. That's a big shift in how we manage the PR queue and probably requires a broader discussion.
