### ISSUE TITLE
Please make Travis CI optional again

### ISSUE THREAD

**Issue by vstinner** [python/core-workflow#377]
Please make Travis CI job optional on Python. The issue https://github.com/python/core-workflow/issues/376 prevents to merge PRs even when the Travis CI run succesfully.

----

For example, https://github.com/python/cpython/pull/22513 was created 5 days ago. The PR lists two Travis CI builds. One is "Queued — Build Created", the other one is "Successful in 16m — Build Passed". Problem: if you click on the two builds... it's the same build: https://travis-ci.com/github/python/cpython/builds/188824091

Travis CI integration in GitHub is sick for several months and I'm tired of trying to fix it. Again, see https://github.com/python/core-workflow/issues/376 for the 3rd issue in 6 months.

**Comment by vstinner** [comment]
I'm not fully comfortable with having no mandatory Linux job on PRs. One solution would be to make the "Ubuntu (pull_request)" GitHub Action job mandatory.

What do you think of making the Travis CI job optional and make the Ubuntu job mandatory, at the same time?

Can this change be done for 3.7, 3.8, 3.9 and master branches? I see the Ubuntu job on my recent 3.7 PR: https://github.com/python/cpython/pull/22578 (backport)

For Python 3.6, I see GitHub Action jobs, but only @ned-deily is allowed to merge changes on this branch. I'm sure that he will pay a special attention to all CIs before merging anything! Example of recent 3.6 PR: https://github.com/python/cpython/pull/22579 (backport).

For 3.6, I suggest to just make Travis CI optional.

@ewdurbin @Mariatta @brettcannon: Who is allowed to make a CI mandatory or optional on the GitHub cpython project?

**Comment by ewdurbin** [comment]
> @ewdurbin @Mariatta @brettcannon: Who is allowed to make a CI mandatory or optional on the GitHub cpython project?

Current organization [owners](https://devguide.python.org/devcycle/?highlight=github%20administrators#current-owners) and repository [administrators](https://devguide.python.org/devcycle/?highlight=github%20administrators#current-owners)

**Comment by ewdurbin** [comment]
When some consensus is determined, I'm happy to handle this, just mention me again.

**Comment by brettcannon** [comment]
I strongly support the proposed change.

**Comment by vstinner** [comment]
Once the change will be applied, I will notify python-committers list as I did last May when Travis CI became mandatory.
https://mail.python.org/archives/list/python-committers@python.org/message/B6WVI254L7GEOCKUOHZ6XBZD4GCLAIBV/

In May, Tracis CI looked reliable. Over time, it is getting worse and worse. I'm tired to spending time on trying to fix each Travis CI issue.

**Comment by Mariatta** [comment]
I also agree with making travisci not required for now.
I've brought up this issue with GitHub OS Maintainers feedback group. They said:
> "The team responsible for Checks has been looking into this issue, but I'm not sure about a timeline for a fix"

**Comment by vstinner** [comment]
> Given Travis's unreliability and their lack of any visible response or feedback on their forums

Oh right, I forgot to mention that "Travis CI fails to report build status to GitHub PR" is an old known issue and is frequently reported to the Travis CI community. I didn't see concrete progress over the last months.

**Comment by vstinner** [comment]
@ewdurbin: I count 3 people in favor of the making Travis CI optional, and no one who wants to keep it as mandatory. Would you mind to make it optional?

**Comment by ewdurbin** [comment]
@vstinner for all branches?

**Comment by ned-deily** [comment]
> @vstinner for all branches?

Yes, please.

**Comment by ewdurbin** [comment]
Done.

**Comment by vstinner** [comment]
> Done.

Thanks Ernerst! I announced the change on python-committers:
https://mail.python.org/archives/list/python-committers@python.org/thread/JR7HIQHVECHPKH2LE46EACN73KCBLVKE/

Now, should we consider to make the Ubuntu job mandatory, at least on the master branch, to get at least one Linux CI mandatory job?

**Comment by vstinner** [comment]
This change fixed issue #376.

**Comment by ned-deily** [comment]
Update: at the Core Dev Virtual Sprint today, the issue of continuing to run Travis at all was discussed with the opinion voiced that, if the Travis CI jobs are now optional and if few people are even looking at them, it would be better to not keep wasting Travis resources to the potential detriment of other projects using Travis.  A majority of the current release managers (with no dissensions) and @brettcannon agreed to disable the Travis hooks on all branches - at least until we have reason to believe that the intermittent problems we have been seeing are gone - and that has now been done.  So I think we can now close this issue.

**Comment by terryjreedy** [comment]
On 10/19/2020 5:14 PM, Ned Deily wrote:
> Update: at the Core Dev Virtual Sprint today, the issue of continuing to 
> run Travis at all was discussed with the opinion voiced that, if the 
> Travis CI jobs are now optional and if few people are even looking at 
> them, it would be better to not keep wasting Travis resources to the 
> potential detriment of other projects using Travis. A majority of the 
> current release managers (with no dissensions) and @brettcannon 
> <https://github.com/brettcannon> agreed to disable the Travis hooks on 
> all branches - at least until we have reason to believe that the 
> intermittent problems we have been seeing are gone - and that has now 
> been done. So I think we can now close this issue.

I look at all test failures, regardless of whether required or not.  I 
really want to be able to override bogus test failures, which most are 
for me.

automerge should be blocked by any failure, not just of 'required' 
tests.  I believe this is the case when a backport test fails even when 
the backport has the required approval.  But maybe that is just the bot 
programming.

Terry

**Comment by ned-deily** [comment]
It looks I spoke too soon: Travis checks are still running for PRs.  And it looks like we haven't yet made at least one Ubuntu check mandatory as was also discussed elsewhere.  Reopening.

**Comment by ammaraskar** [comment]
> Now, should we consider to make the Ubuntu job mandatory, at least on the master branch, to get at least one Linux CI mandatory job?

Yes please, it looks like there's consensus on this on python-committers as well: https://mail.python.org/archives/list/python-committers@python.org/thread/JR7HIQHVECHPKH2LE46EACN73KCBLVKE/ 

Would you mind setting the ubuntu github action to required @ewdurbin?

**Comment by brettcannon** [comment]
The Travis checks were taken off, so I went ahead and made the "Ubuntu" check required.

Since that should cover everything, I'm closing this issue.
