### ISSUE TITLE
Python Triage access for iritkatriel

### ISSUE THREAD

**Issue by ammaraskar** [python/core-workflow#378]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @iritkatriel |
| bpo username   | iritkatriel     |
| Additional info   | bugs.python.org [search with issues they last commented on](https://bugs.python.org/issue?%40search_text=&ignore=file%3Acontent&title=&%40columns=title&id=&%40columns=id&stage=&creation=&creator=&activity=&%40columns=activity&%40sort=activity&actor=iritkatriel&nosy=&type=&components=&versions=&dependencies=&assignee=&keywords=&priority=&status=1&%40columns=status&resolution=&nosy_count=&message_count=&%40group=&%40pagesize=50&%40startwith=0&%40sortdir=on&%40queryname=&%40old-queryname=&%40action=search).  |

Irit has been doing a great job going over the issue backlog and finding stale/straight forward issues to close off. Some recent examples:

* https://bugs.python.org/issue33592
* https://bugs.python.org/issue40471
* https://bugs.python.org/issue37840

I think they'd benefit from being given triage powers so they can close these off directly.

**Comment by zware** [comment]
If I had realized earlier that this hadn't already been done, I'd have granted the developer role on bpo already.  I can go ahead and do that now if someone with access on GitHub can grant that one.

**Comment by Mariatta** [comment]
Just wanted to get confirmation whether @iritkatriel is open and interested in accepting this role.

**Comment by iritkatriel** [comment]
Thank you so much! I would be very excited to join the team.

**Comment by zware** [comment]
Done on bpo! @iritkatriel, you'll now be able to close issues or update issue metadata on your own; feel free to add me (zach.ware) to the nosy list when you want a double-check after the fact :)

**Comment by Mariatta** [comment]
@ewdurbin @dstufft @benjaminp Would one of you be able to add @iritkatriel to the Python Triage Member team on GitHub? Thanks.

**Comment by ewdurbin** [comment]
Invite sent.

**Comment by Mariatta** [comment]
Thanks! @iritkatriel please review the Triaging section on the Devguide https://devguide.python.org/triaging/ and welcome to the triage team!

**Comment by iritkatriel** [comment]
> Invite sent.

And accepted - thank you!

**Comment by brandtbucher** [comment]
Thanks and congrats @iritkatriel!
