### ISSUE TITLE
Request for Python Triage Membership for Andre Delfino

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#379]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @andresdelfino  |
| bpo username   | adelfino     |
| Additional info   | @andresdelfino has been contributing to Python for more than two years and has lots of PRs merged on CPython repo. Nominated by @Mariatta | |

**Comment by Mariatta** [comment]
I have messaged @andresdelfino privately and received confirmation that they would like take on the additional responsibilities.

@ewdurbin @dstufft @benjaminp would you be able to invite @andresdelfino to the Python Triage team on GitHub? 

Thanks.

**Comment by ewdurbin** [comment]
Invitation sent.

**Comment by andresdelfino** [comment]
Just accepted the invitation, thank you all!

**Comment by Mariatta** [comment]
Thanks all! Let me know if you have any questions!
