### ISSUE TITLE
Getting mails from Codacy for cpython

### ISSUE THREAD

**Issue by The-Compiler** [python/core-workflow#384]
Hey! I'm not sure if this is the right place for this request, and I'm not sure if there was any previous discussion anywhere - but looking through this repository, the mailinglists, the bugtracker and Discourse, I can't find anything.

Since yesterday, for every change in `python/cpython`, I get a mail from Codacy:

![image](https://user-images.githubusercontent.com/625793/98944951-210b3400-24f2-11eb-9bac-6340d4d7c1bb.png)

When I try the unsubscribe link, I get asked to link my GitHub account, which I'd rather not do just to disable those mails...

I've reached out to Codacy support about this, since the only thing I've done is to contribute a commit or two - they said:

> By default, Codacy will send an email to all users who contribute to a repo when there is an update on it, and all users who created at least one commit will be considered as contributors to the repo.
>
> I totally understand that those emails aren't useful to you and I can disable them for your account. Would this work for you?

Naturally I'll ask them to disable those mails for me - but it seems to me like this is a far bigger issue. I assume anyone who's ever contributed to CPython will get those emails with every commit (I think I got three so far?).

If this is indeed related to someone enabling Codacy for the cpython repo or the python organization, please consider disabling it again, unless it's *really* needed - IMHO, this is unacceptable behavior from their side and a good reason for not using it.

**Comment by Mariatta** [comment]
Hmm this is weird. I'm not aware that we even use codacy in the CPython repo. 😕  We use codecov. So I'm not sure what to do here.

**Comment by The-Compiler** [comment]
Note that Codacy is a static analyzer, similar to things like Coverty mentioned in the experts index (both not related to test coverage, despite the names suggesting so :sweat_smile:).

I wonder if a core developer perhaps accidentally enabled it for the repository or python organization? If so, I *think* you should be able to see it in one of:

- https://github.com/python/cpython/settings/installations
- https://github.com/organizations/python/settings/oauth_application_policy
- https://github.com/organizations/python/settings/installations
- https://github.com/organizations/python/settings/hooks

(GitHub has waaaay to many ways of managing integrations...)

Perhaps there are also more details about what's happend somewhere in https://github.com/organizations/python/settings/audit-log (no idea what to filter for, though).

**Comment by zware** [comment]
Just to give another data point, I have not been getting these emails.  The only mentions of Codacy that I can find in my email are this issue and a Hacktoberfest spammer trying to add configuration for it to the devguide.

**Comment by Mariatta** [comment]
As core developers we also don't have much ability to randomly install any app/integration on GitHub :) It has to be approved by an admin. 
I'm only seeing 3 integrations for CPython repo: Backhub, Codecov, and Travis CI. 😕

**Comment by The-Compiler** [comment]
Weird. No idea where this is coming from then, or why it started. Maybe Codacy support can say more. Closing this for now as it doesn't seem like there's anything you can do about this then... Thanks for the quick answers!

**Comment by methane** [comment]
I received same email.
Do you click the link in the mail?

In my case, the mail is from https://app.codacy.com/gh/stevenans9859/cpython/dashboard?branch=codacy-amN6znLRueK4Yky/pr/274

It is not python/cpython. It's a fork of it owned by @steven9859.
I think they enabled codacy for their fork.

I don't know why codacy send notification in this case though.

**Comment by The-Compiler** [comment]
Ah! I can confirm I'm also getting mails for the fork by @stevenans9859...

**Comment by Mariatta** [comment]
@stevenans9859 Can we kindly request that you disable Codacy on your fork of CPython? It is not something we use ourselves, and it is spamming other folks who did not sign up for it. Thanks.

**Comment by brandtbucher** [comment]
I've been getting them too.

> By default, Codacy will send an email to all users who contribute to a repo when there is an update on it, and all users who created at least one commit will be considered as contributors to the repo.

That must mean that there's thousands of these emails going out. For somebody's fork. What a horrible design.

**Comment by The-Compiler** [comment]
FWIW Codacy told me:

> I have also opened an internal bug to check if the email process is working as it should and if not, to fix it.

I'll let you know if I hear about anything new.
