### ISSUE TITLE
Give the bug triage permission to Hai Shi

### ISSUE THREAD

**Issue by vstinner** [python/core-workflow#385]
# Request for Python Triage membership

@shihai1991 is one of the most productive contributor to Python and I would like to give him more responsibility: bug triage permission. I'm already mentoring him through PR reviews, I plan to mentor him on bug triage as well.

|     | Description |
| --- | -------------------------- |
| GitHub username   | @shihai1991 |
| bpo username   | shihai1991     |
| Additional info   | recommended by @vstinner | |

**Comment by vstinner** [comment]
I just added the "Developer" role to https://bugs.python.org/user31412 but @shihai1991 should be added to the bug triage team of the Python project on GitHub as well.

**Comment by corona10** [comment]
@shihai1991 is a very active contributor.
IMHO, He has enough experience and contributions to deserve that permission.

**Comment by shihai1991** [comment]
Thanks for your guide(kinds of review and communication). :) @vstinner @corona10
And it's a nice experience to me.

**Comment by aeros** [comment]
Congrats @shihai1991! Definitely well deserved (I assumed that you already had the triage bit, which is always a good sign). :-)

As for adding to the GitHub org, I think that it requires an organization owner such as @benjaminp (not sure who else has permissions, I just recall Benjamin inviting me to the organization back when I was added to the GitHub Python triage team).

**Comment by vstinner** [comment]
It seems like @brettcannon is a maintainer of the https://github.com/orgs/python/teams/python-triage/members team. I requested to join.

I recall that @Mariatta wrote a script to add someone to this team, but I don't know how it works.

**Comment by brettcannon** [comment]
@vstinner you will need to ask PSF infrastructure to add @shihai1991 to the org first, then he can be added to the team by a maintainer like me. But when you ask to have @shihai1991 added to the org you can also ask he be added to the team at the same time.

**Comment by benjaminp** [comment]
Invitation sent.

**Comment by shihai1991** [comment]
Thanks, folks. I have joined in already :)

**Comment by Mariatta** [comment]
Awesome, welcome to the Triage team, @shihai1991.
