### ISSUE TITLE
Add "first contribution" label 

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#397]
GitHub announced a recent change where maintainers need to "approve" workflow runs for PRs from first-time contributors.

Article: https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/

Basically, before the CI would run on the PR, core devs need to first "approve" the workflow run, and just the workflow, not the whole PR. I have just came across this in one of the PR in CPython today.

Screenshot from GitHub article. https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

![image](https://user-images.githubusercontent.com/5844587/116701184-76da7800-a97c-11eb-9ac9-d1bdab69d7a0.png)

One of the issue is that we can't easily tell (visually) of PRs from first time contributors until we open the PR itself. It is not shown in the list of PRs web UI.

## Suggestion

I think we need to add a "first contribution" label to PRs from first time contributors.
Then we need to make the bot apply such label to the PR opened by first time contributors. There is a "membership" data that gets passed in the webhooks payload.

Perhaps there's an existing GH action that does this already? If not, it is easy to add to bedevere.

## questions

- What color do we want this label to be?
- If writing our own automation, do we do this in bedevere, or GH action?

**Comment by Mariatta** [comment]
Screenshot from https://github.com/python/cpython/pull/25702

It looks like only GitHub Action workflows are blocked and needing review. 🤔 
![Screenshot_20210430-092143](https://user-images.githubusercontent.com/5844587/116724537-a34ebe00-a995-11eb-9c6f-01b7c02e55c0.png)

**Comment by terryjreedy** [comment]
Who makes label: whatever is easier to do and maintain?

Color: the 'awaiting' orange, similar to 'caution' road signs, or something close.

One GHA: ask GH about this.  They only care abut *their* resources?  Anyway, we would not want to have separate buttons for other CI providers.

**Comment by brettcannon** [comment]
There's a bunch of GitHub Actions we can either pick from or get inspiration for: https://github.com/marketplace?type=actions&query=first+pull+request

**Comment by brettcannon** [comment]
Except Bedevere is supposed to be moving to GitHub Actions for easier maintenance.

**Comment by Safihre** [comment]
Can I suggest to change the setting to only require approval for new GitHub accounts and not for all first-time contributors?
That was added a few months ago by GitHub.

![image](https://user-images.githubusercontent.com/5703454/158342095-3a4640be-0814-460f-a716-d398bbbf93f2.png)

**Comment by ezio-melotti** [comment]
I changed the setting to `Require approval for first-time contributors who are new to GitHub`, so I'm going to close this issue.  If you think it needs further discussion or a different solution, please reopen.
