### ISSUE TITLE
Move the devguide to Read the Docs

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#4]
Either redirect to http://cpython-devguide.readthedocs.io/, or make http://cpython-devguide.readthedocs.io/ be dev.python.org and redirect there.

**Comment by Mariatta** [comment]
What needs to be done in order to move python docs to Read the Docs?

**Comment by brettcannon** [comment]
1. Decide whether we are going to do a subdomain, and if so what that name is and then setting it up.
2. Set up a redirect for docs.python.org/devguide to the new subdomain.

**Comment by brettcannon** [comment]
OK, let's move this discussion forward. First up: vote on where the docs should live. Vote appropriately.

**Comment by brettcannon** [comment]
dev.python.org

**Comment by brettcannon** [comment]
devguide.python.org

**Comment by brettcannon** [comment]
developer.python.org

**Comment by brettcannon** [comment]
cpython-devguide.readthedocs.io (i.e. no subdomain)

**Comment by matrixise** [comment]
@brettcannon a subdomain of `python.org` is better because more official. (IMHO)

**Comment by brettcannon** [comment]
@matrixise yep, and I'm already working on getting devguide.python.org created for us.
