### ISSUE TITLE
How to import my cherry_picker script to here while maintaining full commit history?

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#40]
Since @ncoghlan has started contributing to it as well, I'd like to keep the history intact if possible :)

**Comment by brettcannon** [comment]
I don't think there is a way unless you want to simply create a separate repo under the python org? Otherwise you would have to "replay" every commit.

**Comment by brettcannon** [comment]
So I'm going to close this, but if you want to create a separate repo that's also fine.

**Comment by Mariatta** [comment]
Ok.. in that case I just need to fork my repo to python, right?

**Comment by brettcannon** [comment]
I need to create you a Python repo and you can then push your git repo that and the history will just carry over.

And to create that repo I need a name.

**Comment by Mariatta** [comment]
I'm not well versed in finding references to Monty Python sketches.
So `chic_a_cherry_picker` unless someone can suggest a better name.

**Comment by vadmium** [comment]
I’m not sure where you want your script added, but Git can merge independent histories together. You just get a merge commit on top of the existing commits plus the commits from the external repository. If the files or trees are in the wrong place, you can rename them before or after the merge. IMO this would be better than “replaying every commit”.

**Comment by brettcannon** [comment]
Actually, now that I think about it, there are essentially no important files in this repo. So if you simply made sure your repo had appropriate README, LICENSE, and .gitignore for this repo you could force-push on to this repo and just have your changes be carried over. Or if @vadmium 's idea works that's another way.

Or @ncoghlan might not simply care about tracking his contributions and all of these machinations are unnecessary. 😄

**Comment by brettcannon** [comment]
As for a name, `cherry_picker.py` is fine by me (I know the reference for the `chic_a` part of the name).

**Comment by ncoghlan** [comment]
While I don't personally mind losing the commit history (I'll just hold off on updating the `--dry-run` PR until after the migration), looking at https://saintgimp.org/2013/01/22/merging-two-git-repositories-into-one-repository-without-losing-file-history/ it seems the process of merging would be to add @Mariatta's cherry picker repository as a remote to a core-workflow checkout, and then merge master from chic_a_cherry_picker to master in the core-workflow checkout. In essence, git would treat the "cherry_picker_remote/master" branch like any other feature branch, even though it doesn't have a common root commit.

Giving `cherry_picker` its own subdirectory prior to the merge would also let it retain its own README separate from the top-level one for the core-workflow repo as a whole.

**Comment by brettcannon** [comment]
Using the trick @ncoghlan lists with a subdirectory SGTM.

**Comment by Mariatta** [comment]
ok I think I did it 😅 
https://github.com/python/core-workflow/tree/master/cherry_picker

These were the commands I use.. for historical purpose:
```
git clone git@github.com:python/core-workflow.git
cd core-workflow/
git remote add cherry_picker git@github.com:Mariatta/chic_a_cherry_picker.git
git fetch cherry_picker
mkdir ./cherry_picker
git -C ./cherry_picker/ pull cherry_picker master --allow-unrelated-histories
git mv cherry_picker.py ./cherry_picker/
git mv requirements.txt ./cherry_picker/
git mv readme.rst ./cherry_picker/
# removed the license from my repo, keeping the original core-workflow license.
git rm LICENSE.txt  
```
committed and pushed to master 😱
