### ISSUE TITLE
Request for Python Triage membership: Erlend Aasland 

### ISSUE THREAD

**Issue by corona10** [python/core-workflow#402]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @erlend-aasland  |
| bpo username   | erlendaasland     |
| Additional info   |  [50+ commits](https://github.com/python/cpython/commits?author=erlend-aasland&before=f4013eba41967e294a7ca5cf71d343b4be390d64+35) in CPython project |
| Recommended by    |  @corona10  |

I am very happy to introduce @erlend-aasland to suggest him as the Python triage member.
In recent months, he has been improving a lot of parts of the SQLite module and also participated in several Python C API discussions :)
I believe that he can enhance the SQLite module for the future Python and his activity shows that he well deserves to get more responsibility.

**Comment by zware** [comment]
:+1:!

I've granted the Developer role on bpo.

**Comment by corona10** [comment]
@Mariatta Can we invite @erlend-aasland to the Github Python triage team?

**Comment by corona10** [comment]
@zware 
> I've granted the Developer role on bpo.

Thank you :)

**Comment by ewdurbin** [comment]
Invitation sent.

**Comment by erlend-aasland** [comment]
Thank you all! Looking forward to contributing as a triage member.

**Comment by corona10** [comment]
@Mariatta @ewdurbin 
Thank you for helping with this issue :)

Looks like all needed tasks are done!
