### ISSUE TITLE
Request for Python Triage membership: Filipe Laíns

### ISSUE THREAD

**Issue by jaraco** [python/core-workflow#406]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @FFY00 |
| bpo username   | [FFY00](https://bugs.python.org/issue?%40search_text=&ignore=file%3Acontent&title=&%40columns=title&id=&%40columns=id&stage=&creation=&creator=&activity=&%40columns=activity&%40sort=activity&actor=&nosy=FFY00&type=&components=&versions=&dependencies=&assignee=&keywords=&priority=&status=1&%40columns=status&resolution=&nosy_count=&message_count=&%40group=&%40pagesize=50&%40startwith=0&%40sortdir=on&%40queryname=&%40old-queryname=&%40action=search)     |
| Additional info   | Filipe has been contributing substantially to CPython through code, triaging, discussion, and shepherding PRs ([link](https://github.com/python/cpython/search?q=ffy00&type=issues)). In addition to core contributions, Filipe has been aiding with triage and enhancements on the `importlib_*` backports. |

**Comment by zware** [comment]
Developer role has been granted on bpo.  Welcome, Filipe :)

**Comment by FFY00** [comment]
Thank you :blush:

**Comment by Mariatta** [comment]
Sounds great!

Can someone from @python/infrastructure-staff add @erlend-aasland to the Python Triage Team please?

Thanks.

**Comment by ewdurbin** [comment]
hmmm, did you mean to request to add @FFY00?

**Comment by ewdurbin** [comment]
As @erlend-aasland is already on the triage team, and this issue is clearly for @FFY00, an invitation has been dispatched for @FFY00.

**Comment by Mariatta** [comment]
Ahh sorry for writing the wrong username. Thanks for taking care of this @ewdurbin! Welcome to the triage team, @FFY00.
