### ISSUE TITLE
berkerpeksag/cpython-bpo-linkify link on readme is dead

### ISSUE THREAD

**Issue by Bonifacio2** [python/core-workflow#408]
# The short story

It would be nice if... it wasn't.

**Comment by Mariatta** [comment]
Hmm, not sure what happened to it. cc @berkerpeksag

**Comment by zware** [comment]
I think it was rendered obsolete by GitHub allowing us to set our own link prefix for `bpo-`.

**Comment by Mariatta** [comment]
Has it been completely turned off then? Would be great to be notified about this kind of stuff in the future.

**Comment by berkerpeksag** [comment]
> I think it was rendered obsolete by GitHub allowing us to set our own link prefix for `bpo-`.

True, and it has never worked properly for non-Chrome browsers. As far as I remember, I was the only user of the extension at the time :) I'll remove the link.

**Comment by berkerpeksag** [comment]
Thanks for the report!
