### ISSUE TITLE
CLA signatura performed but not working

### ISSUE THREAD

**Issue by Leonardofreua** [python/core-workflow#411]
I signed the CLA on July 15th, went through the whole process, and received the signed document by email with the subject **You signed: "Contributor Agreement 2020-09-23"** (this date in the subject looks strange!). But it still appears as **CLA not signed** on GitHub and on the site https://check-python-cla.herokuapp.com/ it also appears as if I had not signed.

Do I need to do any other procedure after signing the file?

**Comment by Mariatta** [comment]
I have just checked your CLA on the heroku app, and it seems to work fine. Your PR now has the CLA signed label. Perhaps just needed to wait.

**Comment by Leonardofreua** [comment]
Thanks, Mariatta.

Moments before opening this issue I had tried and it didn't work.

But I'm glad it worked, thank you very much.

**Comment by terryjreedy** [comment]
Completion of the process requires a manual step, not done on weekends.  It apparently did not happen Friday, so today, Monday.  In any case, welcome.

**Comment by Leonardofreua** [comment]
Understood. Thank you again and sorry for the inconvenience.
