### ISSUE TITLE
Request for Python Triage membership: Dennis Sweeney

### ISSUE THREAD

**Issue by zware** [python/core-workflow#412]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @sweeneyde |
| bpo username   | Dennis Sweeney     |
| Additional info   | ~25 merged patches, active on Discourse and mailing lists, appears to already be following new issues | |

**Comment by zware** [comment]
I've added the Developer role on bpo, could @python/infrastructure-staff please add @sweeneyde to the triage team?

**Comment by ewdurbin** [comment]
Invite dispatched.

**Comment by zware** [comment]
Thanks, Ee!
