### ISSUE TITLE
Request for Python Triage membership: Yurii Karabas

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/core-workflow#413]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @uriyyo |
| bpo username   | uriyyo |
| Additional info   | Yurii is very versatile and has worked on various parts of asyncio, typing, and the compiler. He's dealt with tricky C and Python code, and I appreciate him helping us out to clear our issue backlog for typing.|

I have emailed him to ask for his permission. He understands the additional triage responsibilities and is excited to take them on.

**Comment by zware** [comment]
Developer role granted on bpo; welcome to triage, @uriyyo :)

Could @python/infrastructure-staff please invite @uriyyo to the triage team?

**Comment by ewdurbin** [comment]
Invite sent.

**Comment by uriyyo** [comment]
@ewdurbin Invite accepted.

Thank you all💫

**Comment by Fidget-Spinner** [comment]
Thanks Zach and Ee for handling this. Much appreciated!
