### ISSUE TITLE
Request for Python Triage: Alex Waygood

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/core-workflow#416]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @AlexWaygood|
| bpo username   | AlexWaygood|
| Additional info   | Recommended by me and @zware. Alex has improved large chunks of our docs, and he's branching out to code in other parts of the stdlib. He's also very active in the python/typeshed repository. Though new, I'm confident he will put his triage abilities to good use. |

**Comment by ambv** [comment]
I concur, Alex's doing good work. I sent him an invite to the Triage team.

**Comment by ambv** [comment]
Invite accepted. Some member of the Triage team could then close this issue, right @AlexWaygood?

**Comment by AlexWaygood** [comment]
> Invite accepted. Some member of the Triage team could then close this issue, right @AlexWaygood?

It would appear so! Thanks so much everybody, really excited to be joining the team 😀

**Comment by zware** [comment]
Added the Developer role on bpo, welcome @AlexWaygood!

**Comment by AlexWaygood** [comment]
> Added the Developer role on bpo, welcome @AlexWaygood!

Thank you!
