### ISSUE TITLE
Request for Python Triage membership: Hugo van Kemenade

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#417]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @hugovk |
| bpo username   | hugovk     |
| Additional info   | 19 merged PRs in CPython, helps review others' PRs in CPython, bpo, devguide, PEPs, etc |

**Comment by Mariatta** [comment]
I'm recommending Python Triage privileges for @hugovk. I have granted the **Developer** role on b.p.o. Could someone from @python/infrastructure-staff be able send the invite to the GitHub Python Triage team?

Thanks.

**Comment by ewdurbin** [comment]
Invitation sent.

**Comment by Mariatta** [comment]
Thanks!

**Comment by hugovk** [comment]
Invitation accepted, thank you!
