### ISSUE TITLE
Triage team members cannot edit PR title

### ISSUE THREAD

**Issue by hugovk** [python/core-workflow#418]
# The short story

Looks like a GitHub permission is missing for Python triage team members.

# Long version

https://devguide.python.org/triaging/#python-triage-team says responsibilities include "Renaming PRs".

However, I don't see the Edit button next to PRs at https://github.com/python/cpython or this repo.

Am I missing something or is an extra permission needed? Or if GitHub's settings aren't granular enough, shall we remove this bullet point from the devguide?

**Comment by brettcannon** [comment]
Consider the devguide wrong; GitHub permissions are not granular to what the level does, just what level a person is at.
