### ISSUE TITLE
Request for Python Triage membership: Nikita Sobolev

### ISSUE THREAD

**Issue by corona10** [python/core-workflow#422]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @sobolevn |
| bpo username   | sobolevn     |
| Additional info   |  [42+ commit](https://github.com/python/cpython/commits?author=sobolevn) in CPython project & [113+ commit](https://github.com/python/mypy/commits?author=sobolevn) in mypy project |
| Recommended by    |  @corona10  |

I am very happy to introduce @sobolevn to suggest him as the Python triage member.
Last few months, I've observed his activity to the CPython project and he submitted well-valued patches.
From my view, he looks already familiar with what the CPython project wants and how we handle CPython issues.
So I think that it's time to give triage permission to @sobolevn. 
Moreover, he is very active at the mypy project and it will make a synergy to CPython activity too :)
I am going to mentor the Triage permission for 4 weeks.

**Comment by sobolevn** [comment]
I am not sure if this matters, but I also try to improve [`typeshed`](https://github.com/python/typeshed/pulls/sobolevn) (~70 commits at the moment) when I can 🙂 

Thanks a lot for this proposal! 👍

**Comment by zware** [comment]
Developer role added on bpo.  Welcome, @sobolevn!

**Comment by corona10** [comment]
Now waiting for Github invitation by @ewdurbin :)

**Comment by Fidget-Spinner** [comment]
@sobolevn is doing great work and I vouch for him too! Thank you Dong-hee for mentoring him for the triage role for the next 4 weeks.

**Comment by ewdurbin** [comment]
Invite sent.

**Comment by sobolevn** [comment]
Thanks everyone! I am going to work hard to serve CPython and its users 😊
