### ISSUE TITLE
Should triage team members be allowed to "Approve GitHub Actions workflow run"?

### ISSUE THREAD

**Issue by sobolevn** [python/core-workflow#423]
Let's take this PR as an example: https://github.com/python/cpython/pull/30493

A developer pushes some valid patch to CPython. But, no one from triage team can authenticate the GitHub Actions run. 

<img width="916" alt="Снимок экрана 2022-01-10 в 18 00 21" src="https://user-images.githubusercontent.com/4660275/148787688-f1b3bfd6-8e34-4e23-9b1b-ca7799872bbf.png">

This leaves new contributors to wait longer and requires some attention from core-devs, wasting their time.

Maybe triagers should be able to do that? 🤔

**Comment by hugovk** [comment]
https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork says:

> Maintainers with write access to a repository can use the following procedure to review and run workflows on pull requests from contributors that require approval.

So sounds like only those with write access can approve it => only core devs.

**Comment by zware** [comment]
To answer the question in the title: ideally, yes.  However, as far as I know GitHub's permissions structure is not granular enough for us to have control over that, so I'm unfortunately just closing the issue.

If there's somewhere to request this from GitHub, please do :)

**Comment by sobolevn** [comment]
> If there's somewhere to request this from GitHub, please do :)

I have a direct access to GitHub feature request, consider it done! 👍
