### ISSUE TITLE
Mark generated files with custom `generated` git diff driver

### ISSUE THREAD

**Issue by erlend-aasland** [python/core-workflow#425]
In `.gitattributes`, add `diff=generated` to generated files so one conveniently can configure `git diff` to ignore them, for example by marking them as "binary files" (`git config diff.generated.binary true`). This should not impact how GitHub renders such diffs.

Suggestion stolen from @zware on Discord :sunglasses:

**Comment by erlend-aasland** [comment]
See also:
- https://git-scm.com/docs/diff-config
- https://git-scm.com/docs/gitattributes

**Comment by isidentical** [comment]
If someone takes over, here is a prepared list from a year back. Probably it got changed a lot, but might be useful base https://github.com/python/cpython/pull/20314

**Comment by erlend-aasland** [comment]
See also https://bugs.python.org/issue40729

**Comment by zware** [comment]
Done in python/cpython#30745.
