### ISSUE TITLE
Renaming labels on `python/cpython`

### ISSUE THREAD

**Issue by ezio-melotti** [python/core-workflow#432]
Some labels of the `python/cpython` repo should be renamed either before or after the migration:
* `type-enhancement` -> `type-feature` (this has been updated by Guido already)
* `type-bugfix` -> `type-bug`
* `type-documentations` -> `docs`
* `type-tests` -> `tests`
* `type-performance` -> `performance`

[This post](https://discuss.python.org/t/github-issues-migration-label-mapping/14212) has some more background, but there are two main things that are relevant for this issue:
1. making sure there aren't any tools (e.g. bots, actions, etc.) that depend on these specific names and will break if we change them;
2. making sure that the names match during the migration, or we will end up with two different spellings for the same label;

Labels can be easily renamed before or after the migration, so if you prefer different names you can comment on the post linked above.  We can also migrate with these names and updated them later, the only issue is that `type-bugfix` will look weird on issues, so if we could rename that either before or shortly after the migration it would be better.  Please let me know if you want to update any of those labels, so that I can make sure that the same name is used during the migration.

Do you know anything that depends on those names?

(cc: @Mariatta, @brettcannon)

**Comment by Mariatta** [comment]
Bedevere relies on those types, so we may need to update it.

https://github.com/python/bedevere/blob/master/bedevere/prtype.py

**Comment by Mariatta** [comment]
PR created at bedevere to make use of the new labels.
https://github.com/python/bedevere/pull/419
