### ISSUE TITLE
Enable and document use of the GitHub "Always suggest updating pull request branches" option

### ISSUE THREAD

**Issue by ned-deily** [python/core-workflow#434]
It has been suggested on the Python Core Devs Discord that we should enable the newish GitHub repo option to always suggest updating pull request branches when they are out-of-date when the current branch head. That would simplify the PR contribution experience in the not infrequent case when a PR CI job fails due to some unrelated change that has been subsequently fixed.  As an experiment, I've already enabled it for cpython after some discussion on Discord and it does seem to be useful. If we want to make that a permanent change, we should announce it to the developer community and add something to the devguide.

![image](https://user-images.githubusercontent.com/5833005/160463296-c5fc80f4-6525-4f00-9366-d93a4e051512.png)

**Comment by ned-deily** [comment]
Pinging admins and other release managers. @brettcannon @Mariatta @pablogsal @ambv

**Comment by brettcannon** [comment]
Someone beat me to it!

**Comment by ned-deily** [comment]
@brettcannon Beat you to what ? :)  I changed the setting on the repo before opening the issue. I opened the issue to make sure we had consensus that it was the right thing to do and then, if so, announce it and document it in the devguide. Or do you think that none of that is necessary?
