### ISSUE TITLE
Use issue templates for `python/cpython`

### ISSUE THREAD

**Issue by ezio-melotti** [python/core-workflow#437]
After the migration, we could use issue templates on the `python/cpython` repo.

When the user clicks on the green "New Issue" button, we could present a few options ([like this repo does](https://github.com/python/core-workflow/issues/new/choose)):
* Propose a new feature or enhancement
* Report a bug
* Report a crash
* Report a security issue
* Visit the documentation

The first four provide a first level of triaging, by determining the *type* of issue.  The last two can be links to the [security policy page](https://github.com/python/cpython/security/policy) (or something equivalent) and a Devguide section about reporting bugs.  Each of them should have a description to clarify when to use them.  An additional link to python-ideas could be added too.

It is also possible to create [templates that use forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms), with dropdowns and textareas that can be filled by the user.

If we do this, we could have a few dropdowns for
* The affected area:  library/tests/documentation/interpreter-core/extension-modules/not-sure
* Python version: 3.7/3.8/3.9/3.10/3.11, possibly also options for branches in security/bug fixes/features mode
* Operating system: all/Linux/MacOS/Windows/others

A few other considerations:
* We could have a single template, with the "issue type" selection being another dropdown
* We could disable free-form issues and enforce the use of templates
* We should make clear that the version/os refer to the ones where the behavior has been observed by the user, and not necessarily all the affected targets
* We should be able to automatically set some labels depending on the selections made by the user
* We could also make the form simpler (or avoid using it altogether) and skip the dropdowns, making reporting easier and triaging more difficult (but possibly more accurate)

I still have to play around more with issue templates to better understand the extent of their capabilities, and I'm open to more ideas and feedback, especially from people that have related experience on other repos.

**Comment by ezio-melotti** [comment]
If we start using templates, we should also include a link to python-ideas among the options.  I already saw a few reports proposing ideas (e.g. python/cpython#91509 and python/cpython#91540).

**Comment by AlexWaygood** [comment]
I'd support issue templates, and I think we should implement them with some urgency. There's been a particularly large increase in issues  proposing radical syntax changes, as well as issues from beginners seeking user help. As well as the ones you've already pointed out, there's also been:

- https://github.com/python/cpython/issues/91473
- https://github.com/python/cpython/issues/91440
- https://github.com/python/cpython/issues/91460

The fact that filers of issues can't (without issue templates) add their own labels (like they could on BPO) also increases the triaging burden for each new issue.

**Comment by hugovk** [comment]
@AlexWaygood re: urgency, would you like to PR up some basic templates? 

We could merge that sooner to help steer people in the right direction. 

And then iterate to get all the neat dropdowns and  so on in Ezio's post.

**Comment by AlexWaygood** [comment]
> @AlexWaygood re: urgency, would you like to PR up some basic templates?
> 
> We could merge that sooner to help steer people in the right direction.
> 
> And then iterate to get all the neat dropdowns and so on in Ezio's post.

Yup, sounds good — I'll try to send a PR today!

**Comment by AlexWaygood** [comment]
- https://github.com/python/cpython/pull/91569

**Comment by ezio-melotti** [comment]
The template added by @AlexWaygood in https://github.com/python/cpython/pull/91569 seems to be working well, so I think this can be closed.  Should the need arise to improve upon what we have, a new issue can be opened.
