### ISSUE TITLE
Request for Python Triage membership: Kumar Aditya

### ISSUE THREAD

**Issue by gvanrossum** [python/core-workflow#438]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @kumaraditya303 |
| bpo username   | kumaraditya |
| Additional info   |  [many CPython GitHub commits](https://github.com/python/cpython/commits?author=kumaraditya303) |
| Recommended by | @gvanrossum |

I have watched @kumaraditya303's activity over the past months and mentored him on numerous code reviews in areas from performance improvements to documentation. He is very interested in becoming a triager and I am convinced that he will do a good job and be a great addition to the our project.

@kumaraditya303, if you have any additional info about your activities and aspirations, now would be the time to add them below.

**Comment by zware** [comment]
Developer role added on bpo; we'll need @python/infrastructure-staff to invite to the triage group.

Welcome, @kumaraditya303!

**Comment by ewdurbin** [comment]
Invitation sent.

**Comment by Fidget-Spinner** [comment]
Congrats @kumaraditya303 !
