### ISSUE TITLE
Avoid running tests for changes in `.github/*`

### ISSUE THREAD

**Issue by ezio-melotti** [python/core-workflow#442]
I noticed (in python/cpython#91590) that the test suite is run even for changes to files in `.github/*`.
Unless maybe for `.github/workflows`, it shouldn't be necessary to run the whole test suite for changes to other files.

**Comment by TeamSpen210** [comment]
According to python/cpython#84728 it has to run, so it can complete and allow merging. So instead the folder would need to be added [here](https://github.com/python/cpython/blob/4e661cd69164318c1f871faa476c68a04092ddc4/.github/workflows/build.yml#L53) to skip the actual execution in this case?

**Comment by ezio-melotti** [comment]
> So instead the folder would need to be added [here](https://github.com/python/cpython/blob/4e661cd69164318c1f871faa476c68a04092ddc4/.github/workflows/build.yml#L53) to skip the actual execution in this case?

From a quick look it seems that might be enough, but I'm not too familiar with that workflow.  @vstinner, what do you think?

Also note that [the original thread linked in one of the messages](https://github.community/t/feature-request-conditional-required-checks/16761/14) has received more replies and now links to a couple of GH actions that might be useful.

**Comment by hugovk** [comment]
> Unless maybe for `.github/workflows`

Yes, let's keep running for these: we want to know that changes to CI config doesn't break the build :)

**Comment by vstinner** [comment]
>  Unless maybe for .github/workflows, it shouldn't be necessary to run the whole test suite for changes to other files.

Changing ``.github/workflows/build.yml`` or ``.github/workflows/doc.yml`` can likely break the CI if a bug is introduced. I wouldn't call this wasting CI resources. Changing ``.github/`` is rare.

I close the issue.
