### ISSUE TITLE
Request for Python Triage membership: @hauntsaninja

### ISSUE THREAD

**Issue by JelleZijlstra** [python/core-workflow#443]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @hauntsaninja |
| bpo username   | hauntsaninja     |
| Additional info   |  Already a maintainer for typeshed, typing, typed-ast; ~30 CPython PRs |

I have worked with @hauntsaninja for a long time and have a lot of confidence in him. He is a maintainer on several typing-related projects and has also contributed to CPython.

**Comment by hauntsaninja** [comment]
Thank you for nominating me! 

Other contributions of mine within the Python Github org include:
- Authored 725 commits within the Python org, 28 in CPython: https://github.com/search?q=org%3Apython+author%3Ahauntsaninja+is%3Apr&type=commits
- Participated in about 2000 issues and PRs within the Python org: https://github.com/search?q=org%3Apython+commenter%3Ahauntsaninja&type=Issues
- I help maintain the mypy type checker

**Comment by isidentical** [comment]
I've worked with @hauntsaninja on python/cpython#19612 (a fairly non-trivial PR) and the overall experience was great and reactive. Definietly a +1 from me as well.

**Comment by benjaminp** [comment]
invited

**Comment by brandtbucher** [comment]
Congrats @hauntsaninja!

It was nice to finally meet you this week, and I look forward to working with you even more in the future.
