### ISSUE TITLE
Request for Python Triage membership: @slateny

### ISSUE THREAD

**Issue by iritkatriel** [python/core-workflow#444]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @slateny |
| bpo username   | slateny     |
| Additional info   |  _"recommended by @iritkatriel"_| |

**Comment by AlexWaygood** [comment]
+1. @slateny's been doing a sterling job on docs issues. From what I've seen, their PRs are always careful and considered, and they've consistently been willing to take feedback on board when it's offered.

**Comment by zware** [comment]
@python/infrastructure-staff, I think the only step these days is an invite to the `python/python-triage` group.

I no longer have power to help these along, but support the promotion :)

**Comment by JelleZijlstra** [comment]
While you're at it, please do this for @hauntsaninja too (#443).

**Comment by benjaminp** [comment]
invited both
