### ISSUE TITLE
Request for Triage membership for Docs-Community members

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#445]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @pradyunsg |
| Additional info   | For docs review and triage |

Today in [Docs community monthly meeting](https://github.com/python/docs-community/pull/51/files) we discussed of adding the members of the docs-community and to give them triage permissions to the CPython repo. This will allow them to help review and triage docs related PRs in the CPython repo.

The plan is to allow the docs community members to review and approve the docs related PR, and potentially add the "docs-approved" label. Once the docs community member has reviewed the PR, a core developer can then merge such PR. 

In the meeting, we also wanted to grant the triage privileges to @cam-gerlach and @aa-turner. Since both Cam and Adam are already in the Python org (as PEP editors), I've gone ahead and given the Python triage membership to them.

Update: We want to grant the Triage role to @nedbat as well since he's part of the docs community and editorial group. I have gone ahead and add Ned to the Triage team. So we just need to add Pradyun.

**Comment by Mariatta** [comment]
@python/infrastructure-staff Would one of you be able to add @pradyunsg to the Python Triage Team please?

Thank you.

**Comment by ezio-melotti** [comment]
Done.
