### ISSUE TITLE
Request to transfer bpo triage membership for josh.r to GitHub @MojoVampire

### ISSUE THREAD

**Issue by MojoVampire** [python/core-workflow#446]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @MojoVampire |
| bpo username   | josh.r     |
| Additional info   | already a bpo triager, having made several PRs and triaged a few dozen issues on bpo| |

**Comment by Mariatta** [comment]
Sounds great. Thanks for your contributions! Since you're already a bpo triager it makes sense to add you to the Python triage team.
@python/infrastructure-staff please add @MojoVampire to the Python Triage Team. Thanks.

**Comment by ezio-melotti** [comment]
Done.
