### ISSUE TITLE
Request for Python triage membership: carljm

### ISSUE THREAD

**Issue by JelleZijlstra** [python/core-workflow#448]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @carljm |
| bpo username   | carljm     |
| Additional info   | Author of PEP-405, PEP-438, PEP-690; previous maintainer of pip and virtualenv; Django core team member; several contributions to CPython |

Carl reached out to me because he is interested in helping out with CPython. He works on Static Python at Instagram and has a ton of experience with the language.

**Comment by JelleZijlstra** [comment]
@Mariatta could you add Carl to the triage team? He is already a member of the Python org.

**Comment by Mariatta** [comment]
Yes, done. Thanks, and welcome @carljm to the team!

**Comment by JelleZijlstra** [comment]
Thank you!

**Comment by carljm** [comment]
Thanks @Mariatta and @JelleZijlstra !
