### ISSUE TITLE
Consider how to handle failed cherry-picks

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#45]
_From @ncoghlan on March 12, 2017 4:57_

I think this utility has a lot of potential to evolve into the bot that actually does the automated cherry-pick PR creation, and one of the things we'll need to address there is what to do when the routine cherry pick fails.

At the moment, if the first cherry-pick fails, it leaves the checkout in a messy state, so all the subsequent branch creation commands fail.

I'm thinking one way of tackling this would be to:

Complain and exit early if the checkout is in a messy state, and suggesting running git stash to move the local changes aside.
If any of the cherry-picks fail do an immediate git reset --hard and move on to the next branch.
Does that approach sound reasonable?

_Copied from original issue: Mariatta/chic_a_cherry_picker#15_

**Comment by ncoghlan** [comment]
https://github.com/python/core-workflow/issues/51 points out that for the interactive use case, dropping the user into the failed cherry-pick directory with a printed command on:

* how to finish the current cherry-pick
* how to resume any other not-yet-attempted cherry-picks

**Comment by serhiy-storchaka** [comment]
Would be nice if `cherry_picker.py` be allowing to fix errors manually and continue its work when run with `--continue`. Running with `--abort` should abort the current conflict resolution process, reset the workspace and delete just created branch.

**Comment by Mariatta** [comment]
Thanks @serhiy-storchaka . I started working on handling errors in cherry_picker.py see #57 
I implemented the interactive mode where it will ask the user of how to proceed.
But if we want it as ``--continue`` or ``--abort`` options, it can be done.

**Comment by ncoghlan** [comment]
The `--continue`/`--abort` approach would align nicely with the way git's own commands work, so +1 from me for that approach.

**Comment by Mariatta** [comment]
Please check if https://github.com/python/core-workflow/pull/65 does what's expected. Thanks :)
