### ISSUE TITLE
CPython notify-new-bugs-announce workflow fails for long issue body

### ISSUE THREAD

**Issue by The-Compiler** [python/core-workflow#456]
Reporting this here after https://github.com/psf/gh-migration/issues/7#issuecomment-1138318122

I just got a mail from GitHub telling me that the workflow failed after I opened an issue:

https://github.com/python/cpython/issues/93249
https://github.com/python/cpython/runs/6606492855?check_suite_focus=true

Due to:

```
[Error: Bad Request] {
  status: 400,
  details: 'Send options (parameters starting with o:, h:, or v:) are limited to 16 kB total'
}
```

I suppose it should truncate long issue bodies (there's a big C stacktrace hidden in a `<details>` in there).

**Comment by hugovk** [comment]
Hopefully fixed in https://github.com/python/cpython/pull/106329, thanks @sobolevn.
