### ISSUE TITLE
Shut down Zulip

### ISSUE THREAD

**Issue by ezio-melotti** [python/core-workflow#457]
Since [Zulip](https://python.zulipchat.com/) never caught on and we are now using Discourse/Discord, we could shut it down and remove its mentions from the Devguide and elsewhere.

Before pulling the plug, we should:
* check if any stream is still active (none of the ones I followed are), and announce the shutdown;
* check what other pages (e.g. the Devguide) point to Zulip so that they can be updated/removed;
* review if there is any significant thread that we might want to preserve/export.

**Comment by hugovk** [comment]
Please see PR https://github.com/python/devguide/pull/1001 to remove Zulip references from the devguide.

**Comment by hugovk** [comment]
> * check if any stream is still active (none of the ones I followed are), and announce the shutdown;

There's very little activity, what little there is, is people asking for help and not getting it. See screenshots in https://github.com/python/devguide/pull/1001. There are better forums to get help.

> * check what other pages (e.g. the Devguide) point to Zulip so that they can be updated/removed;

Searching https://github.com/python repos: https://github.com/search?q=org%3Apython%20zulip&type=code

* [x] Reference to the Zulip blog, not our Zulip chat, can stay: https://github.com/python/mypy/blob/7da2abf9a5a05fffc3d07caef31681c50bc9d6e7/docs/source/getting_started.rst#L445
* [ ] Reference in PEP 581, update or leave? https://peps.python.org/pep-0581/#downsides-of-github
* [x] Devguide reference, removed in https://github.com/python/devguide/pull/1001
* [x] SC minutes about plan to shut it down. Can stay: https://github.com/python/steering-council/blob/04bde3ca9f0760ffa4dcd77c794e1b8c7911790c/updates/2020-01-06-steering-council-update.md?plain=1#L19
* [ ] Mention in Spanish docs CoC, can be removed
* [ ] Reference in PEP 101 checklist, removed in https://github.com/python/peps/pull/2918
* [ ] Reference in PEP 595, update or leave? https://github.com/python/peps/blob/53cdf55b7d7f6ac09ae79f236472fb90a770411a/pep-0595.rst#L427

**Comment by JelleZijlstra** [comment]
I don't think we need to change the references in PEPs 581 and 595, those are just historical. It's a bit sad if the links stop working but probably not worth the bother to try to fix.

**Comment by hugovk** [comment]
* PR to update the Spanish CoC: https://github.com/python/python-docs-es/pull/2240
* PSF CoC: https://www.python.org/psf/conduct/

(Both added to checklist above)

**Comment by arhadthedev** [comment]
Is there anything left before the actual shutdown?

**Comment by hugovk** [comment]
The reference in the PSF CoC should be removed, but that's not a blocker for shutdown.

**Comment by zware** [comment]
It appears that I have the power to `Deactivate organization` on Zulip; are we ready to go ahead with that?  It's not undo-able without help from Zulip support.

**Comment by pradyunsg** [comment]
I’d say we announce that this is happening, give people a day/week to act on it, and then shut this down?

For me personally, I’d like to check and see if there’s information in the chats around the pip resolver project that I wanna move into my personal notes. :)

**Comment by hugovk** [comment]
Sounds like a plan. Shall we say either two weeks or a month, to give plenty of time (we're not in a rush), and then post on Discuss?

**Comment by CAM-Gerlach** [comment]
A month sounds good. It should also be posted on the Zulip itself, if anyone still has access.

**Comment by zware** [comment]
Announced: https://python.zulipchat.com/#narrow/stream/116406-announce/topic/Shutdown.20imminent/near/327902501

**Comment by hugovk** [comment]
Thanks, please could you post it on https://discuss.python.org/ as well?

**Comment by zware** [comment]
[Done.](https://discuss.python.org/t/notice-python-zulip-instance-shutdown-imminent/23917)

**Comment by CAM-Gerlach** [comment]
NB, its been a good bit over a month/30 days now, so is it time to finally shut it down?

**Comment by zware** [comment]
python.zulipchat.com has been deactivated.

**Comment by Mariatta** [comment]
I saw that we have a webhooks set up on the CPython repo to zulip. I've deactivated that.
