### ISSUE TITLE
Drop the gcc build from Travis

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#46]
We currently have 5 builds on Travis:

1. clang
2. gcc
3. C++ header compatibility
4. docs
5. code coverage

I'm not willing to drop 1, 4, or 5. Perhaps we should drop the gcc build as redundant next to clang and let any gcc buildbots acts as our fallback in case we hit a weird compatibility issue?

**Comment by brettcannon** [comment]
This would make @1st1 happy. 😉

**Comment by methane** [comment]
I think 3 can be merged into 1 easily, too.

**Comment by brettcannon** [comment]
I created python/cpython#697 to try out the 1+3 idea.

**Comment by brettcannon** [comment]
So my idea of dropping the C++ header check failed due to $CXX not being exported under the "c" language option in Travis. That slipped into being checked in even though it failed due to the checks of what was changed thought a change to .travis.yml didn't warrant running the test suite.

I'm pointing this out here in case gcc or any other Travis change occurs where the test suite needs to run. Best option is to probably disable the check for whether the suite needs to run and then after it has been fully verified to put the check back to where it was.

**Comment by brettcannon** [comment]
An idea that I had from a discussion in python/cpython#743 is we could roll the gcc build into the coverage run. IOW we keep clang for the testing build but use gcc for the coverage build. While failures in the coverage run won't trigger a blocking failure, it will still at least be visible.

**Comment by brettcannon** [comment]
Created python/cpython#853 to try dropping the gcc build.
