### ISSUE TITLE
Request for Proofreader membership

### ISSUE THREAD

**Issue by encukou** [python/core-workflow#461]
# Request for Proofreader membership

Please add the following volunteers to the @python GitHub org and the `proofreaders` team.
This team has no special privileges, it exists so it can be mentioned for help with wordsmithing. More info: https://discuss.python.org/t/16319

Volunteers to add:

* [x] @mwichmann  (Mats Wichmann)
* [x] @bskinn (Brian Skinn)

**Comment by ewdurbin** [comment]
Invitations dispatched. Once accepted this issue can be closed!
