### ISSUE TITLE
Mechanism for getting attention of a python GitHub Organization Owner.

### ISSUE THREAD

**Issue by ewdurbin** [python/core-workflow#462]
I've opened https://github.com/python/devguide/pull/889 to document the now mentionable "Organization Owners" team on the `python` GitHub org.

I'd like us to consider the parts of workflow including Triage membership and the new Proofreaders group to update any process documents related to actions that require [owner level permissions](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization#permissions-for-organization-roles) to include highlighting @python/organization-owners explicitly.

**Comment by ewdurbin** [comment]
cc @Mariatta @encukou

**Comment by encukou** [comment]
Sounds great! Consider adding that mention to [the Triagers template](https://github.com/python/core-workflow/blob/master/.github/ISSUE_TEMPLATE/triage_membership.md), too.

I can actually add people *who are already part of the organization* to `proofreaders` myself. So I'll only mention the owners when necessary.

**Comment by ambv** [comment]
Yes, totally acceptable.

**Comment by ambv** [comment]
This has been in use for 18 months now. We can close it and refine as needed.
