### ISSUE TITLE
Nominate Michael Droettboom for Python triage

### ISSUE THREAD

**Issue by tiran** [python/core-workflow#472]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @mdboom |
| Additional info   | Recommended by @tiran, supported by @Fidget-Spinner and @brandtbucher. Mike is the creator of Pyodide, manager of Faster CPython team, and has helped to solve 3.11 release blocker bugs. |

**Comment by ewdurbin** [comment]
Invitations dispatched.
