### ISSUE TITLE
Request to join the macOS team.

### ISSUE THREAD

**Issue by corona10** [python/core-workflow#476]
@python/organization-owners cc @ronaldoussoren @ned-deily 

Hi
Since I've been involved in several issues with CPython macOS platform,
I want to register myself to @python/macos-team for supporting the macOS platform.
I would like to know the process for this. (Who to ask, who can register me to the group)
I always appreciate all your hard work.

Warm regards,
Dong-hee

**Comment by ned-deily** [comment]
@corona10, welcome to the team

**Comment by corona10** [comment]
@ned-deily Thank you!
