### ISSUE TITLE
Request for Python Triage Membership: @barneygale

### ISSUE THREAD

**Issue by barneygale** [python/core-workflow#485]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @barneygale |
| bpo username   | barneygale |
| Additional info   | I'd like to help triage pathlib and os.path issues and pull requests. |

**Comment by CAM-Gerlach** [comment]
Hey Barney, thanks for submitting this! It seems to me that a lot of people, including myself, would be thrilled to see you join the triage team :) In fact, you were recommended for it previously in recognition of your tireless work on `pathlib` in the face of many obstacles, it just apparently got lost in the shuffle before a core dev submitted a request here.

The only thing is that a core dev needs to sponsor the request here first. However, if I were to guess, I would think that won't be a problem for long :wink:

**Comment by zware** [comment]
I had thought Barney was already a triager, whoops.  If this needs explicit sponsorship from a core developer to go through, here's mine.

**Comment by AlexWaygood** [comment]
I'd also like to co-sponsor and help mentor @barneygale as a triager. He's been doing tireless work improving pathlib, and seems to be one of the politest people on the internet as far as I can tell.

**Comment by CAM-Gerlach** [comment]
In my own capacity as a triager (among other things), I'd be happy to help "triage" (answer or direct) any questions you may have getting adjusted to the new role. And FWIW, I wanted to share this publicly:

I've been nothing but impressed with his large and consistent effort, and carefully considered and thoughtful approach toward improving pathlib and other related modules over the past years, his excellent communications skills, and his dedication, patience and positivity even in the face of obvious frustration from his work being continually blocked on lack of mentor and reviewer bandwidth. Particularly with the additional motivation, privileges, mentorship and opportunities that being a triager would provide, I'm excited to see where his CPython contributions take him in the future.

I aspire to be as patient, conscientious and wholesome as @barneygale in his work and interactions with others (which I in particular could certainly use, as that's something I need to work on myself), even in the face of obvious frustration and obstacles in getting his work reviewed and merged. Beyond his own contributions to CPython over that time, his positive attitude and interactions with people seems to have encouraged others to contribute to CPython as well, and is a great credit to the project and the community.

**Comment by barneygale** [comment]
Thank you - I really appreciate the vote of confidence. I'll try to live up to the high standards of the project and the triage team. For the sake of balance I feel I must point out that, like everyone, I make mistakes and get frustrated and upset sometimes. So I can't promise 100% wholesomeness and I don't want to be held to that standard! But I'll do my best to contribute constructively where I feel able.

**Comment by Mariatta** [comment]
Thanks @barneygale. I'll also approve this request. Can someone from @python/organization-owners add Barney to the Python Triage Team please?

**Comment by ewdurbin** [comment]
Invitation sent 📤

**Comment by barneygale** [comment]
I seem to have all the permissions I need. Thanks again all!
