### ISSUE TITLE
Python Triage Membership

### ISSUE THREAD

**Issue by subbayaah** [python/core-workflow#486]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @bedevere-bot |
| bpo username   | bedevere     |
| Additional info   | e.g. _"already a bpo triager"_, _"I've made 1 million PRs"_, _"recommended by @miss-islington"_| |

**Comment by AlexWaygood** [comment]
he basically says the same thing every time, thougb

**Comment by CAM-Gerlach** [comment]
I also have a feeling that, considering that he incorrectly triaged her with the `witch` label, he wouldn't be "recommended by @miss-islington"...
