### ISSUE TITLE
Ensure 2FA is enabled!

### ISSUE THREAD

**Issue by ewdurbin** [python/core-workflow#489]
All members of the python organization will soon be required to have 2FA enabled.

Currently some members of @python/python-core and @python/python-triage *do not* have 2FA enabled.

At your earliest convenience, please go to [your account security settings](https://github.com/settings/security) and ensure that the “Two-factor authentication” section shows “Enabled”.

If not, please enable 2FA for your GitHub account according to [GitHub's documentation](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/about-two-factor-authentication). Be sure to save your recovery codes somewhere safe while doing so!

**Comment by hugovk** [comment]
In case it's useful, I write a little script when we were enabling 2FA at work, to check which members of the org didn't have 2FA turned on yet, so I could go and ~hassle~ remind them:

https://github.com/hugovk/github-tools/blob/main/org_users_2fa.py

**Comment by arhadthedev** [comment]
> to check which members of the org didn't have 2FA turned on yet

What's about Bedevere and Miss Islington? I'm working on triggering the former via GitHub Actions but we still need an account token to work with GitHub REST API.

**Comment by ewdurbin** [comment]
@arhadthedev discussion here: https://github.com/python/bedevere/issues/531

**Comment by CAM-Gerlach** [comment]
To note, GitHub has been steadily rolling out 2FA for all users, starting with [the maintainers of depended-upon projects](https://github.blog/2023-03-09-raising-the-bar-for-software-security-github-2fa-begins-march-13/) a couple weeks ago, and concluding with all users by the end of the year. This will include all of us, so all CPython core team members (Triager, Core Dev, etc) will need to have 2FA enabled by around the end of April to continue using their GitHub account.

**Comment by menkotoglou** [comment]
Following @CAM-Gerlach latest comment, is it required that all CPython core team members have 2FA enabled? If so, could this issue close?

**Comment by hugovk** [comment]
It will _soon_ be required.

This at least depends on https://github.com/python/bedevere/pull/569 to resolve https://github.com/python/bedevere/issues/531.

**Comment by ambv** [comment]
Using @hugovk's script, there are still 13 team members without 2FA:
- @aeros
- @akulakov 
- @bitdancer 
- @ctismer 
- @davidmalcolm
- @ericvsmith
- @jcea
- @jdemeyer
- @jeremyhylton
- @LauraGraves
- @sunmy2019
- @terryjreedy
- @theller

**Comment by sunmy2019** [comment]
Done

**Comment by vstinner** [comment]
If these core devs enable 2FA later, they can again merge pull requests?

**Comment by hugovk** [comment]
Yes, but:

If they don't enable 2FA before we require it for the org, they're removed from the org.

If they enable within 3 months, we can reinstate them with the earlier permissions/settings.

If they enable after that, we can re-add them as if they're a new user.

> When you require use of two-factor authentication for your organization, members, outside collaborators, and billing managers who do not use 2FA will be removed from the organization and lose access to its repositories. They will also lose access to their forks of the organization's private repositories. You can reinstate their access privileges and settings if they enable two-factor authentication for their personal account within three months of their removal from your organization.

https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-two-factor-authentication-for-your-organization/requiring-two-factor-authentication-in-your-organization

This isn't necessarily a bad thing, because it can be good for security to remove access when it's not used. And it's not permanent, so can be re-added.

**Comment by vstinner** [comment]
Are you going to contact them? I know a few of them.

**Comment by akulakov** [comment]
I did enable 2FA but I guess I didn’t do it right? I will try again today
or tomorrow..

**Comment by nanjekyejoannah** [comment]
These folks need to be contacted maybe by email before as an example Laura Graves might also lose functionality related to her PSF work unknowingly or she may not be checking and using GitHub actively @LauraGraves .

**Comment by akulakov** [comment]
I've enabled 2FA now.

**Comment by hugovk** [comment]
Reminder that GitHub will "require all developers who contribute code on GitHub.com to enable one or more forms of two-factor authentication (2FA) by the end of 2023".

https://github.blog/2023-03-09-raising-the-bar-for-software-security-github-2fa-begins-march-13/

@ambv Who still needs to enable 2FA?

**Comment by encukou** [comment]
GitHub now requires 2FA for code contributors.
The `python` organization now also requires it for all members. A handful of outside collaborators were removed in that change; see https://github.com/python/steering-council/issues/91#issuecomment-1932716492 (go there to regain access).

I'll close the issue: there's nothing more to do, and it doesn't look like anyone connected to *core workflow* is affected now.
