### ISSUE TITLE
Request for Python triage membership: Oleg Iarygin

### ISSUE THREAD

**Issue by hugovk** [python/core-workflow#490]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @arhadthedev |
| Additional info   | He is doing great work and already has 47 merged PRs and 10 open: https://github.com/python/cpython/pulls?q=is%3Apr+author%3Aarhadthedev+is%3Amerged He also has more that 100 PR reviews: https://github.com/python/cpython/pulls?q=is%3Apr+reviewed-by%3Aarhadthedev |

**Comment by hugovk** [comment]
Ping @python/organization-owners, thanks!

**Comment by ewdurbin** [comment]
Invitation to org/team dispatched.

**Comment by arhadthedev** [comment]
Invitation accepted. Thanks everyone!

**Comment by arhadthedev** [comment]
Can my mannequin be reclaimed, please?

**Comment by hugovk** [comment]
@ezio-melotti Please can you help reclaiming the mannequin?

**Comment by ezio-melotti** [comment]
I believe only org-owners can do that: @python/organization-owners?
There should be a page where to do it somewhere here: https://github.com/python/cpython/settings

**Comment by ewdurbin** [comment]
Done. For reference it is under https://github.com/organizations/python/settings/import-export
