### ISSUE TITLE
Create an organizational account for OpenAI API

### ISSUE THREAD

**Issue by corona10** [python/core-workflow#496]
# The short story
* We need to create an organizational account for OpenAI API
https://platform.openai.com/

# Long version
@Mariatta and I are currently working on developing an internal Discord bot that utilizes OpenAI GPT APIs. However, since the OpenAI API is not free, we are in need of a sponsor from OpenAI to cover the cost. Fortunately, @hauntsaninja has responded positively, and the next step is to create an organizational account.

Related works: https://github.com/python/discord-bot/pull/4

**Comment by corona10** [comment]
cc @python/infrastructure

**Comment by Mariatta** [comment]
And thanks @hauntsaninja and OpenAI for supporting this.

How can we go about creating the OpenAI Python org account? I imagine perhaps an org admin has to do it and perhaps grant access to some of us.
