### ISSUE TITLE
Move the PEPs to Read the Docs

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#5]
Various things need to happen (as outlined as issues in https://github.com/python/peps/issues), but getting the PEPs to build instantly would be good. Could even create peps.python.org.

**Comment by brettcannon** [comment]
I created https://github.com/python/peps/projects/1 to track the work.

**Comment by hugovk** [comment]
Since this issue was opened, we now have PEPs built instantly, hosted on GitHub Pages at https://peps.python.org. We use RTD for build previews.

Shall we close this in favour of https://github.com/python/docs-community/issues/5 which has more discussion?

**Comment by JelleZijlstra** [comment]
Yes, I think this can be tracked elsewhere.
