### ISSUE TITLE
Update the GitHub Sponsors page

### ISSUE THREAD

**Issue by arhadthedev** [python/core-workflow#500]
https://github.com/sponsors/python has outdated links and statistics:

> [...] CPython is developed and maintained largely by volunteers, and has accrued a large backlog of open issues (>7,500 open bugs http://bugs.python.org/) and unmerged code contributions (>1,200 open pull requests https://github.com/python/cpython/pulls).

- http://bugs.python.org/ moved to https://github.com/python/core-workflow/issues
- open bug count dropped to >6,500
- unmerged code contributions raised to >1,400

**Comment by ewdurbin** [comment]
Update applied.
