### ISSUE TITLE
Request for Python triage membership: Steven Sun

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/core-workflow#503]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @sunmy2019 |
| Additional info   | Recommended by @Fidget-Spinner and @JelleZijlstra. Steven has shown a deep understanding of the C codebase, and has been instrumental in debugging reference leaks and memory bugs of multiple CPython PRs. His help is deeply appreciated and his expertise would benefit all parts of CPython. | |

**Comment by erlend-aasland** [comment]
+1 from me to!

**Comment by ewdurbin** [comment]
Invitation dispatched. Please close this issue when it has been accepted.

**Comment by sunmy2019** [comment]
Thanks for the invitation! 🚀
