### ISSUE TITLE
Request for Python triage membership: Itamar Ostricher

### ISSUE THREAD

**Issue by carljm** [python/core-workflow#506]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @itamaro |
| Additional info   | Itamar has been active in core triage and development, with 50+ issues/PRs commented and 20+ merged PRs, and expressed interest to do more. I asked in core dev Discord, there was support from a number of core devs  and no concerns raised. I've worked closely with Itamar for a couple years now and I'm confident he will be a valuable addition to the team. |

**Comment by ewdurbin** [comment]
Invitation has been sent.

**Comment by itamaro** [comment]
thank you!
