### ISSUE TITLE
When cherry_picker fails, drop you off in the checkout

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#51]
I just had a cherry-pick fail, but because I was running `cherry_picker` from its own git repo it took me a minute to realize that I couldn't find the failed branch because I had not `cd cpython` yet. It might work out better to automatically `cd` into the checkout upon failure (with an appropriate message that this was done).

**Comment by Mariatta** [comment]
Sorry about that.. yeah it's definitely something that I need to address. Maybe related to https://github.com/python/core-workflow/issues/45 too

**Comment by brettcannon** [comment]
@Mariatta Nothing to apologize for! Tool worked out great (only issue is GitHub seems to keep thinking I might want to create a PR for the 3.5 branch)!

**Comment by ncoghlan** [comment]
If we did decide to do this (and I think it's reasonable for the interactive case), it would be helpful if it printed two things before exiting:

* a command to finish just the "commit-and-push-and-open-web-browser" steps for the current target branch
* a command to run the cherry-pick again for any not yet processed branches

**Comment by Mariatta** [comment]
Hmm.. I couldn't figure out how to actually ``cd`` to the ``cpython`` directory and let it persist there after cherry_picker.py ended 😅  So instead I'm printing out the message that you need to ``cd cpython`` first..

**Comment by Mariatta** [comment]
Once https://github.com/python/core-workflow/pull/99 is merged, this is not needed anymore since the people will be cherry-picking from cpython directory.
