### ISSUE TITLE
Add a `topic-venv` label

### ISSUE THREAD

**Issue by pradyunsg** [python/core-workflow#510]
> If you want to propose a new label, state the name and the reason for its addition.

`topic-venv`

This would allow grouping the issues relevant to the `venv` module, to simplify triaging for them.

**Comment by ezio-melotti** [comment]
Ok.

**Comment by pradyunsg** [comment]
Discussed this in-person with @hugovk, @AlexWaygood and @ezio-melotti and added this. :)
