### ISSUE TITLE
Request for Python triage membership: Russell Keith-Magee

### ISSUE THREAD

**Issue by ned-deily** [python/core-workflow#511]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @freakboy3742 |
| Additional info   | Russell has long been involved in developing support for Python for iOS and has been participating in recent Language Summits and Core Developer Sprints. He is very interested in making iOS become a supported platform for cPython releases and many of us are very interested in helping make that happen. As a step towards that, Russell should be given triage membership to participate in triaging iOS-related bugs and with development-related discussions on the python-dev Discord server along the path to full core developer status.  I, among others, will be happy to serve as a mentor. | |

**Comment by ewdurbin** [comment]
Invitation dispatched.
