### ISSUE TITLE
Add a label 'topic-free-threaded' for PEP 703

### ISSUE THREAD

**Issue by corona10** [python/core-workflow#513]
Need to add a new label at CPython repo
See: https://github.com/python/cpython/issues/111062

cc @colesbury @itamaro @hugovk

**Comment by JelleZijlstra** [comment]
Is "free-threaded" the name we're going with? For an internal label "nogil" might be better as it's a very familiar term for core devs.

**Comment by corona10** [comment]
> https://github.com/python/cpython/issues/111062#issuecomment-1783856112

Yeah, I already created with `topic-nogil` but @hugovk suggested `topic-free-threaded`
Then we will work with `topic-nogil` today and if we make the final decision, we can update GAs with the new topic.

**Comment by JelleZijlstra** [comment]
Oh, I missed that the SC explicitly suggested "free-threaded". Let's just go with that term then; I don't want to reopen the discussion.

**Comment by corona10** [comment]
> Oh, I missed that the SC explicitly suggested "free-threaded". Let's just go with that term then; I don't want to reopen the discussion.

Cool!

**Comment by corona10** [comment]
I added the label for `topic-free-threaded`. Please reopen the issue if someone want to discuss :)
