### ISSUE TITLE
Request for Python triage membership: Seth Larson

### ISSUE THREAD

**Issue by hugovk** [python/core-workflow#515]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @sethmlarson |
| Additional info   | Seth is the [PSF Security Developer-in-Residence](https://sethmlarson.dev/security-developer-in-residence), has volunteered to review PRs for SBOM files/tooling (e.g. [python/cpython#112303](https://github.com/python/cpython/pull/112303)) and it would be helpful to list him as the `CODEOWNERS` contact, which is possible as a triager |

**Comment by ewdurbin** [comment]
This is already done! Not sure by whom!

**Comment by ambv** [comment]
I did it 😎

**Comment by ewdurbin** [comment]
🤝
