### ISSUE TITLE
Requesting triage membership for Numpy

### ISSUE THREAD

**Issue by m-newhauser** [python/core-workflow#522]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @m-newhauser |
| Additional info   | I signed up to participate in Numpy triage with CodeTriage and am interested in pursuing this further. I'm happy to work with someone on learning more about triaging before being granted access.| |

**Comment by Mariatta** [comment]
Hi, we don't manage the Numpy project here. This issue template is for requesting triage role for the Core Python project. The Numpy project is managed externally, not by us.

Please check Numpy contributing guide on this doc https://numpy.org/contribute/

Thanks.
