### ISSUE TITLE
Request for Python triage membership: Matt Page

### ISSUE THREAD

**Issue by corona10** [python/core-workflow#527]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @mpage |
| Additional info   | Matt is a committer of the [Cinder](https://github.com/facebookincubator/cinder) project and an active contributor to a free-threading project of CPython. A lot of issues about PEP 703 are discussed on CPython GitHub, and Matt is involved a lot. This permission will be helpful to triage the related issues and also for the successful landing for PEP 703. I am going to mentor his new permission for a while. |

**Comment by corona10** [comment]
cc @erlend-aasland @colesbury @carljm

**Comment by ewdurbin** [comment]
Invite dispatched.

**Comment by mpage** [comment]
Accepted!
