### ISSUE TITLE
Request triage team membership for Brett Simmers

### ISSUE THREAD

**Issue by carljm** [python/core-workflow#528]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @swtaarrs |
| Additional info   | Brett is working actively on free-threading, will be useful to be able to manage free-threading issues and PRs |

**Comment by ewdurbin** [comment]
Invitation dispatched.

**Comment by swtaarrs** [comment]
Looks like I'm all set. Thanks @carljm and @ewdurbin!
