### ISSUE TITLE
Request for Python triage membership: AN Long

### ISSUE THREAD

**Issue by erlend-aasland** [python/core-workflow#529]
# Request for Python Triage membership
@python/organization-owners, please add a new triager: AN Long

|     | Description |
| --- | -------------------------- |
| GitHub username   | @aisk |
| Additional info   | AN Long has been contributing to the CPython code base since 2019, and currently has [11 open PRs](https://github.com/python/cpython/pulls/aisk), and [45 PRs merged to main](https://github.com/python/cpython/pulls?q=is%3Apr+author%3Aaisk+is%3Amerged). His contributions range from documentation updates, through Python and C code bugfixes/features. Isolation of the `winsound`, `winreg`, and `msvcrt` extension modules are examples of the latter. He's also shown interest in helping reviewing open PRs and triaging issues in the bug tracker, and has expressed interested in continued contribution. See also `git log --author=aisk`. |

**Comment by ewdurbin** [comment]
Invite dispatched.

**Comment by aisk** [comment]
Thank you for your help and invitation! @erlend-aasland @ewdurbin
