### ISSUE TITLE
Request for Python triage membership: Malcolm Smith

### ISSUE THREAD

**Issue by encukou** [python/core-workflow#531]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @mhsmith |
| Additional info   | Malcolm is the author of PEP-738 "Adding Android as a supported platform", and I'd like to put him in charge of Android issues. |

@mhsmith, I'll be your mentor. If you'll want to use your permissions for something that's not related to Android, please check with me first.

**Comment by mhsmith** [comment]
Understood.

**Comment by encukou** [comment]
Thank you, Ee!
