### ISSUE TITLE
Try out Datadog CI Visibility for CPython

### ISSUE THREAD

**Issue by hugovk** [python/core-workflow#532]
# The short story

The CPython CI is growing quickly, we'd like to try out some monitoring tools.

# Long version

The [CPython GitHub Actions CI](https://github.com/python/cpython/actions/) is getting more complex. We're testing more operating systems and architectures, and things like free-threaded, JIT, address and thread sanitisation, fuzzing, docs. For [example](https://github.com/python/cpython/actions/runs/8385044602):

<img width="373" alt="image" src="https://github.com/python/core-workflow/assets/1324225/9948454c-1c9d-4474-99ff-49b1ece289d4">

* On the one hand, automated testing is good, it prevents bugs and regressions in a fast-moving project, and means we can better support the hardware used by our users (e.g. [aarch64-apple-darwin was just added to tier 1 in PEP 11](https://github.com/python/peps/pull/3705)).

* On the other, the CI is getting more complex and taking longer to run. We're on the [GitHub Free plan](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits) which limits us to 5 concurrent macOS jobs. During busy periods this has caused builds to wait ~100 minutes before starting, and to mitigate we've begun reducing some testing (https://github.com/python/cpython/pull/116814).

Monitoring could help us see where we're using CI resources and help manage it. Hopefully it would help us see how long different jobs take, how long workflows take within jobs, and so on.

Datadog have a tool called CI Visibility: https://www.datadoghq.com/blog/datadog-github-actions-ci-visibility/ I've not tried it before, but it looks useful.

Datadog also have an Open Source Partner Program to offer free accounts, and I see the PSF is already a partner, using it to monitor PyPI: https://opensource.datadoghq.com/

@ewdurbin Is CI Visibility available for free under the current PSF account and would we be able to try it out for https://github.com/python/cpython? ([Config docs](https://docs.datadoghq.com/continuous_integration/pipelines/github/))

If not, what are the next steps to set up a demo? Thank you!

**Comment by ewdurbin** [comment]
I've configured our datadog account to start collecting these. I'll just need to create a team in our DataDog account to view them and invite folks who will be monitoring.

Let me know who to invite.

**Comment by hugovk** [comment]
Thank you!

Please could you add me? My email's in the voter file. 

I've asked other core devs to comment here if they'd like adding too.

**Comment by ewdurbin** [comment]
I’d prefer to do it in one batch. So let me know when the list is complete.

**Comment by gvanrossum** [comment]
Is this where I should express interest?

**Comment by hugovk** [comment]
This is fine, I'll collect a list and send it to Ee tomorrow or the day after 👍

**Comment by ned-deily** [comment]
Me, too, please!

**Comment by pradyunsg** [comment]
Me too please.

**Comment by willingc** [comment]
Me too please.

**Comment by ewdurbin** [comment]
Invite sent.

**Comment by willingc** [comment]
@ewdurbin Thanks Ee. Login worked just fine.

**Comment by erlend-aasland** [comment]
Too late to get an invite?

**Comment by hugovk** [comment]
@erlend-aasland You should have received an invite now.
