### ISSUE TITLE
Request for Python triage membership:  Peter Lazorchak

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/core-workflow#534]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @lazorchakp |
| Additional info   | Recommended by @Fidget-Spinner and @gvanrossum | |

**Comment by gvanrossum** [comment]
I've seen his work on [gh-116168](https://github.com/python/cpython/issues/116168) and it's great!

**Comment by ewdurbin** [comment]
Invitation dispatched.

**Comment by lazorchakp** [comment]
Accepted. Thanks everyone!

**Comment by Fidget-Spinner** [comment]
Congrats @lazorchakp ! Welcome to the team.
