### ISSUE TITLE
Request for Python triage membership: Savannah Ostrowski

### ISSUE THREAD

**Issue by brandtbucher** [python/core-workflow#537]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @savannahostrowski |
| Additional info   | Savannah has been [very helpful](https://github.com/python/cpython/issues?q=involves%3Asavannahostrowski) in a wide range of areas: everything from fixing tricky C issues involving GC deallocations and jumping in debuggers, to the more "routine" doc updates, triage work, and PR review. Recently, she's been a huge help with moving the new JIT forward, and she's expressed genuine interest and competence in helping me maintain it. This nomination is supported by several core devs, including @ericsnowcurrently, @carljm, @AlexWaygood, @JelleZijlstra, and @Fidget-Spinner. |

**Comment by ewdurbin** [comment]
Invitation dispatched!

**Comment by savannahostrowski** [comment]
Accepted! Thanks so much - super excited to be part of the team! 🎉
