### ISSUE TITLE
Add the "topic-JIT" label

### ISSUE THREAD

**Issue by brandtbucher** [python/core-workflow#538]
# Request for label changes on `python/cpython`

We have a JIT now, and a steadily growing number of issues about it. A dedicated label would be great for easily subscribing to and filtering by these issues for triage and tracking purposes.

**Comment by ezio-melotti** [comment]
Done: https://github.com/python/cpython/labels/topic-JIT

**Comment by brandtbucher** [comment]
Thanks!
