### ISSUE TITLE
Travis tests are broken

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/core-workflow#54]
After all Python tests are passed at the end of the log:
```
$ echo '#include "Python.h"' > test.cc && $CXX -c test.cc -o /dev/null -I ./Include -I .

/home/travis/build.sh: line 62: -c: command not found

The command "echo '#include "Python.h"' > test.cc && $CXX -c test.cc -o /dev/null -I ./Include -I ." exited with 127.

Done. Your build exited with 1.
```
This blocks merging even simple PRs.

**Comment by brettcannon** [comment]
Fixed in https://github.com/python/cpython/pull/718 and I'm starting to cherry-pick now.

**Comment by brettcannon** [comment]
Cherry-picks are in python/cpython#719, python/cpython#720, and python/cpython#721. As soon as they are merged I will close this issue.

**Comment by brettcannon** [comment]
Everything should be fixed. Sorry, everybody.
