### ISSUE TITLE
Request for Python triage membership: Bénédikt Tran

### ISSUE THREAD

**Issue by JelleZijlstra** [python/core-workflow#543]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @picnixz |
| Additional info   | Many useful contributions and reviews in CPython; also a Sphinx maintainer |

**Comment by ewdurbin** [comment]
Invitation dispatched!

**Comment by picnixz** [comment]
I just accepted the invitation. Thank you very much!
