### ISSUE TITLE
Add the `topic-dataclasses` label

### ISSUE THREAD

**Issue by picnixz** [python/core-workflow#545]
There are quite a lot of *recent* issues on dataclasses and Nikita was interested in having this additional label.

- https://github.com/python/cpython/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+dataclass+in%3Atitle
- https://github.com/python/cpython/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+dataclass+in%3Atitle

I'm also tempted to suggest a `topic-enum` label but there has not been enough issues lately on enums so I don't think we need to have this label for now (the number of enum issues is also smaller compared to those on dataclasses).

**Comment by sobolevn** [comment]
My use-case: I subscribe to individual issues' topics on GitHub. I am very interested in `dataclasses.py` and I would love to get notifications about it.

**Comment by carljm** [comment]
A label seems like a good idea to me; I remember wanting to find dataclasses issues and thinking it would be nice if there was a label.

**Comment by ericvsmith** [comment]
I agree with @carljm.

**Comment by picnixz** [comment]
Thanks to that label, I was able to add 45 opened issues to it. I think I'll now go through each of them and see if some of them can be closed.
