### ISSUE TITLE
How to become a CPython triager

### ISSUE THREAD

**Issue by rruuaanng** [python/core-workflow#548]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

Hey, I’ve been pretty active on the main branch of CPython and I’ve been working on resolving issues. I’m interested in becoming a triager. please give me some tips on how to apply and what steps I should follow?

**Comment by rruuaanng** [comment]
Even though I’m primarily a DSP developer. I think my problem-solving skills and experience in development will help me adapt quickly

**Comment by carljm** [comment]
Hi, thanks for your interest in helping to maintain CPython! The process to become a triager is documented at https://devguide.python.org/triage/triage-team/#becoming-a-member-of-the-python-triage-team

New triagers are nominated by a core developer, so to become a triager usually requires sustained useful contributions on the issue tracker for a longer period of time (months or years, not days or weeks), such that members of the core team become familiar with and confident in your contributions. (This doesn't necessarily mean submitting PRs, it can also mean helping to triage issues and review other contributors' PRs.)
