### ISSUE TITLE
Request for Python triage membership: Sergey B Kirpichev 

### ISSUE THREAD

**Issue by vstinner** [python/core-workflow#549]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @skirpichev |
| Additional info   | _"Sergey is helping a lot in the mathematics area (float, Decimal, math and cmath modules)."_, _"recommended by @vstinner"_| |

@vstinner: I asked Sergey and he is interested to become a bug triager. IMO he would be helpful to triage bugs related to maths.

cc @erlend-aasland @serhiy-storchaka

**Comment by ewdurbin** [comment]
Invitation dispatched.

**Comment by sobolevn** [comment]
@skirpichev warm welcome! 🤝

**Comment by skirpichev** [comment]
Thanks, accepted!

Lets hope I'll not break things too often.
