### ISSUE TITLE
Request for Python triage membership: ZeroIntensity

### ISSUE THREAD

**Issue by encukou** [python/core-workflow#550]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @ZeroIntensity |
| Additional info   | Active triager on various issues, mainly C code. Recommended by @encukou | |

**Comment by ewdurbin** [comment]
invitation dispatched.

**Comment by ZeroIntensity** [comment]
Just accepted, thank you!
