### ISSUE TITLE
Request for Python triage membership: Jacob Coffee

### ISSUE THREAD

**Issue by hugovk** [python/core-workflow#551]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @JacobCoffee |
| Additional info   | Jacob is an [Infrastructure Engineer](https://pyfound.blogspot.com/2024/07/announcing-our-new-infrastructure.html) at the PSF and as such, has admin rights over https://github.com/python. He would like to contribute more to CPython outside of work duties and is interested in infra and docs reviews, for which I will mentor. He's also interested in finding a mentor for asyncio or typing. He's been cautious about commenting or approving because his current green tick status might look more "official" than it really is. I recommend Jacob joins the triage team so we follow process and he may continue to contribute. |

**Comment by ewdurbin** [comment]
Added with enthusiasm!

**Comment by JelleZijlstra** [comment]
I'm happy to provide some mentorship around typing, though I think asyncio might need the help more :)
