### ISSUE TITLE
Request for Python triage membership: Diego Russo

### ISSUE THREAD

**Issue by pablogsal** [python/core-workflow#553]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @diegorusso |
| Additional info   | Diego works as a Principal Software Engineer ARM working on CPython. He has authored [many PRs](https://github.com/python/cpython/pulls?q=is%3Apr+author%3Adiegorusso+) adding support for aarch64 to the JIT, helping triaging `perf` integration issues, maintains the ARM neoverse server in speed.python.org and has been very active in conversations. Diego has been always a polite and respectful on his interactions with several other core developers and he is very enthusiastic to continue his journey in core development. I recommend Diego joins the triage team so we follow process and he may continue to contribute.

**Comment by ewdurbin** [comment]
Invitation dispatched.

**Comment by pablogsal** [comment]
Thanks @ewdurbin ❤️

**Comment by diegorusso** [comment]
I humble accept the offer with great pleasure. Thank you all for the trust you give me! As usual, I will do my best to continue improving Python and its ecosystem! I have already accepted the invitation ❤️
