### ISSUE TITLE
Request for Python triage membership: Tomáš Roun

### ISSUE THREAD

**Issue by Eclips4** [python/core-workflow#554]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @tomasr8 |
| Additional info   |  Tomas contributed to CPython for about a year and a half and has [25 merged PRs](https://github.com/python/cpython/pulls?q=is%3Apr+is%3Amerged+author%3Atomasr8). He contributed to many parts of CPython, including AST, ctypes, and made some built-in collections thread-safe for the free threaded build. Recommended by @eclips4 |

**Comment by ewdurbin** [comment]
Invitation dispatched. @tomasr8 please close this issue after you accept it.

**Comment by JelleZijlstra** [comment]
@tomasr8 feel free to ping me too if you have questions about CPython procedures, need help triaging something, or something similar.

**Comment by tomasr8** [comment]
Thanks for the invitation and your trust! Invitation accepted :slightly_smiling_face:

**Comment by Eclips4** [comment]
Welcome to the team, Tomas!
