### ISSUE TITLE
Request for Python Triage membership: Parul Gupta

### ISSUE THREAD

**Issue by willingc** [python/core-workflow#555]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @parul100495 |
| Additional info   | Parul has actively participated in the 2024 Core Dev sprint and is interested in continuing to contribute. Recommended by @willingc |

**Comment by JacobCoffee** [comment]
Invite sent :)
