### ISSUE TITLE
Request for Python triage membership: Jason Fried

### ISSUE THREAD

**Issue by willingc** [python/core-workflow#556]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @fried |
| Additional info   | Jason has been a long-time Python developer and supporter of CPython. He participated in the 2024 Core Dev Sprint and is interested in continued involvement. Recommended by @willingc |

**Comment by JacobCoffee** [comment]
Invite sent :)
