### ISSUE TITLE
Request for Python triage membership: Hood Chatham

### ISSUE THREAD

**Issue by encukou** [python/core-workflow#560]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @hoodmane |
| Additional info   | Hood is a primary maintainer of Pyodide, and for a long time he has championed porting CPython to Emscripten (i.e. WASI in the browser). Emscripten is getting official support again (https://github.com/python/steering-council/issues/256), and IMO Hood is more than ready to triage issues for it. |

**Comment by JacobCoffee** [comment]
invite sent :)
