### ISSUE TITLE
Add "OS-linux" label

### ISSUE THREAD

**Issue by sobolevn** [python/core-workflow#561]
Several times I was searching for "OS-linux" label in cpython's repo for linux-specific issues.
And I was always surprised when I didn't find one.
<img width="297" alt="Снимок экрана 2024-11-21 в 02 48 39" src="https://github.com/user-attachments/assets/471a00f4-826e-4aee-817e-80f39330f28a">

**Comment by sobolevn** [comment]
Example of linux-specific issue: https://github.com/python/cpython/issues/127072

**Comment by AA-Turner** [comment]
Created: https://github.com/python/cpython/labels/OS-linux

A

**Comment by hugovk** [comment]
No objection from me, but note this has been asked before on the 🔒 [Python Core Dev Discord](https://discord.com/channels/854719841091715092/868504620970962944/1162200962862153808) and the answer was that `OS-linux` is assumed to be the default unless otherwise specified.
