### ISSUE TITLE
Request for Python triage membership: Pieter Eendebak

### ISSUE THREAD

**Issue by erlend-aasland** [python/core-workflow#562]
# Request for Python Triage membership
@python/organization-owners, please add a new triager:

|     | Description |
| --- | -------------------------- |
| GitHub username   | @eendebakpt |
| Additional info   | Pieter has been [reviewing PRs](https://github.com/python/cpython/issues?q=++reviewed-by%3Aeendebakpt+-author%3Aeendebakpt), [contributing](https://github.com/python/cpython/pulls?q=author%3Aeendebakpt+is%3Apr) & [proposing](https://github.com/python/cpython/issues?q=is%3Aissue+author%3Aeendebakpt+) changes, and [triaging issues](https://github.com/python/cpython/issues?q=is%3Aissue+involves%3Aeendebakpt+-author%3Aeendebakpt) since early 2022. He shows a good understanding of our development process, and is motivated for continued contribution. I think he will be a valuable addition to our triage team. _Recommended by @erlend-aasland_| |

**Comment by JacobCoffee** [comment]
Invitation sent :)
