### ISSUE TITLE
Add a status check for reverted commits

### ISSUE THREAD

**Issue by berkerpeksag** [python/core-workflow#72]
Currently, it's hard to know why a commit has been reverted. I wonder if we should require to have a "Reason:" field in commit messages.

bedevere seems like a good tool to implement this.

**Comment by Mariatta** [comment]
Maybe we can start by mentioning this in the devguide :thinking:

**Comment by brettcannon** [comment]
You might want to talk to python-committers or python-dev about this before implementing it as I have not heard this issue brought up prior to this issue.

**Comment by brettcannon** [comment]
I should also mention core-workflow is also an acceptable place to ask about this. My point is that since this will be front and centre for everyone it should be discussed at least a little bit before it gets turned on.

**Comment by berkerpeksag** [comment]
I don't really have time and motivation to start an endless thread on a mailing list. This was briefly mentioned by other core developers (I think the last time I read something about this was written by @terryjreedy) on various places over the past few years, but unfortunately I don't have a link.

**Comment by Mariatta** [comment]
This is the most recent message about revert commit message in python-committers:

https://mail.python.org/pipermail/python-committers/2017-April/004389.html

**Comment by brettcannon** [comment]
I agree that people should be filling in a message, I just don't know if requiring a "Reason:" prefix is necessary instead of simply telling people they are expected to give a reason. It's one of those questions of whether we need an explicit check or people just need to pick up the habit?

**Comment by terryjreedy** [comment]
Although I clicked the 'like' button for the message that said 'require Reason: field', I am inclined to what Brett said.  I would prefer a first line of 'Revert xyz because it broke Window buildbot' to having the reason buried in the details, if any.  I also think we should carefully pick what is mechanically required.

**Comment by Mariatta** [comment]
I'm good with just asking people to give a reason, and not needing a status check for it :)

**Comment by brettcannon** [comment]
OK, with the update @Mariatta did to the devguide for providing guidance to have people say why something was reverted I think this can probably be closed. OK with you @berkerpeksag ?

**Comment by berkerpeksag** [comment]
SGTM, thanks @Mariatta!
