### ISSUE TITLE
Add --no-push option to cherry_picker.py

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#78]
I've been thinking of adding `--no-push` option.
It will fetch from upstream, checkout the cherry-pick branch, and do `git cherry-pick`. 
This will allow us to test the change locally before pushing the changes.
Once we're satisfied with it, we can use `--continue` (implemented in #68) that will do the rest (`git push`, open web browser, and delete the branch).

What does everyone think about this?

**Comment by lulouie** [comment]
This sounds great, instead only impl `--continue`, maybe add `--abort` (delete local branch, recover..etc) like `git rebase`?

**Comment by Mariatta** [comment]
`--abort` has also been implemented in #68 (deletes the backport branch and checkout master) so yes, people have both options :)

**Comment by lulouie** [comment]
@Mariatta ah, that's cool. :)
