### ISSUE TITLE
Move Codecov configuration under .github

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#80]
Codecov says the [file can live anywhere](https://docs.codecov.io/docs/codecov-yaml#section-can-i-name-the-file-codecov-yml-), so we might as well move it out of the way.

**Comment by morrme** [comment]
@brettcannon I'd like to help with this one.

**Comment by brettcannon** [comment]
@morrme go for it!

**Comment by brettcannon** [comment]
We should also drop the leading `.` from the filename.
