### ISSUE TITLE
Have Codecov only use the configuration from the master branch

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#81]
Codecov can be set to only [pull the configuration from a specific branch](https://docs.codecov.io/docs/codecov-yaml#section-restricting-changes), so we could set it to only use the configuration from the e.g. master branch so there's only a single file to update.

**Comment by morrme** [comment]
I can do this while tackling the other issue. 

Seems like it's just adding thiat line `strict_yaml_branch: master`

**Comment by brettcannon** [comment]
I'm not quite ready to do this as I'm still thinking through the ramifications of it (e.g. is having custom settings for 3.5 important?).
