### ISSUE TITLE
Require macOS testing for Travis

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#91]
It was initially left off due to how much time it added to a complete run, but since the migration, Travis has added more macOS capacity. It might be time to turn it on again and see how it impacts CI run time.

**Comment by brettcannon** [comment]
I have created python/cpython#1846 to turn on macOS builds.

**Comment by brettcannon** [comment]
Looks like this adds about 10 minutes to the total CI time.

**Comment by brettcannon** [comment]
The builds have  been turned on conditionally. Now we wait to see how much time they add to the whole CI process and whether they are stable.

**Comment by nightlark** [comment]
Does anything else need to get done for this issue (e.g. updated to be done with the GHA workflows instead)?

**Comment by brettcannon** [comment]
Doesn't look like it:
https://github.com/python/cpython/blob/1eb451031a64b4f28d737ee7f394252ae9a76118/.github/workflows/build.yml#L117-L133
