### ISSUE TITLE
Migrate exists PR to a new account?

### ISSUE THREAD

**Issue by mlouielu** [python/core-workflow#92]
Hi all,

I remove my old GitHub account, but there have several opened PR on python/cpython. Is there any protocol to handle this situation? to move a exist PR to a new account?

thanks.

**Comment by Mariatta** [comment]
You can submit a new PR under your new account.
Maybe you can comment on the old PR and ask for it to be closed. I'm assuming you only created new GH account, but using the same bpo account? If you link bpo with your new GH acct, a core dev can try to remove the CLA label on the old PR. ni should now apply the `CLA not signed label`.

**Comment by Mariatta** [comment]
Asked and answered. Closing the issue.
