### ISSUE TITLE
Script to update mention bot based on the experts index

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#95]
https://github.com/python/cpython/blob/master/.mention-bot could be updated based on the contents of https://github.com/python/devguide/blob/master/experts.rst. I don't know how useful that would be, though, since you would suppose that an expert would already be mentioned purely based on the amount of commits they have done to files they were an expert in.

**Comment by brettcannon** [comment]
Another way to do this is if we added appropriate labels and just automatically notify folks who are listed as experts for that label. E.g. the `expert-asyncio` label being added could automatically mention the appropriate people listed in the experts file for asyncio.

**Comment by willingc** [comment]
I like the option of notifying based on label as it better accounts for new core devs. Though, either way seems reasonable. Thanks!

**Comment by brettcannon** [comment]
The only drawback to the label approach is it might lead to a *a lot* of labels as we easily have over 100 classes of expertise in the experts file. 😄 

Perhaps we could auto-assign PRs based on the experts file and leave a message saying, e.g. "This pull request proposes changes to `Lib/turtle.py`, so we have initially assigned this pull request to @willingc thanks to their expertise for the code involved.", or something along those lines. People can obviously unassign themselves, but at least this really should catch people's attention as https://github.com/pulls/assigned is very easy to look at on a regular basis compared to https://github.com/notifications .

**Comment by Mariatta** [comment]
We don't have mention-bot anymore.
Any interest in updating `codeowners` file based on the experts list? Or perhaps core devs prefer to opt in and add their own name to `codeowners`?

**Comment by brettcannon** [comment]
At this point I don't know. 😅

**Comment by heroInCommunity** [comment]
Hey @brettcannon ,
Could you please tell, how do you solve now the issue with recommended reviewers and notifications?

I am creating a tool which identifies recommended reviewers based on their expertise.
It is called efficiefy.io and it is free for OSS.
I would be glad to hear your needs and implement required features.

**Comment by brettcannon** [comment]
@heroInCommunity we don't have a solution beyond using `CODEOWNERS` itself.

**Comment by ezio-melotti** [comment]
Currently we have a few solutions:
* there are a number of `expert-*` (and other) labels that can be added, that notify users that are subscribed to those labels
* there is the `CODEOWNERS` file
* for PRs, GitHub automatically suggest reviewers that recently worked on the files being updated
* there are some teams (e.g. `@python/windows-team`), but we could/should create more
* we have a number of projects (https://github.com/python/cpython/projects?type=beta)

I think this can be closed.
