### ISSUE TITLE
Support requesting a buildbot build for a PR (or personal branch).

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/core-workflow#98]
When debugging a failure (or trying out something new) it can be helpful to run a buildbot against a specific branch.  This used to be an option via hg.python.org, but now only possible via a "custom-buildbot" branch on python/cpython (of where there's only one such branch for everyone to share).  I'd like to be able to request a build on a single buildbot for any PR and any branch belonging to someone in the python-core team (or something like that).

**Comment by ericsnowcurrently** [comment]
@pablogsal, it seems like this has been solved via your bedevere changes a few weeks ago.  Does that seem right?

**Comment by pablogsal** [comment]
> @pablogsal, it seems like this has been solved via your bedevere changes a few weeks ago. Does that seem right?

Yup! Thanks for the ping :+1:
